### ISSUE TITLE
Require proof of private key ownership for matrix account registration

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#1386] opened 2018-04-26 14:34 UTC
## Problem Definition

_This is not strictly a Raiden issue in itself._ 

To make user lookup and communication in general easier under the new matrix transport scheme it's desirable that nodes with a particular Ethereum address map to predictable matrix usernames. 

One way to ensure this is to extend the matrix homeserver with functionality to only allow user registration if the registrant can prove ownership of the private key mapping to the Ethereum address corresponding with the chosen username. This proof can be given in the form of an ecrecoverable signature.

It's possible that the built-in matrix homeserver extension mechanism ("application services") could be used for this purpose but more investigation is necessary

Additionally, as a follow-up to this issue there should be a mechanism for nodes to "report" (TBD what that exactly means) accounts (and the homeserver(s) that allowed those accounts to be created) that fail the signature verification.

**Comment by LefterisJP** [comment] 2018-04-26 15:04
@ulope This is a requirement for the Red Eyes milestone for matrix transport. Correct?

**Comment by ulope** [comment] 2018-04-26 15:46
I'm a bit on the fence for this one.
It would make things a bit nicer in Raiden but OTOH could turn out to be (possibly a lot) more work than expected if it's not doable with a matrix/synapse application service (which may be the case).

Additionally, this will complicate the homeserver setup process a bit.

So I'd say lets keep this for after Red Eyes.

**Comment by LefterisJP** [comment] 2018-04-26 21:30
But how will we identify a matrix address with a user's ethereum's address for the matrix transport to operate? Isn't this what the issue is about? Can we use the matrix transport in Raiden without that property?

**Comment by andrevmatos** [comment] 2018-05-08 09:16
To add on the above, right now, the password with which the node registers itself with the server is the signed homeserver address. With that, we could make a small server-side plugin to ecrecover and reject register requests which fails this validation. OTOH, enforcing that on the server may limit our federation capabilities (we would need to ensure that federating servers also follow these rules for users registering with them). Anyway, it would be only a kind of account spam protection. I think the best approach for actual security is as it is now: any user in any server can send messages, and each node/client will check and validate that signature in the `displayName` matches the address that must be in the `userId` upon receiving the messages. This is done only in the matrix transport, and therefore, doesn't _tie_ Raiden to matrix protocol. Also, it'll continue allowing any compatible matrix server to federate the rooms, keeping decentralization capabilities at maximum.

**Comment by ulope** [comment] 2018-07-31 16:48
Very likely we can use a so called `password provider` for this purpose.

**Comment by andrevmatos** [comment] 2018-08-03 08:24
WIP: https://gist.github.com/andrevmatos/579a80113f6b6a73b35bec46bda81846

**Comment by andrevmatos** [comment] 2018-08-08 13:13
Fixed by #2061 
The production servers and the guide should still be updated to include it, but the code is already merged and integrated into the test synapse server/config.

**Closed by andrevmatos** 2018-08-08 13:13 UTC
Labels: matrix
