### ISSUE TITLE
Unexpected Balance in bf1 Scenario

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5204] opened 2019-11-04 09:56 UTC
## Problem Definition
The scenario player logs shows the presence issue again

`{"json": {"errors": "Payment couldn't be completed because: there is no route available"}, "event": "Received response", "logger": "scenario_player.tasks.api_base", "level": "debug", "timestamp": "2019-11-03 03:48:43.194562"}`

The  `AssertSumTask` task also

`{"task": "<AssertSumTask: {'from': 0, 'balance_sum': 1105000000000000000}>", "event": "Task errored", "logger": "scenario_player.tasks.base", "level": "error", "timestamp": "2019-11-03 05:12:08.287310", "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 74, in __call__\n    return self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 70, in _run\n    return self._process_response(response_dict)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/channels.py\", line 254, in _process_response\n    f'Expected sum value \"{assert_value}\" for channel fields \"{field}\". '\nscenario_player.exceptions.legacy.ScenarioAssertionError: Expected sum value \"1105000000000000000\" for channel fields \"balance\". Actual value: \"1106000000000000000\". Channels: [{'total_deposit': 1000000000000000000, 'token_network_address': '0xDa1fBc048f503635950058953f5c60FC1F564ee6', 'total_withdraw': 0, 'state': 'opened', 'partner_address': '0xfEA8f4F5B6c015a9DC6b6D51B2f6C76ca36B5219', 'reveal_timeout': 20, 'channel_identifier': 1676, 'balance': 1106000000000000000, 'token_address': '0x62083c80353Df771426D209eF578619EE68D5C7A', 'settle_timeout': 40}]"}`

Logs of the Scenario(Edit earlier the wrong logs were uploaded by mistake the correct logs are here)
[Scenario_player_Logs-bf1_basic_functionality-1-latest-2019-11-03.tar.gz](https://github.com/raiden-network/raiden/files/3804092/Scenario_player_Logs-bf1_basic_functionality-1-latest-2019-11-03.tar.gz)

**Comment by err508** [comment] 2019-11-04 11:39
The node logs are from 27.10. please provide the logs from the right run. Also the scenario failed for an balance assertion error and all transfers went through, so please change the title accordingly.

**Comment by agatsoh** [comment] 2019-11-04 13:07
@err508 @rakanalh @karlb Updated the issue with the correct log files

**Comment by karlb** [comment] 2019-11-04 14:05
This is not caused by presence problems:
```
node 0: '0x67e62dd9C1cE3f9580654F92E7943E07016aFF37': <AddressReachability.REACHABLE: 1>
node 1: '0xfEA8f4F5B6c015a9DC6b6D51B2f6C76ca36B5219': <AddressReachability.REACHABLE: 1>
node 2: '0x6667a4E589f094B23F274cd05B277ABE0c5678ea': <AddressReachability.REACHABLE: 1>
node 3: '0x8E0AB430F55A9A598ed0BE2d6baC92D5265fB4CE': <AddressReachability.REACHABLE: 1>
node 4: '0xcf85AEcF4713660CC01e2554b6810a38DD964d58': <AddressReachability.REACHABLE: 1>
```

Here's the output for the route request from the PFS:
```
2019-11-03 03:48:43.101422 [warning  ] Invalid fee calculation        [pathfinding_service.model.token_network] amount=1000000000000000 amount_without_fees=1000000000000000 balance_in=1000000000000000000 balance_out=0 receivable_amount=0 schedule_in=FeeSchedule(cap_fees=True, flat=0, proportional=0, imbalance_penalty=None, timestamp=datetime.datetime(2019, 11, 3, 3, 45, 41, 825775, tzinfo=datetime.timezone(datetime.timedelta(0), '+0000'))) schedule_out=FeeSchedule(cap_fees=True, flat=0, proportional=0, imbalance_penalty=None, timestamp=datetime.datetime(2019, 11, 3, 3, 48, 39, 113629, tzinfo=datetime.timezone(datetime.timedelta(0), '+0000'))) view_in=<ChannelView cid=1677 from=0x8E0AB430F55A9A598ed0BE2d6baC92D5265fB4CE to=0xcf85AEcF4713660CC01e2554b6810a38DD964d58 capacity=0> view_out=<ChannelView cid=1680 from=0xcf85AEcF4713660CC01e2554b6810a38DD964d58 to=0x67e62dd9C1cE3f9580654F92E7943E07016aFF37 capacity=0>
2019-11-03 03:48:43.103041 [debug    ] Checking path validity         [pathfinding_service.model.token_network] nodes=['0x8E0AB430F55A9A598ed0BE2d6baC92D5265fB4CE', '0xcf85AEcF4713660CC01e2554b6810a38DD964d58', '0x67e62dd9C1cE3f9580654F92E7943E07016aFF37'] value=1000000000000000
2019-11-03 03:48:43.103598 [debug    ] Creating Path object           [pathfinding_service.model.token_network] fees=[] is_valid=False nodes=['0x8E0AB430F55A9A598ed0BE2d6baC92D5265fB4CE', '0xcf85AEcF4713660CC01e2554b6810a38DD964d58', '0x67e62dd9C1cE3f9580654F92E7943E07016aFF37']
2019-11-03 03:48:43.104177 [debug    ] Checking path validity         [pathfinding_service.model.token_network] nodes=['0x8E0AB430F55A9A598ed0BE2d6baC92D5265fB4CE', '0xcf85AEcF4713660CC01e2554b6810a38DD964d58', '0x67e62dd9C1cE3f9580654F92E7943E07016aFF37'] value=1000000000000000
2019-11-03 03:48:43.104667 [warning  ] Invalid fee calculation        [pathfinding_service.model.token_network] amount=1000000000000000 amount_without_fees=1000000000000000 balance_in=1000000000000000000 balance_out=0 receivable_amount=0 schedule_in=FeeSchedule(cap_fees=True, flat=0, proportional=0, imbalance_penalty=None, timestamp=datetime.datetime(2019, 11, 3, 3, 45, 38, 955047, tzinfo=datetime.timezone(datetime.timedelta(0), '+0000'))) schedule_out=FeeSchedule(cap_fees=True, flat=0, proportional=0, imbalance_penalty=None, timestamp=datetime.datetime(2019, 11, 3, 3, 45, 38, 961085, tzinfo=datetime.timezone(datetime.timedelta(0), '+0000'))) view_in=<ChannelView cid=1678 from=0x6667a4E589f094B23F274cd05B277ABE0c5678ea to=0xfEA8f4F5B6c015a9DC6b6D51B2f6C76ca36B5219 capacity=0> view_out=<ChannelView cid=1676 from=0xfEA8f4F5B6c015a9DC6b6D51B2f6C76ca36B5219 to=0x67e62dd9C1cE3f9580654F92E7943E07016aFF37 capacity=0>
2019-11-03 03:48:43.106133 [debug    ] Checking path validity         [pathfinding_service.model.token_network] nodes=['0x8E0AB430F55A9A598ed0BE2d6baC92D5265fB4CE', '0x6667a4E589f094B23F274cd05B277ABE0c5678ea', '0xfEA8f4F5B6c015a9DC6b6D51B2f6C76ca36B5219', '0x67e62dd9C1cE3f9580654F92E7943E07016aFF37'] value=1000000000000000
2019-11-03 03:48:43.106954 [debug    ] Creating Path object           [pathfinding_service.model.token_network] fees=[] is_valid=False nodes=['0x8E0AB430F55A9A598ed0BE2d6baC92D5265fB4CE', '0x6667a4E589f094B23F274cd05B277ABE0c5678ea', '0xfEA8f4F5B6c015a9DC6b6D51B2f6C76ca36B5219', '0x67e62dd9C1cE3f9580654F92E7943E07016aFF37']
2019-11-03 03:48:43.107621 [debug    ] Checking path validity         [pathfinding_service.model.token_network] nodes=['0x8E0AB430F55A9A598ed0BE2d6baC92D5265fB4CE', '0x6667a4E589f094B23F274cd05B277ABE0c5678ea', '0xfEA8f4F5B6c015a9DC6b6D51B2f6C76ca36B5219', '0x67e62dd9C1cE3f9580654F92E7943E07016aFF37'] value=1000000000000000
2019-11-03 03:48:43.108209 [info     ] Returning paths for payment    [pathfinding_service.model.token_network] diversity_penalty=5 fee_penalty=100 max_paths=5 paths=[] source=0x8E0AB430F55A9A598ed0BE2d6baC92D5265fB4CE target=0x67e62dd9C1cE3f9580654F92E7943E07016aFF37 value=1000000000000000
2019-11-03 03:48:43.109459 [warning  ] Error while handling request   [pathfinding_service.api] details={'from_': '0x8E0AB430F55A9A598ed0BE2d6baC92D5265fB4CE', 'to': '0x67e62dd9C1cE3f9580654F92E7943E07016aFF37', 'value': 1000000000000000} error=NoRouteFound(None) message=No route between nodes found.
172.23.0.19 - - [2019-11-03 03:48:43] "POST /api/v1/0xDa1fBc048f503635950058953f5c60FC1F564ee6/paths HTTP/1.1" 404 473 0.247653
```

The `Invalid fee calculation` might be the cause of the problem, but I have to check more details before drawing any conclusion.

**Comment by karlb** [comment] 2019-11-04 15:11
The missing route happens for
```
          name: "Make transfer in the direction with no deposit (should fail)"
          tasks:
            - transfer: {from: 3, to: 0, amount: 1_000_000_000_000_000, lock_timeout: 30, expected_http_status: 409}
```
and is an expected part of the scenario. So the only unexplained problem is the wrong balance.

**Comment by karlb** [comment] 2019-11-04 16:06
The relevant part of the scenario is https://github.com/raiden-network/raiden/blob/develop/raiden/tests/scenarios/bf1_basic_functionality.yaml#L202-L234

The time range to the 100 transfers is `select(.timestamp > "2019-11-03 04:53:41.863518" and .timestamp < "2019-11-03 05:10:28.268332")`.

The channel 0->1 starts with a transferred amount of 11_000_000_000_000_000 and ends with 111_000_000_000_000_000. So as expected 100_000_000_000_000_000 tokens have been transferred during the "Make 100 payments from 3 to 0" step.

**Comment by rakanalh** [comment] 2019-11-11 09:13
Duplicate of #5219

**Closed by rakanalh** 2019-11-11 09:13 UTC
Labels: Component / State Machine, Severity / Medium, Type / Bug
