### ISSUE TITLE
Allow parallel channel opening

### ISSUE THREAD

**Issue by kilrau** [raiden-network/raiden#4625] opened 2019-08-15 17:03 UTC
## Intro

It should be possible to open channels in parallel, not forced in sequence. Hopefully there will be a lot of `TokenNetworks` in future, users would have to wait for channels to be opened in sequence, which is a long time. This is especially a very serious limitation for a raiden 'hub' node, which opens channels to multiple users as a service (e.g. inbound liquidity service). Only one user and one channel at a time...

After speaking to @rakanalh ,  original reason for this were race conditions to "lock" balance of a token.

But should be possible to open channels for different token networks in
parallel .

## Problem Definition

Above.

### System Description

N/A

**Comment by hackaugusto** [comment] 2019-09-03 10:02
Just to clarify. Because of how the ERC20 standard works, Raiden has to use `transferFrom` to keep track of the channel deposit. To use the `transferFrom` function, first a call to `approve` is necessary. Because the `approve` function is not monotonic, either the transactions to `approve + deposit` have to be ordered, or if these calls are interleaved then subsequent calls to `approve` must to add to the existing amount, in order to ensure that the following `deposit`s will works.

The problem with the current code base is that sending transactions is completely asynchronous, the proxy will send a transaction, wait for it to be mined, confirmed, and the proceed. That means we don't optimistically send the `approve + deposit` transactions, which result in higher latency when opening multiple channels at the same time.

For a long term solutions this can be fixed with https://github.com/raiden-network/raiden/issues/3268 , which would allow the `TransactionManager` to schedule the transactions and even collapse them if necessary.

Another solution is to reduce the critical section by optimistically sending both transactions, and only holding the lock while the transactions are being created. At the worst case this would make the user waste a transaction (if the approve fails). This can work but it's probably error prone.

**Comment by hackaugusto** [comment] 2019-09-05 12:40
One quick thing that we can do to have a slight improvement is to start with a very high value for the first `approve` call. The idea is to provide a very high allowance to the TokenNetwork on the first deposit, with the assumption that additional channels will be open with the same network, so that the following deposits don't have to wait for two transactions (`approve` + `deposit`), but just for the call to `deposit`.

**Comment by kilrau** [comment] 2019-09-05 12:46
This sound like a good first step, yes. What do you think @offerm

**Comment by Dominik1999** [comment] 2020-02-06 16:37
Discuss with @hackaugusto @Dominik1999 and specify whatever is not yet specified
Overlapping with #5447

**Comment by Dominik1999** [comment] 2020-02-12 14:55
We need to reduce the critical section within the `gas_reserve_lock` here, see
https://github.com/raiden-network/raiden/blob/9b2c12d06ffb558c9a5acfbabc50ec468e195958/raiden/api/python.py#L496

to allow for parallel channel opening with different partners or on different token networks. 

Goal is to increase speed by creating test topologies and what @kilrau said.

**Comment by hackaugusto** [comment] 2020-02-13 11:01
> Another solution is to reduce the critical section by optimistically sending both transactions, and only holding the lock while the transactions are being created. At the worst case this would make the user waste a transaction (if the approve fails). This can work but it's probably error prone.

This was very error prone. We had two problems, gas estimation for the deposit fails if the approve is not mined, and gas estimation returns a low value for an approve if it is done before the deposit is mined (because `deposit` use the whole approved amount and `SSTORE` is more expensive if the storage location has a value of `0`), this means we could only reduce the section had to include the `approve mining`, which allows for concurrent approvals.

**Comment by hackaugusto** [comment] 2020-02-13 11:06
An extra note regarding the section under the lock `gas_reserve_lock`:

https://github.com/raiden-network/raiden/blob/9b2c12d06ffb558c9a5acfbabc50ec468e195958/raiden/api/python.py#L496

The region it protects should include the counter increment:

https://github.com/raiden-network/raiden/blob/dbca37400e905ee28ba3ce6475f4f306e3a05d5e/raiden/network/proxies/token_network.py#L285-L293

Otherwise the gas reserve will be wrong. My proposed solution is to do something like this:

https://github.com/raiden-network/raiden/pull/5848/files#diff-64c10d1678769ab22f3184808718f729R226-R232

Were the transaction allocation is decoupled from the transaction pooling. Which allows the lock to be acquired on the PythonAPI, preventing concurrent changes to the counter, then the gas reserved can be checked with the new channel open, if it is valid, the transaction can be send, the lock released, a and the the polling starts. (Also, the lock should be per token network and not a global lock in the `RaidenService`)

**Comment by Dominik1999** [comment] 2020-02-13 15:41
@hackaugusto please follow up issue blablabla

**Comment by hackaugusto** [comment] 2020-02-14 12:50
follow up: https://github.com/raiden-network/raiden/issues/5446

**Comment by Dominik1999** [comment] 2020-03-19 15:14
@hackaugusto checks if follow up removes the lock, if so close that issue

**Comment by hackaugusto** [comment] 2020-03-19 15:20
The lock was removed by https://github.com/raiden-network/raiden/pull/5887/ we have a follow up to fix a corner case were it is possible to have underestimate the necessary gas reserve.

**Closed by hackaugusto** 2020-03-19 15:20 UTC
Labels: Component / API, Component / Proxies, Component / Smart Contracts, Effort / 1, Topic / Integration
