### ISSUE TITLE
Can't send payment after long inactivity time

### ISSUE THREAD

**Issue by offerm** [raiden-network/raiden#4049] opened 2019-05-12 05:05 UTC
I have two nodes A and B running (on my mac) and connected.
I did a  few payments from A to B without a problem.
Gave them the night. The machine may went to sleep during that time

Next morning I tried to make another payment and failed.
Log shows that the LockTransfer is not being send for A to B.

Restart solve the problem (but is not a solution)

Attached the logs.
Payment identifier: 285858571360508011

A:
[raiden-debug_2019-05-11T20:00:05.392031.log](https://github.com/raiden-network/raiden/files/3169753/raiden-debug_2019-05-11T20.00.05.392031.log)

B:
[raiden-debug_2019-05-11T20:00:06.792606.log](https://github.com/raiden-network/raiden/files/3169751/raiden-debug_2019-05-11T20.00.06.792606.log)

**Comment by ulope** [comment] 2019-05-21 14:26
@offerm The log of node B stops two messages after the time jump to `2019-05-12 04:52`. Did the node perhaps crash?

**Comment by hackaugusto** [comment] 2019-06-13 14:13
@offerm ping

**Comment by offerm** [comment] 2019-06-13 14:16
Sorry. Missed it.

There was not crash. The machine went to sleep and after I resume I couldn't make payments.

Note that this is running on a private network and the miner is not running. It is normal that you don't see any chain activity on the log.

I will try to reproduce it again.

**Comment by ulope** [comment] 2019-06-24 13:58
@offerm From the logs it looks like one of the nodes didn't come back up after the machine sleep. 
I'll just close this for now. If you're able to reproduce please open a new issue linking to this one.

**Closed by ulope** 2019-06-24 13:58 UTC
Labels: matrix, minor bug, needs more info
