### ISSUE TITLE
Add scenario to check for onchain unlocks

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#5178] opened 2019-10-30 13:26 UTC
### Introduction
In order to make sure that we cover as many parts of the functionality as possible we want to have a scenario that checks if on-chain unlocks have taken place. 

### Description
This scenario must somehow in a predictable way assure that there will be locks that have to be unlocked on-chain. Currently there is no predictable way of doing so. One idea is to initiate a mediated transfer and then kill one of the mediating nodes right away, but this is not predictable at all.
For the issue of checking if a lock has been unlocked the, onchain balance of a given token can be asserted once https://github.com/raiden-network/scenario-player/issues/77 is implemented. 

The scenario must open a topology [0, 1, 2, 3] and deposit in both directions. Then a transfer is initialized from node1 to node3. Now a predictable way of killing one of the mediating nodes, must happen so that there is a lock that cannot be unlocked off-chain. When this is done, the scenario must assert the onchain token balance and then wait for the unlock timeout to expire and then assert the on-chain token balance again. The on-chain amount should now be equal to the previous assert plus the unlocked amount.

**Comment by christianbrb** [comment] 2019-10-31 09:10
@Dominik1999 please check with the Raiden client and services team how if an integration test needs to be done and how (balance updates)

**Comment by rakanalh** [comment] 2019-10-31 11:21
To have unlocking happen on-chain, you would need the initiator to send the secret to the target. However, the target should not be able to unlock off-chain with the previous hop (mediator) as the mediator is offline.

The way this is tested in the Raiden client is that we listen for messages and we can trigger certain code to execute when a message is received. In this example, we could stop a mediator node once the target receives `SecretReveal`.

However, because this is internal protocol functionality, none of this is actually exposed to external tools such as the SP. I would suggest doing something as follows:
```
parallel:
  - transfer {...}
  - stop { node: mediator }
```

But it's a bad approach as so many "flaky" stuff could happen such as:
1. PFS getting presence update about mediator going offline before the route is provided to the initiator.
2. Transfer completing before the node is completely stopped. Or at least, completing from the perspective of the target (already completed the unlock with the mediator).

and so on. 

I don't see how this could be accomplished by the SP "reliably" so i would drop the idea altogether. This is a test case that is more suitable to be created as an integration test (and it is).

**Comment by christianbrb** [comment] 2019-10-31 12:34
@rakanalh Thanks for your answer : )

Is there an interaction between PFS, MS and the Raiden client regarding unlock? If yes, we could just test it with the scenario player.

CC @karlb

**Comment by karlb** [comment] 2019-10-31 12:48
> Is there an interaction between PFS, MS and the Raiden client regarding unlock? If yes, we could just test it with the scenario player.

@christianbrb Neither the PFS nor MS have anything directly to do with unlocks. Unlocks happen between Raiden nodes or on-chain.

**Comment by Dominik1999** [comment] 2019-11-01 08:38
@karlb there is no PFSCapacityUpdate being sent after the unlock?

**Comment by karlb** [comment] 2019-11-01 08:55
> @karlb there is no PFSCapacityUpdate being sent after the unlock?

There is. But the PFS does not know the PFSCapacityUpdate is caused by an unlock. If you want to draw conclusions about the unlocks indirectly, it is easier to ask the nodes for their channel balances than to intercept the PFSCapacityUpdates.

**Comment by Dominik1999** [comment] 2019-11-01 08:58
ok, thanks.

**Comment by christianbrb** [comment] 2019-11-14 08:15
@palango This seems to be not testable with the scenario player. I would close this. Is it ok for you? I am asking because it would be an integration test between the services and the client.

**Comment by palango** [comment] 2019-12-09 15:30
Fine for me.

**Closed by palango** 2019-12-09 15:30 UTC
Labels: Component / Scenario Player, Flag / Testing
