### ISSUE TITLE
BF6 Raiden node gets Target does not have a channel with sufficient capacity

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5612] opened 2020-01-09 15:22 UTC
## Problem Definition
In the bf6 stress hub node we get the following exception
```
{
  "task": "<TransferTask: {'from': 8, 'to': 4, 'amount': 1000000000000000, 'expected_http_status': 200}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "timestamp": "2020-01-08 23:28:09.628176",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 74, in __call__\n    return self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 59, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.legacy.RESTAPIStatusMismatchError: HTTP status code \"409\" while fetching http://127.0.0.1:54067/api/v1/payments/0x62083c80353Df771426D209eF578619EE68D5C7A/0x8D025CF1771671369B74A286c1a944bfE45d532e. Expected 200: {\"errors\": \"Payment couldn't be completed because: Target does not have a channel with sufficient capacity ([0] < 1000000000000000)\"}"
}
```

What exception says:

1. **Payment couldn't be completed because: Target does not have a channel with sufficient capacity ([0] < 1000000000000000)** 
`1_000_000_000_000_000`

2. TransferTask
line 152
`- transfer: {from: 8, to: 4, amount: 1_000_000_000_000_000, expected_http_status: 200}`

3. while fetching request 

`http://127.0.0.1:54067/api/v1/payments/0x62083c80353Df771426D209eF578619EE68D5C7A/0x8D025CF1771671369B74A286c1a944bfE45d532e`

logs
https://drive.google.com/drive/folders/1gGDVfBVg0G3APt8po0J-_cBVldPY9Oa1?usp=sharing

**Comment by Dominik1999** [comment] 2020-01-09 15:26
I can reproduce that error locally when running the scenario bf6, if that helps. I can also provide the logs

**Comment by agatsoh** [comment] 2020-01-09 15:30
@Dominik1999 Updated the comment with the logs, had to store in google drive, they were too huge.

**Comment by Dominik1999** [comment] 2020-01-09 15:31
In tonight's run (see logs provided by Sohan) it looked that 
- not every PFSCapacityUpdate was sent by Node8 (only 1 PFSCapacityUpdates with respect to the channel with node 0), and
- that Node0 sent more PFSCapacityUpdates then it should have (11 PFSCapacityUpdates with respect to the channel with node 8)

**Comment by Dominik1999** [comment] 2020-01-10 07:58
Happened again tonight:

- [Scenario Player Logs](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/scenario-player-run_bf6_stress_hub_node_2020-01-09T23%3A03%3A21.log)
- [Node 0](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_47_000/)
- [Node 1](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_47_001/)
- [Node 2](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_47_002/)
- [Node 3](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_47_003/)
- [Node 4](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_47_004/)
- [Node 5](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_47_005/)
- [Node 6](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_47_006/)
- [Node 7](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_47_007/)
- [Node 8](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_47_008/)
- [Node 9](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_47_009/)

**Comment by agatsoh** [comment] 2020-01-13 08:02
Got this exception today as well in the SP runs

**Comment by karlb** [comment] 2020-01-13 09:26
Fixed by https://github.com/raiden-network/raiden/pull/5634, but now I get `Payment couldn't be completed because: Source not online`, which is not caused by the same bug.

**Closed** 2020-01-13 12:22 UTC
Labels: Component / Scenario Player, State / Needs more info
