### ISSUE TITLE
Payment could not be completed

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/raiden#5043] opened 2019-10-07 13:11 UTC
I tried to pay via a channel that was opened automatically when I joined the TestToken token network and kept getting a message saying: “Payment could not be completed because there is no route available”.

I also tried to make a payment to another of my own nodes that I had opened a channel directly with and got the same message on the first couple of tries before the payment went through. This scenario happened with the Mediated Transfers as well, error message a couple of times before the payment passed.

Raiden 0.200.0rc1
[raiden-debug_2019-10-07T11:28:06.284028.log.zip](https://github.com/raiden-network/raiden/files/3697504/raiden-debug_2019-10-07T11.28.06.284028.log.zip)
[node_0faa9bcd.zip](https://github.com/raiden-network/raiden/files/3697752/node_0faa9bcd.zip)

**Comment by agatsoh** [comment] 2019-10-07 16:28
I am getting the same error in mediated transfers. After a few hours of letting the nodes stay idle and then restarting them. Direct transfers work. but in case of one hop or two hop mediated transfers we get the following messages.
`Payment couldn't be completed because: there is no route available`
`A payment of 10 of the token 0x95B2d84De40a0121061b105E6B54016a49621B44 is being sent to the partner 0xc453Fa8e3258DF2df7Fca7486c21eCE0795aeD62`

**Comment by nephix** [comment] 2019-10-08 09:22
I'm having the exact same issue

**Comment by rakanalh** [comment] 2019-10-08 10:25
As far as i could see in the logs for target node `0x83BEef7079F3cb453CF96d8Dac04F4E199D888F6`:

The node's last known presence state was REACHABLE:

```
{"node": "0x0faA9bCdFcC07E9cCD94c4CC7d799fcCAf22c0C2", "state_changes": [{"network_state": "REACHABLE", "node_address": "0x83BEef7079F3cb453CF96d8Dac04F4E199D888F6", "_type": "raiden.transfer.state_change.ActionChangeNodeNetworkState"}], "event": "State changes", "logger": "raiden.raiden_service", "level": "debug", "greenlet_name": "AlarmTask._run node:0x0faA9bCdFcC07E9cCD94c4CC7d799fcCAf22c0C2", "timestamp": "2019-10-07 11:37:03.838577"}
```

Once the payment is initialized, Raiden queries the PFS for routes to be able to send the payment forward. However, the PFS returns **zero** routes for the payment.
```
{"response": [{"token_network_address": "0x11e5a4247AE70f790fEAb91d6eEbe6fE89D84161", "state": "opened", "channel_identifier": 2, "token_address": "0x1A022b925D370737e95dC0Bf8D7a1a00f7B05766", "reveal_timeout": 50, "settle_timeout": 500, >
{"event": "127.0.0.1 - - [2019-10-07 13:40:59] \"GET /api/v1/channels HTTP/1.1\" 200 885 0.004434", "logger": "raiden.api.rest.pywsgi", "level": "info", "timestamp": "2019-10-07 11:40:59.648467"}
{"node": "0x0faA9bCdFcC07E9cCD94c4CC7d799fcCAf22c0C2", "registry_address": "0x07147fE01573D88B4a8D60f94877d7b47f06e7EC", "token_address": "0x1A022b925D370737e95dC0Bf8D7a1a00f7B05766", "target_address": "0x83BEef7079F3cb453CF96d8Dac04F4E19>
{"initiator": "0x0faA9bCdFcC07E9cCD94c4CC7d799fcCAf22c0C2", "target": "0x83BEef7079F3cb453CF96d8Dac04F4E199D888F6", "token": "0x1A022b925D370737e95dC0Bf8D7a1a00f7B05766", "amount": 500000000000000, "identifier": 1570448460000, "event": "I>
{"node": "b'\\x0f\\xaa\\x9b\\xcd\\xfc\\xc0~\\x9c\\xcd\\x94\\xc4\\xcc}y\\x9f\\xcc\\xaf\"\\xc0\\xc2'", "target": "b'\\x83\\xbe\\xefpy\\xf3\\xcbE<\\xf9m\\x8d\\xac\\x04\\xf4\\xe1\\x99\\xd8\\x88\\xf6'", "amount": 500000000000000, "identifier":>
{"current_user": "@0x0faa9bcdfcc07e9ccd94c4cc7d799fccaf22c0c2:transport03.raiden.network", "node": "0x0faA9bCdFcC07E9cCD94c4CC7d799fcCAf22c0C2", "transport_uuid": "362dee53-e5c7-423a-bbb3-69a6e79363eb", "address": "0x83BEef7079F3cb453CF96>
{"current_user": "@0x0faa9bcdfcc07e9ccd94c4cc7d799fccaf22c0c2:transport03.raiden.network", "node": "0x0faA9bCdFcC07E9cCD94c4CC7d799fcCAf22c0C2", "transport_uuid": "362dee53-e5c7-423a-bbb3-69a6e79363eb", "peer_address": "0x83BEef7079F3cb45>
{"source": "0x0faA9bCdFcC07E9cCD94c4CC7d799fcCAf22c0C2", "target": "0x83BEef7079F3cb453CF96d8Dac04F4E199D888F6", "amount": 500000000000000, "target_is_direct_partner": true, "can_use_pfs": true, "event": "Getting route for payment", "logg>
{"url": "https://pfs-rinkeby.services-dev.raiden.network", "token_network_address": "b'\\x11\\xe5\\xa4$z\\xe7\\x0fy\\x0f\\xea\\xb9\\x1dn\\xeb\\xe6\\xfe\\x89\\xd8Aa'", "payload": {"from": "0x0faA9bCdFcC07E9cCD94c4CC7d799fcCAf22c0C2", "to":>
{"event": "PFS cannot find a route: No route between nodes found. (2201).", "logger": "raiden.network.pathfinding", "level": "info", "timestamp": "2019-10-07 11:41:00.470590"}
{"routes": [], "feedback_token": null, "event": "Received route(s) from PFS", "logger": "raiden.routing", "level": "info", "timestamp": "2019-10-07 11:41:00.471258"}
```

Making the payment ffail because of the lack of routes.

**Comment by Dominik1999** [comment] 2019-10-08 14:50
I also have this issue almost all the time now. I tried with scenarios and triggering transfers manually via the WebUI. 

The PFS returns 0 routes most of the time, because it does not see all nodes of the route <Reachable>. There is probably some matrix error. The reachability of the nodes fluctuated a lot according to the pfs even if from my perspective the Raiden node was running stable. 

I have plenty of logs, if needed for debugging. But it looks like everyone can reproduce that error

**Comment by Dominik1999** [comment] 2019-10-09 08:12
Maybe it is not a matrix issue afterall ...

- I have here a payment that expired
```
{
  "node": "0xeC95F1C57df7e19D2FEBfB4304a2C214FF2fC55B",
  "raiden_events": [
    {
      "balance_proof": {
        "balance_hash": "0xea15fd75f86737031bc8d27bc106501264b7fc1e6625ff7966336844fb654fb4",
        "transferred_amount": 1000000000000000,
        "locked_amount": 0,
        "canonical_identifier": {
          "chain_identifier": "5",
          "token_network_address": "0x9526EC0E58ac5Bb1e24d655E964f0eAA46054d16",
          "channel_identifier": "1541"
        },
        "nonce": "5",
        "locksroot": "0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470"
      },
      "secrethash": "0x9fd17c8660da91f6b3ec954de633677a79e7b5112f8ba17727337026c3c9ef73",
      "recipient": "0xfcDb847C01a71b3bc9C224152eC8ee9ac2ea49b3",
      "canonical_identifier": {
        "chain_identifier": "5",
        "token_network_address": "0x9526EC0E58ac5Bb1e24d655E964f0eAA46054d16",
        "channel_identifier": "1541"
      },
      "message_identifier": "5930000474947421878",
      "_type": "raiden.transfer.mediated_transfer.events.SendLockExpired"
    },
    {
      "reason": "lock expired",
      "token_network_registry_address": "0x754b1Fa6bcb43F09557Eb5A212513F40A263DAF8",
      "token_network_address": "0x9526EC0E58ac5Bb1e24d655E964f0eAA46054d16",
      "target": "0x6BBA688D4C91F3660Ca61EE9cacC37D940DB291B",
      "identifier": "4355725369288512701",
      "_type": "raiden.transfer.events.EventPaymentSentFailed"
    },
    {
      "secrethash": "0x9fd17c8660da91f6b3ec954de633677a79e7b5112f8ba17727337026c3c9ef73",
      "route": [
        "0xeC95F1C57df7e19D2FEBfB4304a2C214FF2fC55B",
        "0xfcDb847C01a71b3bc9C224152eC8ee9ac2ea49b3",
        "0x6BBA688D4C91F3660Ca61EE9cacC37D940DB291B"
      ],
      "token_network_address": "0x9526EC0E58ac5Bb1e24d655E964f0eAA46054d16",
      "_type": "raiden.transfer.mediated_transfer.events.EventRouteFailed"
    },
    {
      "secrethash": "0x9fd17c8660da91f6b3ec954de633677a79e7b5112f8ba17727337026c3c9ef73",
      "identifier": "4355725369288512701",
      "reason": "lock expired",
      "_type": "raiden.transfer.mediated_transfer.events.EventUnlockFailed"
    }

``` 
- the pfs provided a correct route 
```
2019-10-08 18:02:38.757677 [info     ] Returning paths for payment    [pathfinding_service.model.token_network] diversity_penalty=5 fee_penalty=100 max_paths=5 paths=[{'path': ['0xeC95F1C57df7e19D2FEBfB4304a2C214FF2fC55B', '0xfcDb847C01a71b3bc9C224152eC8ee9ac2ea49b3', '0x6BBA688D4C91F3660Ca61EE9cacC37D940DB291B'], 'estimated_fee': 0}, {'path': ['0xeC95F1C57df7e19D2FEBfB4304a2C214FF2fC55B', '0x82bA6EA7605b28918EEcFA671A1fCD6177Ed3767', '0x9218072b3BDcA8C2a73dA1504b9C827416dBb4e4', '0x6BBA688D4C91F3660Ca61EE9cacC37D940DB291B'], 'estimated_fee': 0}] source=0xeC95F1C57df7e19D2FEBfB4304a2C214FF2fC55B target=0x6BBA688D4C91F3660Ca61EE9cacC37D940DB291B value=1000000000000000
```  
- the sender node had all it's neighbours available at the time being 
```
{
  "addresses_uids_and_presence": {
    "0x82bA6EA7605b28918EEcFA671A1fCD6177Ed3767": {
      "@0x82ba6ea7605b28918eecfa671a1fcd6177ed3767:transport02.raiden.network": "online"
    },
    "0xfcDb847C01a71b3bc9C224152eC8ee9ac2ea49b3": {
      "@0xfcdb847c01a71b3bc9c224152ec8ee9ac2ea49b3:transport01.raiden.network": "online"
    },
    "0x6BBA688D4C91F3660Ca61EE9cacC37D940DB291B": {
      "@0x6bba688d4c91f3660ca61ee9cacc37d940db291b:transport02.raiden.network": "online"
    }
  },
  "current_user": "@0xec95f1c57df7e19d2febfb4304a2c214ff2fc55b:transport03.raiden.network",
  "event": "Matrix address manager status",
  "logger": "raiden.network.transport.matrix.utils",
  "level": "debug",
  "timestamp": "2019-10-08 18:02:46.468715"
}
{
  "addresses_uids_and_presence": {
    "0x82bA6EA7605b28918EEcFA671A1fCD6177Ed3767": {
      "@0x82ba6ea7605b28918eecfa671a1fcd6177ed3767:transport02.raiden.network": "online"
    },
    "0xfcDb847C01a71b3bc9C224152eC8ee9ac2ea49b3": {
      "@0xfcdb847c01a71b3bc9c224152ec8ee9ac2ea49b3:transport01.raiden.network": "online"
    },
    "0x6BBA688D4C91F3660Ca61EE9cacC37D940DB291B": {
      "@0x6bba688d4c91f3660ca61ee9cacc37d940db291b:transport02.raiden.network": "online"
    }
  },
  "current_user": "@0xec95f1c57df7e19d2febfb4304a2c214ff2fc55b:transport03.raiden.network",
  "event": "Matrix address manager status",
  "logger": "raiden.network.transport.matrix.utils",
  "level": "debug",
  "timestamp": "2019-10-08 18:03:16.470388"
}
{
  "addresses_uids_and_presence": {
    "0x82bA6EA7605b28918EEcFA671A1fCD6177Ed3767": {
      "@0x82ba6ea7605b28918eecfa671a1fcd6177ed3767:transport02.raiden.network": "online"
    },
    "0xfcDb847C01a71b3bc9C224152eC8ee9ac2ea49b3": {
      "@0xfcdb847c01a71b3bc9c224152ec8ee9ac2ea49b3:transport01.raiden.network": "online"
    },
    "0x6BBA688D4C91F3660Ca61EE9cacC37D940DB291B": {
      "@0x6bba688d4c91f3660ca61ee9cacc37d940db291b:transport02.raiden.network": "online"
    }
  },
  "current_user": "@0xec95f1c57df7e19d2febfb4304a2c214ff2fc55b:transport03.raiden.network",
  "event": "Matrix address manager status",
  "logger": "raiden.network.transport.matrix.utils",
  "level": "debug",
  "timestamp": "2019-10-08 18:03:46.471889"
}

``` 
- and also the mediating node 
```
{
  "addresses_uids_and_presence": {
    "0x6BBA688D4C91F3660Ca61EE9cacC37D940DB291B": {
      "@0x6bba688d4c91f3660ca61ee9cacc37d940db291b:transport02.raiden.network": "online"
    },
    "0xeC95F1C57df7e19D2FEBfB4304a2C214FF2fC55B": {
      "@0xec95f1c57df7e19d2febfb4304a2c214ff2fc55b:transport03.raiden.network": "online"
    },
    "0x9218072b3BDcA8C2a73dA1504b9C827416dBb4e4": {
      "@0x9218072b3bdca8c2a73da1504b9c827416dbb4e4:transport01.raiden.network": "online"
    }
  },
  "current_user": "@0xfcdb847c01a71b3bc9c224152ec8ee9ac2ea49b3:transport01.raiden.network",
  "event": "Matrix address manager status",
  "logger": "raiden.network.transport.matrix.utils",
  "level": "debug",
  "timestamp": "2019-10-08 18:02:37.737978"
}
{
  "addresses_uids_and_presence": {
    "0x6BBA688D4C91F3660Ca61EE9cacC37D940DB291B": {
      "@0x6bba688d4c91f3660ca61ee9cacc37d940db291b:transport02.raiden.network": "online"
    },
    "0xeC95F1C57df7e19D2FEBfB4304a2C214FF2fC55B": {
      "@0xec95f1c57df7e19d2febfb4304a2c214ff2fc55b:transport03.raiden.network": "online"
    },
    "0x9218072b3BDcA8C2a73dA1504b9C827416dBb4e4": {
      "@0x9218072b3bdca8c2a73da1504b9c827416dbb4e4:transport01.raiden.network": "online"
    }
  },
  "current_user": "@0xfcdb847c01a71b3bc9c224152ec8ee9ac2ea49b3:transport01.raiden.network",
  "event": "Matrix address manager status",
  "logger": "raiden.network.transport.matrix.utils",
  "level": "debug",
  "timestamp": "2019-10-08 18:03:07.739388"
}
{
  "addresses_uids_and_presence": {
    "0x6BBA688D4C91F3660Ca61EE9cacC37D940DB291B": {
      "@0x6bba688d4c91f3660ca61ee9cacc37d940db291b:transport02.raiden.network": "online"
    },
    "0xeC95F1C57df7e19D2FEBfB4304a2C214FF2fC55B": {
      "@0xec95f1c57df7e19d2febfb4304a2c214ff2fc55b:transport03.raiden.network": "online"
    },
    "0x9218072b3BDcA8C2a73dA1504b9C827416dBb4e4": {
      "@0x9218072b3bdca8c2a73da1504b9c827416dbb4e4:transport01.raiden.network": "online"
    }
  },
  "current_user": "@0xfcdb847c01a71b3bc9c224152ec8ee9ac2ea49b3:transport01.raiden.network",
  "event": "Matrix address manager status",
  "logger": "raiden.network.transport.matrix.utils",
  "level": "debug",
  "timestamp": "2019-10-08 18:03:37.741372"
}

```

**Comment by rakanalh** [comment] 2019-10-09 09:23
From the case that Talel posted above, what we know so far is:

- We tried to send more than we have deposited
  - Deposit: 100000000000000
  - Transfer: 500000000000000
- The direct channel did not have capacity so we ask PFS.
- The PFS also sees no capacity for this transfer
- Raiden dispatches the transfer and fails

Looking at the code for the transfer, we are lacking a check to make sure balance >= transfer amount. So this is what could be done in this case, otherwise it's a user issue trying to send more than deposited.

**Comment by Dominik1999** [comment] 2019-10-09 12:27
> I'm having the exact same issue

@nephix can you provide the logs and tell us when exactly this issue occurs?

**Comment by rakanalh** [comment] 2019-10-09 12:27
It appears that Dominik's issue was that the BF1 scenario was setting `settle_timeout` and `reveal_timeout` to 40/20 respectively. However, his outdated SP version did not have the code which passes `lock_timeout` param along with the transfer. Which meant that the default lock_timeout value will be larger than the decreased value here in the BF1 nodes therefore the mediator will fail to move the transfer forward causing the transfer to fail. Updating the SP version should suffice.

**Comment by rakanalh** [comment] 2019-10-09 12:44
I'll close this issue as the context seems to be separate between Dominik's case and Talel's one.

**Closed by rakanalh** 2019-10-09 12:44 UTC
Labels: investigating, medium severity bug

**Comment by nephix** [comment] 2019-10-09 12:51
@Dominik1999 sorry I don't have my logs anymore. I will try to same them if I encounter the same issue again
