### ISSUE TITLE
Withdraw transaction isn't sent after ContractSendChannelWithdraw from light client

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden#4749] opened 2019-09-04 21:41 UTC
## Problem Definition

While developing the withdraw reply functionality in the Light Client (raiden-network/light-client#304), on a clean state for both clients on Kovan, a transfer of 105 tokens was sent, which completed successfuly.
Then, from the python client, a withdraw of 40 tokens was requested to test/demo the functionality. The `WithdrawConfirmation` response came with what seems to be the right format and signature, due to the presence in the logs of the events `ReceiveWithdrawConfirmation` and `ContractSendChannelWithdraw`, as well as logs telling about transport stopping retry of the `WithdrawRequest`.
Unfortunately, despite the presence of the `ContractSendChannelWithdraw` event, no transaction seem to have been sent. Withdraw REST request doesn't seem to have returned. Seems like I stopped the node before the `WithdrawExpired` message came, but it shouldn't matter to the fact that the withdraw transaction from the confirmation was not sent.
40s after the above event, there seems to have some lines in the logs about a transaction `#27` being sent, but the time is quite long, and it doesn't seem to have been sent nor mined on the Kovan blockchain.

- [stdout/stderr from the whole run](https://github.com/raiden-network/raiden/files/3576596/raiden_withdraw_noop.log)
- [raiden-debug_2019-09-04T12:58:55.201076.log](https://github.com/raiden-network/raiden/files/3576601/raiden-debug_2019-09-04T12.58.55.201076.log)
- [db: node_aaaaaa21.zip](https://github.com/raiden-network/raiden/files/3576603/node_aaaaaa21.zip)

For reference, the code in Light Client creating the `WithdrawConfirmation` message:
https://github.com/raiden-network/light-client/blob/99644befc3cf17bc0c24fa67724fe1b3e7cbe5c0/raiden-ts/src/transfers/epics.ts#L452-L462

It shouldn't matter as the ContractSend event happened on the Raiden side, but as the Light Client can't afford signing withdraws on every retry, it caches the WithdrawConfirmation response per WithdrawRequest's `message_identifier`, causing the following retries/responses after the confirmation to trigger some `EventInvalidReceivedWithdraw` events because of it was again expecting the nonce after the received WithdrawConfirmation message from us.

### System Description

Docker nightly from yesterday:
```
{
  "raiden": "0.100.5a1.dev159+gd4f7f5e05",
  "raiden_db_version": 23,
  "python_implementation": "CPython",
  "python_version": "3.7.4",
  "system": "Linux 64bit 5.2.11-arch1-1-ARCH",
  "architecture": "x86_64",
  "distribution": "source"
}
```

**Comment by hackaugusto** [comment] 2019-09-05 13:42
The transaction did pass the precondition checks and at least the gas_estimation was done:

> {"description": "set_total_withdraw", "node": "0xAAAAAA219100005A77eF9dEf76b24dfB2cD6B35e", "contract": "0x23E1f3B00e09B60044b223Bacee81eADf8F530ff", "participant": "0xAAAAAA219100005A77eF9dEf76b24dfB2cD6B35e", "partner": "0xE0902284c85A9A03dAA3B5ab032e238cc05CFF9a", "total_withdraw": 40, "event": "Entered", "logger": "raiden.network.proxies.token_network", "level": "debug", "timestamp": "2019-09-04 13:09:08.619342"}

I try to figure out if the transaction was sent at all.

**Comment by hackaugusto** [comment] 2019-09-05 16:42
Since the logs don't have enough information I had to replay the transaction, this is what I did:

```python
from raiden.storage.wal import WriteAheadLog
from raiden.utils.packing import pack_withdraw
from raiden.storage.sqlite import RANGE_ALL_STATE_CHANGES, SerializedSQLiteStorage
from raiden.transfer.architecture import StateManager
from raiden.transfer import node
from raiden.storage.serialization import JSONSerializer
from raiden.transfer.events import ContractSendChannelWithdraw
from eth_keyfile import decode_keyfile_json
import json
from itertools import chain
from eth_keys import keys
from raiden.utils.signer import eth_sign_sha3
from raiden.network.blockchain_service import BlockChainService
from raiden_contracts.contract_manager import ContractManager, contracts_precompiled_path
from raiden.network.rpc.client import JSONRPCClient
from web3 import HTTPProvider, Web3
from eth_utils import decode_hex

db_file = '<redacted>'
key_file = '<redacted>'
password = b'<redacted>'
url = '<redacted>'

tn_address = decode_hex('0x23E1f3B00e09B60044b223Bacee81eADf8F530ff')
web3 = Web3(HTTPProvider(url))
key = keys.PrivateKey(decode_keyfile_json(json.loads(open(key_file).read()), password))
contract_manager = ContractManager(contracts_precompiled_path())
service = BlockChainService(JSONRPCClient(web3, key.to_bytes(), uses_infura=True), contract_manager)
tn = service.token_network(tn_address)

storage = SerializedSQLiteStorage(db_file, JSONSerializer())
all_state_changes = storage.get_statechanges_by_range(RANGE_ALL_STATE_CHANGES)
state_manager = StateManager(state_transition=node.state_transition, current_state=None)
wal = WriteAheadLog(state_manager, storage)

all_events = list()
for _, state_change in enumerate(all_state_changes):
    _, events = wal.state_manager.dispatch([state_change])
    all_events.extend(events)

withdraw_events = list(filter(lambda x: isinstance(x, ContractSendChannelWithdraw), chain.from_iterable(all_events)))
channel_withdraw_event = withdraw_events[0]
our_address = wal.state_manager.current_state.our_address
withdraw_confirmation_data = pack_withdraw(
    canonical_identifier=channel_withdraw_event.canonical_identifier,
    participant=our_address,
    total_withdraw=channel_withdraw_event.total_withdraw,
    expiration_block=channel_withdraw_event.expiration,
)
our_signature = private_key.sign_msg_hash(message_hash=eth_sign_sha3(withdraw_confirmation_data)).to_bytes()

channel_proxy = service.payment_channel(
	canonical_identifier=channel_withdraw_event.canonical_identifier
)

channel_proxy.set_total_withdraw(
	total_withdraw=channel_withdraw_event.total_withdraw,
	expiration_block=channel_withdraw_event.expiration,
	participant_signature=our_signature,
	partner_signature=channel_withdraw_event.partner_signature,
	block_identifier=channel_withdraw_event.triggered_by_block_hash,
)
```

This is what I got as a result:

```
2019-09-05 13:38.11 Entered                        contract=0x23E1f3B00e09B60044b223Bacee81eADf8F530ff description=set_total_withdraw node=0xAAAAAA219100005A77eF9dEf76b24dfB2cD6B35e participant=0xAAAA
AA219100005A77eF9dEf76b24dfB2cD6B35e partner=0xE0902284c85A9A03dAA3B5ab032e238cc05CFF9a total_withdraw=40
2019-09-05 13:38.13 Failed                         contract=0x23E1f3B00e09B60044b223Bacee81eADf8F530ff description=set_total_withdraw node=0xAAAAAA219100005A77eF9dEf76b24dfB2cD6B35e participant=0xAAAA
AA219100005A77eF9dEf76b24dfB2cD6B35e partner=0xE0902284c85A9A03dAA3B5ab032e238cc05CFF9a total_withdraw=40
Traceback (most recent call last):
  File "/home/hack/work/brainbot/raiden/raiden/network/proxies/utils.py", line 122, in log_transaction
    yield
  File "/home/hack/work/brainbot/raiden/raiden/network/proxies/token_network.py", line 1310, in set_total_withdraw
    log_details=log_details,
  File "/home/hack/work/brainbot/raiden/raiden/network/proxies/token_network.py", line 1450, in _set_total_withdraw
    raise RaidenUnrecoverableError("unlock failed for an unknown reason")
raiden.exceptions.RaidenUnrecoverableError: unlock failed for an unknown reason
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/home/hack/work/brainbot/raiden/raiden/network/proxies/payment_channel.py", line 183, in set_total_withdraw
    partner=self.participant2,
  File "/home/hack/work/brainbot/raiden/raiden/network/proxies/token_network.py", line 1310, in set_total_withdraw
    log_details=log_details,
  File "/home/hack/work/brainbot/raiden/raiden/network/proxies/token_network.py", line 1450, in _set_total_withdraw
    raise RaidenUnrecoverableError("unlock failed for an unknown reason")
raiden.exceptions.RaidenUnrecoverableError: unlock failed for an unknown reason
```

The transaction failed at gas estimation.

**Comment by hackaugusto** [comment] 2019-09-05 16:47
@pirapira do you know why the smart contract https://kovan.etherscan.io/address/0x23E1f3B00e09B60044b223Bacee81eADf8F530ff#code is not verified?

**Comment by hackaugusto** [comment] 2019-09-05 17:10
So, the error from the comment [above](https://github.com/raiden-network/raiden/issues/4749#issuecomment-528455275) happened because the withdraw expired. I cannot reproduce the problem, @andrevmatos can you reproduce it?

**Comment by hackaugusto** [comment] 2019-09-05 18:09
@andrevmatos and I did a second test. We did reproduce the problem. 
[This is the log of my run](https://github.com/raiden-network/raiden/files/3580636/raiden-debug_2019-09-05T17.39.28.488914.log).

After that run, I re-executed my script above, and all of a sudden the withdraw worked, and surprisingly, even though my script only sends one transaction, in total 5 appeared in the blockchain:

[28](https://kovan.etherscan.io/tx/0x4629d8a32bef3c2d85417c9daaad676a70b6b22ef85cce1d4f577bd37618a6de)
[27](https://kovan.etherscan.io/tx/0xe31adcef55b5e27b7591853e45c909727db5b75377c1517f0768189f0884e4f3)
[26](https://kovan.etherscan.io/tx/0x6c9262e22ee783b730b399ca24a1a09feb69b6ebbe84dfb9c17e3df4bfeaf320)
[25](https://kovan.etherscan.io/tx/0x4c8d4fe338b78337081414f846fb12ee9a7a481243572eeffd82d4ee7fe7dc19)
[24](https://kovan.etherscan.io/tx/0x2d1c923873a1f98946cd4bc39ed115cc6a76b08bd410cf12d720131cbe1c6aa4)

From my script logs:

```
2019-09-05 14:49.39 Entered                        contract=0x23E1f3B00e09B60044b223Bacee81eADf8F530ff description=set_total_withdraw node=0xAAAAAA219100005A77eF9dEf76b24dfB2cD6B35e participant=0xAAAA
AA219100005A77eF9dEf76b24dfB2cD6B35e partner=0xE0902284c85A9A03dAA3B5ab032e238cc05CFF9a total_withdraw=10
2019-09-05 14:49.40 Calculated gas price for transaction calculated_gas_price=1000000000 node=0xAAAAAA219100005A77eF9dEf76b24dfB2cD6B35e node_gas_price=1000000000
2019-09-05 14:49.40 send_raw_transaction called    gasLimit=134326 gasPrice=1000000000 node=0xAAAAAA219100005A77eF9dEf76b24dfB2cD6B35e nonce=24
2019-09-05 14:49.40 send_raw_transaction returned  gasLimit=134326 gasPrice=1000000000 node=0xAAAAAA219100005A77eF9dEf76b24dfB2cD6B35e nonce=24 tx_hash=0x2d1c923873a1f98946cd4bc39ed115cc6a76b08bd410cf
12d720131cbe1c6aa4
2019-09-05 14:49.45 Exited                         contract=0x23E1f3B00e09B60044b223Bacee81eADf8F530ff description=set_total_withdraw node=0xAAAAAA219100005A77eF9dEf76b24dfB2cD6B35e participant=0xAAAA
AA219100005A77eF9dEf76b24dfB2cD6B35e partner=0xE0902284c85A9A03dAA3B5ab032e238cc05CFF9a total_withdraw=10
```

We know that it sent the nonce `24`. After realizing this I went back to the logs from the issue and found this:

> {"node": "0xAAAAAA219100005A77eF9dEf76b24dfB2cD6B35e", "nonce": 27, "gasLimit": 134326, "gasPrice": 1000000000, "event": "send_raw_transaction called", "logger": "raiden.network.rpc.client", "level": "debug", "timestamp": "2019-09-04 13:09:46.064156"}


And to the logs from my run and found this:

> {"node": "0xAAAAAA219100005A77eF9dEf76b24dfB2cD6B35e", "nonce": 28, "gasLimit": 134326, "gasPrice": 1000000000, "event": "send_raw_transaction called", "logger": "raiden.network.rpc.client", "level": "debug", "timestamp": "2019-09-05 17:44:48.155841"}

So, the problem is that the queue had transactions already, but one of the nonces was missing. Because of this, every new transaction added to the queue never got mined.

**Comment by andrevmatos** [comment] 2019-09-05 18:44
Further investigating, we found the transaction with `nonce=24` in a previous run. It was a minting operation I tried to perform from the webUI, somehow this tx was generated by Raiden (`send_raw_transaction called` & `returned`), incremented the (local?) nonce, but never sent to the node nor mined. Eventually on the tests, the transaction with `nonce=25` was produced and sent, and from there on, even after clearing the state locally (as required to test exclusively with the light client), the queued transactions were already with `nonce>25`, and got stuck on Parity's queue. When Augusto sent another tx with nonce=24 through infura, the queued txs with nonce>=25 were sent as well (and failed).
So, the questions are:
- Why the minting tx (nonce=24) was generated but never sent? Why raiden incremented nonce if the tx wasn't in the (eth node's) queue?
- Any way to prevent this kind of scenario in the future? Is it possible to detect these "roles" in the tx queue, and send transactions with the next available (considering pending transactions only if they're sequential with the already mined transactions) instead of the next after the last queued transaction (which make these queues with roles stuck until the role is somehow filled)?

Logs:
- Log of the run with mint tx nonce=24, never sent: [raiden-debug_2019-09-04T01:22:54.767467.log](https://github.com/raiden-network/raiden/files/3580752/raiden-debug_2019-09-04T01.22.54.767467.log)
- Log of a following run, which tried to send a withdraw with nonce=25: 
[raiden-debug_2019-09-04T03:58:23.468643.log](https://github.com/raiden-network/raiden/files/3580762/raiden-debug_2019-09-04T03.58.23.468643.log)

**Comment by pirapira** [comment] 2019-09-06 07:46
> @pirapira do you know why the smart contract https://kovan.etherscan.io/address/0x23E1f3B00e09B60044b223Bacee81eADf8F530ff#code is not verified?

I do that only TokenNetworkRegistry but not on TokenNetwork.  I opened an issue for that https://github.com/raiden-network/raiden-contracts/issues/1217.

**Comment by hackaugusto** [comment] 2019-09-09 11:29
The transaction `24` could have been culled because of this issue https://github.com/paritytech/parity-ethereum/pull/10901 on parity. I upgraded the kovan node and for now I'm closing the issue because I cannot reproduce the problem.

**Closed by hackaugusto** 2019-09-09 11:29 UTC
Labels: investigating
