### ISSUE TITLE
Transfer unlock failed

### ISSUE THREAD

**Issue by marcosmartinez7** [raiden-network/raiden#3994] opened 2019-05-04 01:08 UTC
- [x] The Ethereum node was always up to date with the chain tip and never stopped running.
- [x] No Ethereum transaction was sent for the account that Raiden manages by another app.
- [x] The Ethereum account used by Raiden always had sufficient ETH.
- [x] The Raiden DB that exists by default at ~/.raiden was never altered or deleted.
- [ ] The Raiden node was never restarted. If yes please provide more info.
- [x] The ethereum node was not switched while Raiden was running.
- [x] The Raiden REST API is protected from public access.

## Problem Definition

Sometimes, when sending a transfer between two nodes, i get `Unlock failed`. The two nodes are up and running. 

Checking the console logs I see that the receiver node is in a **sort of loop** with one message, here is an example:

![image](https://user-images.githubusercontent.com/14795944/57171827-af2b3800-6dee-11e9-84c7-adb83519adb2.png)

As you can see, the node 2 is **ignoring a message because is already in the queue**. I think that is the problem here, the node 1 never receives the response of the balance proof.

**If I reboot both nodes the problem dissapears for a while.**

Here are the logs (if you search for ¨Failed¨ you will see the events):

[raiden-debug_2019-05-02T14_30_20.986999.log](https://github.com/raiden-network/raiden/files/3143917/raiden-debug_2019-05-02T14_30_20.986999.log)
[raiden-debug_2019-05-02T13_25_11.467069.log](https://github.com/raiden-network/raiden/files/3143918/raiden-debug_2019-05-02T13_25_11.467069.log)
[raiden-debug_2019-05-02T13_26_55.397088.log](https://github.com/raiden-network/raiden/files/3143919/raiden-debug_2019-05-02T13_26_55.397088.log)
[raiden-debug_2019-05-02T14_30_14.972097.log](https://github.com/raiden-network/raiden/files/3143920/raiden-debug_2019-05-02T14_30_14.972097.log)

### System Description

```

Geth
Version: 1.8.23-stable
Git Commit: c942700427557e3ff6de3aaf6b916e2f056c1ec2
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.4
Operating System: linux
GOPATH=/home/marcos/gateway
GOROOT=/home/marcos/go


{
  "raiden": "1.1.dev48+gd141f5f6.d20190430",
  "python_implementation": "CPython",
  "python_version": "3.6.7",
  "system": "Linux 64bit_ELF 4.15.0-47-generic x86_64",
  "distribution": "source"
}


```

**Comment by marcosmartinez7** [comment] 2019-05-17 19:13
Hi guys, just wanted to add more information to this issue: 

This seems to be happening when you install the requirements-dev.txt but i cant make it fail again (at least for now) installing the requirements.txt 

That this makes sense for you? The dev dependencies does not seems to be involved on a transfer, maybe the matrix-synapse depdendency is adding the problem

![image](https://user-images.githubusercontent.com/14795944/57950829-bd815580-78be-11e9-8573-587c3d98e7f0.png)

**Comment by marcosmartinez7** [comment] 2019-05-29 17:56
Not 100% sure but i think that  this happens when installing with the dev requirements 

when installed with requirements-dev.txt there is a matrix-synapse library 

![image](https://user-images.githubusercontent.com/14795944/58579483-94978380-8221-11e9-83c6-e44317bdca97.png)

**Comment by rakanalh** [comment] 2019-07-02 12:10
@marcosmartinez7 

We would like to start investigating this issue. Could you please let us know how your setup looks like and how we can reproduce this?

Thanks

**Comment by marcosmartinez7** [comment] 2019-07-02 17:07
Not sure if this issue is relevant now because it was using the v0.100.3-rc2. 

I havent been able to reproduce the behaviour into the latest release. 

**Setup**: 
- Go-ethereum private chain
- 2 Raiden nodes v0.100.3-rc2
- Raiden smart contracts version 0.3._

**Raiden installation from source:**

1. `virtualenv -p <PATH_TO_PYTHON3.6> env`
2`. source env/bin/activate`
3.` pip install -c constraints.txt --upgrade -r requirements-dev.txt` (this step might be related according to my previous comment)
4. `python setup.py develop`

**Raiden nodes initialization:** 

Node 1.

```
raiden --keystore-path $KEYSTORE_PATH --network-id 33 --eth-rpc-endoint http://localhost:8545 --    --tokennetwork-registry-contract-address=$TOKENNETWORK_REGISTRY_CONTRACT_ADDRESS
  --secret-registry-contract-address=$SECRET_REGISTRY_CONTRACT_ADDRESS    --endpoint-registry-contract-address=$ENDPOINT_REGISTRY_CONTRACT_ADDRESS  --no-sync-check
    --api-address=127.0.0.1:5001

```
Node 2

```
raiden --keystore-path $KEYSTORE_PATH --network-id 33 --eth-rpc-endoint http://localhost:8545 --    --tokennetwork-registry-contract-address=$TOKENNETWORK_REGISTRY_CONTRACT_ADDRESS
  --secret-registry-contract-address=$SECRET_REGISTRY_CONTRACT_ADDRESS    --endpoint-registry-contract-address=$ENDPOINT_REGISTRY_CONTRACT_ADDRESS  --no-sync-check
    --api-address=127.0.0.1:5002

```
Both nodes are running into the same machine. The issue happens when doing a payment.

Any other relevant information that i can bring? 


-

**Comment by rakanalh** [comment] 2019-07-03 15:34
Ok, would you mind closing the issue since it's now not reproducible and maybe re-open again if you can reproduce it again? What we would expect to be able to debug this issue is:
1. Logs (which you've provided)
2. Databases of the nodes (to be able to replay the list of state changes).
3. Steps to reproduce this such as: open channel, send transfer or two then stop one of the nodes... i guess you get the idea.

Thank you!

**Closed** 2019-07-03 15:35 UTC
Labels: investigating, matrix, medium severity bug
