### ISSUE TITLE
Expected number of events (1) did not match the number of events found (0) when running the bf1 scenario with different matrix servers

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/raiden#4994] opened 2019-09-27 10:06 UTC
## Problem Definition

Running the scenario [bf1_diff_matrix_node](https://gist.github.com/agatsoh/8d6a3925ce9ee14cd6a60fd239c67190), which is the original [bf1 scenario](https://github.com/raiden-network/raiden/blob/develop/raiden/tests/scenarios/bf1_basic_functionality.yaml) with using different matrix servers.

The following task started 
`[scenario_player.tasks.base] task=<AssertBlockchainEventsTask: {'contract_name': 'TokenNetwork', 'event_name': 'NonClosingBalanceProofUpdated', 'num_events': 1, 'event_args': {'closing_participant': 3}}>`

... and errored:
```
run
    f"Expected number of events ({self.num_events}) did not match the number "
scenario_player.exceptions.legacy.ScenarioAssertionError: Expected number of events (1) did not match the number of events found (0)
```

```
2019-09-27 07:40:41.465367 [error    ] Task errored                   [scenario_player.tasks.base] task=<AssertBlockchainEventsTask: {'contract_name': 'TokenNetwork', 'event_name': 'NonClosingBalanceProofUpdated', 'num_events': 1, 'event_args': {'closing_participant': 3}}>
```
Also see:
- https://gist.github.com/agatsoh/b586ea7ed81e8c0d3aadc677700b3621
- [scenario-player-run_bf1_diff_matrix_node_2019-09-27T10:24:01.log](https://github.com/raiden-network/raiden/files/3661637/scenario-player-run_bf1_diff_matrix_node_2019-09-27T10.24.01.log)

Full logs: [bf1_diff_matrix_nodes_individual_logs.zip](https://github.com/raiden-network/raiden/files/3661644/bf1_diff_matrix_nodes_individual_logs.zip)

**Comment by LefterisJP** [comment] 2019-09-27 10:07
This is a duplicate of: https://github.com/raiden-network/raiden/issues/4990#issuecomment-535873450

**Closed** 2019-09-27 10:50 UTC
