### ISSUE TITLE
Default discovery address error when calling address_encoder(discovery_address)

### ISSUE THREAD

**Issue by xiaoyao1991** [raiden-network/raiden#431] opened 2017-03-13 22:23 UTC
When running raiden with default discovery address, it fails when constructing a `Discovery` object where the constructor tries to call `address_encoder(discovery_address)`. Root cause resides in that `address_encoder` asserts the length of the address to be 20. However, the discovery address is already encoded and has length 40. 

I figured to change where `address_encoder` is called, but I wonder if I'm using it the wrong way. Any pointers?

**Comment by konradkonrad** [comment] 2017-03-15 13:27
Hey @xiaoyao1991 thanks for the report. I'll mark this a duplicate of #425 -- we have to clean up the encoding of addresses, so that user facing addresses are always expected as hex.

**Closed by konradkonrad** 2017-03-15 13:27 UTC
