### ISSUE TITLE
test_assumption_federation_works_after_original_server_goes_down is flaky

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#5508] opened 2019-12-13 09:53 UTC
The test failed:

https://circleci.com/gh/raiden-network/raiden/95350#tests/containers/2

It looks like the test execution is too slow, and the test fails during teardown. Note that there are multiple tests failing at this point, the more likely reason is that the shutdown itself is taking too long and not the test.

**Comment by hackaugusto** [comment] 2020-01-30 14:10
https://circleci.com/gh/raiden-network/raiden/106766#tests/containers/5

**Comment by karlb** [comment] 2020-02-18 10:24
Recent failures:
https://app.circleci.com/jobs/github/raiden-network/raiden/111205/tests
https://app.circleci.com/jobs/github/raiden-network/raiden/111674/tests

The test is fast locally, so there must be something wrong in the CI failure cases except normal slowness.

In both of the above failures I've seen `99: Cannot assign requested address` errors. They appear both in the mirakuru health check output and in the synapse logs.

**Comment by karlb** [comment] 2020-02-21 16:32
If anyone has a look at this and can't fix it, please skip the test. [It failed again](https://app.circleci.com/jobs/github/raiden-network/raiden/112599).

**Comment by fredo** [comment] 2020-02-26 10:47
> Recent failures:
> https://app.circleci.com/jobs/github/raiden-network/raiden/111205/tests
> https://app.circleci.com/jobs/github/raiden-network/raiden/111674/tests
> 
> The test is fast locally, so there must be something wrong in the CI failure cases except normal slowness.
> 
> In both of the above failures I've seen `99: Cannot assign requested address` errors. They appear both in the mirakuru health check output and in the synapse logs.

Looking at the latest logs, it seems that another server is going down while the original one is stopped. Everything works fine until `localhost:8509` is stopped. While stopping the server the connection to `localhost:8511` aborts and cannot be reestablished afterwards.

I could not manage to find the logs for the servers. Where do I find them?

**Comment by fredo** [comment] 2020-03-23 10:28
Can anyone reproduce the error? I can't. 

It seems that the error happens in very rare occasions when connection is not properly closed between the servers while syncing. 

Is anyone able to reproduce this error? It seems like a bug in synapse.

**Comment by fredo** [comment] 2020-03-23 11:23
Another point is that we are currently merging a new synapse version `1.10.1` which we have to see in the future if the problem still happens occasionally. 

I suggest that we close this issue for now and see if at one point the issue comes back with the new synapse version. 

@Dominik1999, whats your thaught on this issue?

**Comment by Dominik1999** [comment] 2020-03-23 12:26
How often did you run the test? If I understand correctly, this test seems or was flaky and it does not happen locally. 

See karl's comment:
> The test is fast locally, so there must be something wrong in the CI failure cases except normal slowness.

If it is not reproducible and you do not see a race condition analytically, let's close and reopen when it happens again.

**Comment by fredo** [comment] 2020-03-23 12:39
I ran the test about 100 times. Locally I was not able to reproduce it. 

According to the synapse server logs, I highly think that this is a synapse related issue and it depends on the moment when the server goes down. I'm gonna close it now and we proceed as discussed

**Closed** 2020-03-23 12:39 UTC
Labels: Effort / 13, Flag / Testing, Topic / Flaky Tests
