### ISSUE TITLE
Consider adding a field for application-level metadata

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#3096] opened 2018-11-29 13:11 UTC
So far we have had the assumption that any non-protocol 3rd party data should be sent out of band and not be piggybacked to the actual raiden messages.

This issue keeps track of deciding
* wheather to add application-level metadata hash into Raiden messages
* and if yes, how
    * an additional field in Raiden messages?
    * make payment_identifier bigger than the current size (64bit)?

This issue is a spawn-out of [a discussion](https://github.com/raiden-network/raiden/issues/3083#issuecomment-442823546).

**Comment by loredanacirstea** [comment] 2019-01-02 11:43
I am in favor of:
- adding application-level metadata hash into Raiden messages
- not using the `payment_identifier`, because it is currently used for other purposes in the client and `256bit` might still be too small (from what I tested)
- we can have an additional field in Raiden messages, named `additional_hash` or `metadata_hash` (as proposed by @LefterisJP in https://github.com/raiden-network/raiden/issues/3083#issuecomment-442823546), that will be included in the `integrity_hash` (https://github.com/raiden-network/raiden/issues/3095)

**Comment by hackaugusto** [comment] 2019-01-14 04:44
This is a duplicate of https://github.com/raiden-network/raiden/issues/1202

**Closed by hackaugusto** 2019-01-14 04:44 UTC
