### ISSUE TITLE
Stress test is flaky with "exceeds block gas limit"

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#2492] opened 2018-09-14 13:49 UTC
As was seen in [this](https://github.com/raiden-network/raiden/pull/2468) PR the stress test seems to be failing in a flaky manner with `ValueError: {'code': -32000, 'message': 'exceeds block gas limit'}[0m`

The complete log can be seen [here](https://gist.github.com/LefterisJP/fb0308cae24e71b896d0593bf1dba069)

**Comment by LefterisJP** [comment] 2018-09-19 09:54
Probably fixed by: https://github.com/raiden-network/raiden/pull/2516 as seen in https://github.com/raiden-network/raiden/pull/2521

**Comment by LefterisJP** [comment] 2018-09-20 11:46
Not fixed yet. After https://github.com/raiden-network/raiden/pull/2441, due to the Travis changes, Travis is slower again and this occurs.

**Comment by hackaugusto** [comment] 2018-09-27 10:40
`ValueError: {'code': -32000, 'message': 'exceeds block gas limit'}` is raised by `web3/manager.py:112`, in [this example](https://api.travis-ci.org/v3/job/434010500/log.txt) `secretRegisterBatch` was called with a `gasLimit=7849262`:

> registerSecretBatch called     contract=feb9ed20 node=d99de5b9 secretshashes=[b'\x96\xa7h \xc7\x8f\xec9Q\xe3\x15\x17\xcb:\xa1zd\xfb\xee\xf0\xfb5\x1a\x1d\xf5d\xed\xf4\xd3\x8aHB'] secretshashes_not_sent=[]
> Calculated gas price for transaction calculated_gas_price=18000000000 node_gas_price=18000000000
> send_raw_transaction called    account=0xD99DE5b9fB7EF25782513DD5A428aA4c590246B8 gasLimit=7849262 gasPrice=18000000000 nonce=5

but the block `gas_limit=6931359`

> STATE CHANGE                   node=8e60a310 state_change=<Block number=377 gas_limit=6931359 block_hash=55fb765d>

The transaction is rejected because it's gas limit is `917903` higher than the block limit

**Comment by andrevmatos** [comment] 2018-09-27 10:59
This is caused by `JSONRPCClient` using the previous block used gas as the gas limit for the next transaction, which is not efficient at all:
https://github.com/raiden-network/raiden/blob/5f0b7796cbd8a749c21ba43f331a8c291a2ad288/raiden/network/rpc/client.py#L221-L224
Solution is do proper gas usage estimation to send a transaction, possibly with progressive (up to a certain limit) increasing this if out-of-gas errors quicks in, but for that, we need to stop doing external tx creationg + send raw tx, and hand all transactions to the client to compose, sign and send it.

**Comment by palango** [comment] 2018-09-28 08:44
Fixed by #2614

**Closed by palango** 2018-09-28 08:44 UTC
Labels: testing
