### ISSUE TITLE
Fail to start: Action not authorized

### ISSUE THREAD

**Issue by chevdor** [raiden-network/raiden#1316] opened 2018-03-20 17:45 UTC
## Problem Definition

After a fresh install from source, raiden fails starting with the following trace:
```
$ raiden --keystore-path ~/Library/Application\ Support/io.parity.ethereum/keys/test --web-ui
Welcome to Raiden, version 0.3.0+git.rce26d056!
Traceback (most recent call last):
  File "/Users/will/projects/raiden/venv-raiden/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/Users/will/projects/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')
  File "/Users/will/projects/raiden/venv-raiden/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/will/projects/raiden/venv-raiden/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/will/projects/raiden/venv-raiden/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/Users/will/projects/raiden/venv-raiden/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/will/projects/raiden/venv-raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/will/projects/raiden/venv-raiden/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/will/projects/raiden/raiden/ui/cli.py", line 706, in run
    with SocketFactory(listen_host, listen_port, strategy=kwargs['nat']) as mapped_socket:
  File "/Users/will/projects/raiden/raiden/network/sockfactory.py", line 75, in __enter__
    mapped_socket = getattr(self, 'map_{}'.format(method))()
  File "/Users/will/projects/raiden/raiden/network/sockfactory.py", line 113, in map_upnp
    self.source_port,
  File "/Users/will/projects/raiden/raiden/network/upnpsock.py", line 146, in open_port
    success = register(internal_port, external_port)
  File "/Users/will/projects/raiden/raiden/network/upnpsock.py", line 142, in register
    '',
Exception: Action not authorized
```

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
uname -a => Darwin KI-2773.fritz.box 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

command -v solc && solc --version => Version: 0.4.20-develop.2018.3.12+commit.2548228b.Darwin.appleclang

command -v geth && geth version => not using

command -v parity && parity --version => version Parity/v1.11.0-unstable-7e948a088-20180313/x86_64-macos/rustc1.24.1

command -v raiden && raiden version => "raiden": "0.3.0+git.rce26d056",
  "python_implementation": "CPython",
  "python_version": "3.6.4",
  "system": "macOS 10.13.3 64bit"

[ -d .git ] && git rev-parse HEAD => ce26d056744cb35015d92c43656aff4e33e6b27c
```

**Comment by palango** [comment] 2018-03-20 18:29
Thanks for reporting this.
This is a problem with out NAT punching code. Can you try to a different method or disable it?

```
  --nat [auto|upnp|stun|none|ext:<IP>[:<PORT>]]
                                  Manually specify method to use for
                                  determining public IP / NAT traversal.
                                  Available methods:
                                  "auto" - Try UPnP, then
                                  STUN, fallback to none
                                  "upnp" - Try UPnP,
                                  fallback to none
                                  "stun" - Try STUN, fallback
                                  to none
                                  "none" - Use the local interface
                                  address (this will likely cause connectivity
                                  issues)
                                  "ext:<IP>[:<PORT>]" - manually
                                  specify the external IP (and optionally port
                                  no.)  [default: auto]
```

**Comment by chevdor** [comment] 2018-03-20 20:07
Thank you @palango. I quickly tried `--nat none` and raiden starts.

**Comment by LefterisJP** [comment] 2018-03-20 21:49
Thanks for trying it out @chevdor. If you have any other problems please write an issue here or in gitter. Note we are reworking our entire transport layer at the moment.

Closing as duplicate of https://github.com/raiden-network/raiden/issues/1095.

**Closed by LefterisJP** 2018-03-20 21:49 UTC
Labels: bug

**Comment by ulope** [comment] 2018-03-20 22:04
Yes, seems similar to #1095. I guess in this case it is probably caused by a router that’s configured to not allow upnp to open ports. The question is we want to invest time in this now or simply live with it until the new transport is there.

**Comment by LefterisJP** [comment] 2018-03-20 22:05
Wait until the new transport is there.
