### ISSUE TITLE
webRTC: Reenable after toDevice message changes

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#6639] opened 2020-11-02 15:46 UTC
In #6629 a new message path using `toDevice` messages was added. This causes some problems as the webRTC session initiation currently expects the communication to happen over matrix rooms.

### Tasks
- [ ] Make `invite`, `answer` and `hangup` messages use `toDevice` messages when enabled
- [ ] Handle receiving session initiation messages with `toDevice` messages
- [x] Reenable `test_web_rtc_message_sync`

**Comment by karlb** [comment] 2020-11-26 15:15
Duplicate of https://github.com/raiden-network/raiden/issues/6701

**Closed by karlb** 2020-11-26 15:15 UTC
Labels: Component / Transport
