### ISSUE TITLE
Presence issue in BF1

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#5285] opened 2019-11-14 09:22 UTC
I ran the BF1 scenario on latest develop yesterday (2b6bcc233b5312788878e0d10f842ca425bb129b)

### Biggest difference between sync calls
`2019-11-13 16:50:35.618260 | 2019-11-13 16:50:55.791961 | 0:00:20.173701`

The `sync` calls now happen with a maximum difference of 20 seconds.

### Presence issues
However the PFS still has wrong presence information for the nodes:

```
5201 ^[[36mpfs-goerli-with-fee_1         |^[[0m {"source": "0xe85baEd489E21b36612993D90B4BD9fF32c8be4C", "target": "0x10918f8e0A0Fe15A36bCCD938899f05cdEaBc4aE", "value": 1     000000000000000, "max_paths": 5, "diversity_penalty": 5, "fee_penalty": 100, "reachabilities": {"0x8FcD78C69005cFCaa512739a05B7Fb4c4cef574f": "<AddressReachability.UN     REACHABLE: 2>", "0x4fc016B482df9273C4Dcb347694a847ae263ddA3": "<AddressReachability.UNREACHABLE: 2>", "0x40561304BB59D22D9e10bfa73a9607Fa0c7F5014": "<AddressReachabil     ity.UNREACHABLE: 2>", "0x38D7ccBe856f09Dcb432897988D16d35A0cC6138": "<AddressReachability.UNREACHABLE: 2>", "0xB3585E4F75b5D9eD7ba75488C6D6DC934B1d089c": "<AddressRea     chability.UNREACHABLE: 2>", "0xeb9E01c4105b2A417b17221022CEC6e8f5763f4b": "<AddressReachability.UNREACHABLE: 2>", "0x9d928AB2e1d0D54C9814029BC51E3fA1B074e128": "<Addr     essReachability.UNREACHABLE: 2>", "0x6cc9f4A546EA013d6eA76C54c99137B2a2b8200e": "<AddressReachability.UNREACHABLE: 2>", "0xB94e524511a99D739F1bC04241Ef14513C2929BA":      "<AddressReachability.UNREACHABLE: 2>", "0x2aeDD36d02F0fC3178B653f7E1096fDc82F256a9": "<AddressReachability.UNREACHABLE: 2>", "0xf5322350d1598674FcB7737C1fDf1257B8AeA     788": "<AddressReachability.UNREACHABLE: 2>", "0x93173CC3b293c6AdcD51D4BeC1E92F87935DABf0": "<AddressReachability.UNREACHABLE: 2>", "0x0E60f242c9D1017100e54D3985EbD9C     1e5Fc646D": "<AddressReachability.UNREACHABLE: 2>", "0xe85baEd489E21b36612993D90B4BD9fF32c8be4C": "<AddressReachability.UNREACHABLE: 2>", "0x9B19E063cFADb4109Ea60287f     0D52BE7B6011392": "<AddressReachability.UNREACHABLE: 2>", "0x72D3bDa01a28AF1035e4BcBB3FAE700335F6bd08": "<AddressReachability.UNREACHABLE: 2>", "0x10918f8e0A0Fe15A36b     CCD938899f05cdEaBc4aE": "<AddressReachability.UNREACHABLE: 2>"}, "event": "Finding paths for payment", "level": "debug", "logger": "pathfinding_service.model.token_ne     twork", "timestamp": "2019-11-13 16:50:24.645558"}
5202 ^[[36mpfs-goerli-with-fee_1         |^[[0m {"error": "NoRouteFound(None)", "details": {"from_": "0xe85baEd489E21b36612993D90B4BD9fF32c8be4C", "to": "0x10918f8e0A0Fe15     A36bCCD938899f05cdEaBc4aE", "value": 1000000000000000}, "message": "No route between nodes found.", "event": "Error while handling request", "level": "warning", "logg     er": "pathfinding_service.api", "timestamp": "2019-11-13 16:50:24.653477"}
```

### Logs

[Archive 4.zip](https://github.com/raiden-network/raiden/files/3845610/Archive.4.zip)

**Comment by hackaugusto** [comment] 2019-11-14 10:52
This is the request:
```
  "details": {
    "from_": "0xe85baEd489E21b36612993D90B4BD9fF32c8be4C",
    "to": "0x10918f8e0A0Fe15A36bCCD938899f05cdEaBc4aE",
    "value": 1000000000000000
  },
```
It was requested twice, and it failed at these times:
```
  "timestamp": "2019-11-13 16:44:07.536268"
  "timestamp": "2019-11-13 16:50:24.653477"
```
This is the first time the initiator becomes available to the PFS just after the PFS sees the channel open event:
```
  "address": "0xe85baEd489E21b36612993D90B4BD9fF32c8be4C",
  "prev_state": "<AddressReachability.UNKNOWN: 3>",
  "state": "<AddressReachability.REACHABLE: 1>",
  "timestamp": "2019-11-13 16:37:36.725033"
```
And it goes offline at this time:
```
  "address": "0xe85baEd489E21b36612993D90B4BD9fF32c8be4C",
  "prev_state": "<AddressReachability.REACHABLE: 1>",
  "state": "<AddressReachability.UNREACHABLE: 2>",
  "timestamp": "2019-11-13 16:41:07.128322"
```
3 minutes before the first request.

**Comment by ulope** [comment] 2019-11-19 11:35
Post-mortem:

- Presence updates were flaky
  - Some old and new bugs / changes in the transport caused delays in calling `/sync` which lead to nodes being considered offline by the servers
  - After fixing those problems presence was still flaky
    - Some nodes reverted to offline state even though they were regularly calling `/sync`.
    - Presence monitoring showed inconsistent presence state for the same users between the servers
- Thursady, 2019-11-14
  - In the evening: Updated Matrix servers to 1.5.1
- Friday, 2019-11-15
  - No change in presence flakiness
  - Noon: @ulope has the hypothesis that synapse split mode is the cause for flaky presence.
    - Changed server configuration to non-split mode
    - Presence monitoring showed consistent results after that
    - Scenarios were still failing because PFS didn't have a route
- Monday, 2019-11-18
  - @hackaugusto discovered that search_user_directory wasn't returning non-local users which lead to the PFS not being able to monitor all relevant nodes
  - Evening: Hypothesis that tainted server state could lead to this behaviour 
    - Server state was backed up and then wiped
    - BF1 scenario ran successfully
    - Server torture test temporarily made user search issue re-appear
      - Monitoring showed big event processing lag of 5+ minutes
      - Synapse debug logging was producing enormous  amounts of logs. Needs to be tested how much influence on performance this has
- Tuesday, 2019-11-19
  - User search behaviour was back to normal
  - BF1 scenarios still succeeding
  - @ulope discovered that he made a mistake when changing the server configuration to non-split on Friday.
    - Namely only changing the `update_user_directory` setting in the synapse config template not the actual config file, which is the likely the cause for the user directory search issue seen on Monday. 
      The state wipe on monday night caused the config file to be regenerated thereby fixing the setting.

It has not been conclusively shown whether split-mode is or isn't the cause for the flaky presence. This will be investigated with a separate transport installation.

**Closed** 2019-11-20 09:36 UTC
Labels: Component / Scenario Player, Component / Transport, State / Investigating, Type / Bug
