### ISSUE TITLE
Repeated opening of channels that have been settled will prompt duplicate channels

### ISSUE THREAD

**Issue by Fang-Li** [raiden-network/raiden#1204] opened 2018-01-17 03:20 UTC
## Problem Definition
when open channel：
{
    "partner_address": "0x589d9cC36aD9b1dB3B6e0b1Fd03a8d842697293F",
    "token_address": "0x3b733dc1d77a2f927d5982a6672e62eadd693828",
    "balance": 100,
    "settle_timeout": 30
}
 ->>>>>>>>>>
Return is like this：
{
    "errors": "Duplicated channel"
}

## Solution
Return should be like this：
    {
        "channel_address": "0x3D45250adA9c0017D2a0EFD8c162271A54568151",
        "partner_address": "0x589d9cC36aD9b1dB3B6e0b1Fd03a8d842697293F",
        "balance": 0,
        "token_address": "0x3B733dC1d77a2F927D5982A6672e62EADd693828",
        "state": "opened",
        "settle_timeout": 30
    }

**Comment by LefterisJP** [comment] 2018-01-17 09:38
Thanks for the report, will take a look and try to reproduce it.

**Comment by LefterisJP** [comment] 2018-01-17 16:03
@Fang-Li I can not reproduce your issue.

Can you specify the exact steps to what lead to your problem?

I did the following:

### Try 1 

1. Opened a channel
2. Closed it
3. Waited till settle timeout expires and the channel is settled.
4. Reopen the channel.

### Try 2

1. Opened a channel
2. Closed it
3. Shut Raiden down
4. Launched Raiden again after the settle timeout blocks have expired
5. Confirmed channel is not there
4. Reopen the channel.

In both of the above cases the returned value was as expected, that of a new channel. I never got the `"Duplicated channel"` error

**Comment by LefterisJP** [comment] 2018-01-23 11:20
Closing this issue since it could not be reproduced.

**Closed by LefterisJP** 2018-01-23 11:20 UTC
