### ISSUE TITLE
Unlock fails after settle

### ISSUE THREAD

**Issue by kelsos** [raiden-network/raiden#3249] opened 2019-01-10 14:51 UTC
This was original experienced on kovan, but I did try to get the flow of actions as close as possible to what I was doing on kovan, but on a private testnet. 

I started trying to replicate the issue on a private testnet with 5 seconds block time, but this also happened on kovan at least twice.

The token network contract address is `0x15008736b8eDf6EaB458D18440876aBd65e57837`

Unfortunately I had a couple of tries trying to reduce the number of transfers send through but I could not get the issue to happen that way.

### Setup

The setup consists of 4 nodes.

Node `A`: `0x60FFe4daDE358246C49C4A16bB5b430d333B5Ce9`
Node `B`: `0x53A9462Be18D8f74C1065Be65A58D5A41347e0A6`
Node `C`: `0x0E809A051034723beE67871a5A4968aE22d36C5A`
Node `D`: `0x88DBDdF47Fe2d8aa2b540b2FF1D83972AF60D41d`

The nodes are in a circular setup because there is need for mediation and an alternative path.
```
A <----> B
▴        ▴
|        |
▾        ▾
D <----> C
```

### Steps

Start 200 transfers from `A` -> `C` and another 200 from `C` -> `A`.
The transfers are originally mediated by `B`, however at some point after around 100 transfers are through the mediator `B` goes offline. 

The sender has a small timeout for the `payment` requests (120 seconds) so the request timeouts on the client, before the lock expires and the client returns a `409` to the sender. Since there is a second available route through `D` the transfers start to go through `D` instead. 

After ~40 *(not exact number)* transfers go through `D`, `B` goes online again and a few transfers got through.

Then `B` closes all the channels and the other nodes follow closing their channels soon after.

### Result

`A` failed to unlock the channel with `B`.
`B` failed to unlock the channel with `A`.
`C` failed to unlock the channel with `D`.
`D` failed to unlock the channel with `A`.

### Logs/Data
The logs and database from the whole network setup are [here](https://drive.google.com/open?id=1WnvkpOI9oWsnqOs1FaAN6WohpJWSHrY3).

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
Linux forseti 4.20.0-arch1-1-ARCH #1 SMP PREEMPT Mon Dec 24 03:00:40 UTC 2018 x86_64 GNU/Linux
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.5.2+commit.1df8f40c.Linux.g++
/usr/bin/geth
Geth
Version: 1.8.20-stable
Git Commit: 24d727b6d6e2c0cde222fa12155c4a6db5caaf2e
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.11.3
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go
/usr/bin/parity
Parity Ethereum
  version Parity-Ethereum/v2.1.10-stable-b47e064f8e-20181213/x86_64-linux-gnu/rustc1.31.0
Copyright 2015-2018 Parity Technologies (UK) Ltd.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann

{
  "raiden": "0.100.2rc2.dev2+gea7a7387",
  "python_implementation": "CPython",
  "python_version": "3.6.7",
  "system": "Linux 64bit_ELF 4.20.0-arch1-1-ARCH x86_64",
  "distribution": "bundled"
}

```

**Comment by LefterisJP** [comment] 2019-01-10 23:25
note: This is on `v0.100.2-rc1`. Wonder why it says `0.100.2rc2` @kelsos

**Comment by kelsos** [comment] 2019-01-11 07:16
@LefterisJP I went through the databases, just to be sure. All nodes seems to started all times with the `rc2` but and there is something really weird going on with `B`. The last log is at 14:00:42 utc, it says it started with `0.100.2rc2.dev2+gea7a7387` and I can see that there is a line in the database that it run on 14:00:47 with the same version. 

I stopped all my nodes at 14:01 to write the issue and the logs confirm the time but there is something weird going on with the database of `B` because it logs in the run table that there are a few runs later using the outdated version of my virtual environment. I am 100% sure that I didn't start the node again after stopping it at 14:01 and there are no logs in my system of a run at the times logged.

I have no idea why or how this might have happened happened but if for some reason at some point the version of the virtual environment was used that all this would make sense.

To answer your question I only used the `rc2` binary I will try it on the previous versions too.

**Comment by kelsos** [comment] 2019-01-11 10:49
So I did another run and the same thing happened again. this time there were no weird values in the database for sure.

**Comment by LefterisJP** [comment] 2019-01-11 16:50
> I repeated the test on v0.100.1 and the issue is also there, so this is not something that broke after v0.100.1

Hmm that sucks. We should look at this asap then. 

We should make a reproducible scenario in a test and find the root cause of the problem.

**Comment by CosminNechifor** [comment] 2019-01-14 13:31
Experienced the same thing on mainnet. Running the ``raiden-v0.100.2rc3.dev2+g04356e2c-linux`` binary. 

### Nodes: 
1. ``0xD6e68536eCe0Eac02b39317FdCE814087Bae6118``
2. ``0xB2C94bBaf307C6DfBf70Cc2537385553385a345b`` <- closing party

### Settle transactions for: 

- ``0xD6e68536eCe0Eac02b39317FdCE814087Bae6118`` can be found [here](https://etherscan.io/tx/0x0f0fd65769e5f7f97651aaab658e41bb422a2c7a92e43b65ee96cc2779a801a9)
- ``0xB2C94bBaf307C6DfBf70Cc2537385553385a345b`` can be found [here](https://etherscan.io/tx/0xa9c4bd47fb85fa47e37a40323b62929ff16138027abc1d734d48f7db1703bbec)

### Logs for the nodes after greping the directory (``grep -r . -e mainnet``): 

- ``0xD6e68536eCe0Eac02b39317FdCE814087Bae6118`` 
[raiden-debug_2019-01-14T09:37:28.050545.log](https://github.com/raiden-network/raiden/files/2755280/raiden-debug_2019-01-14T09.37.28.050545.log)

- ``0xB2C94bBaf307C6DfBf70Cc2537385553385a345b``
[raiden-debug_2019-01-14T09:35:44.975603.log](https://github.com/raiden-network/raiden/files/2755281/raiden-debug_2019-01-14T09.35.44.975603.log)

### System description:

```
Linux cosmin 4.14.83-1-MANJARO #1 SMP PREEMPT Fri Nov 23 18:20:11 UTC 2018 x86_64 GNU/Linux
/usr/bin/geth
Geth
Version: 1.8.19-stable
Git Commit: dae82f098570e15d44584f0d7f350713f4774727
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.11.2
Operating System: linux
```

**Comment by rakanalh** [comment] 2019-01-21 09:39
Looking at the logs, i can see one log item which says:
```
{
  "event": "Unlock not done. Failed to find state/event that match current channel locksroots. token:0x28104EE15e1c70c421150865C3fb731c426929E6 token_network:0x15008736b8eDf6EaB458D18440876aBd65e57837 channel:7 participant:0x60FFe4daDE358246C49C4A16bB5b430d333B5Ce9 our_locksroot:0x0000000000000000000000000000000000000000000000000000000000000000 partner_locksroot:0x73863f4d1057ea77d274e5a827bae2d1612288378e196e59f7e63519b8d8c8a0 ",
  "logger": "raiden.raiden_event_handler",
  "level": "warning",
  "timestamp": "2019-01-10 14:00:51.586733"
}
```

Going through the database for that channel and participants... it seems like i can manage to find the related state change which matches the partner's locksroot:
```
from raiden.transfer.utils import (
    get_state_change_or_event_with_balance_proof,
)
# event is ContractSendChannelClose
record = get_state_change_or_event_with_balance_proof(
    storage=storage,
    chain_id=event.balance_proof.chain_id,
    token_network_identifier=event.balance_proof.token_network_identifier,
    channel_identifier=event.balance_proof.channel_identifier,
    is_our_unlock=False,
    is_partner_unlock=True,
    our_balance_hash=bytes(32),
    partner_balance_hash=event.balance_proof.balance_hash,
    sender=event.balance_proof.sender,
)
return record
```
```
StateChangeRecord(
state_change_identifier=2801, 
data=<ActionInitMediator 
from_route:<RouteState 
    hop:60ffe4da 
    channel_identifier:7> 
from_transfer:<LockedTransferSignedState 
    msgid:17478391825401427624 
    id:1547126196 token:0x28104ee15e1c70c421150865c3fb731c426929e6 
    lock:<HashTimeLockState 
      amount:1 
      expiration:1949 
      secrethash:12964045> 
    target:0x0e809a051034723bee67871a5a4968ae22d36c5a>>
)
```

**Comment by kelsos** [comment] 2019-01-28 10:54
@rakanalh I will checkout master and go through it

**Comment by rakanalh** [comment] 2019-01-31 13:09
@kelsos confirms he has not seen this problem since RC3. Closing.

**Closed by rakanalh** 2019-01-31 13:09 UTC
Labels: P1, investigating, medium severity bug

**Comment by kelsos** [comment] 2019-01-31 13:13
Yes I did run a few tests and I was unable to replicate the issue, on either rinkeby or a private chain setup.
