### ISSUE TITLE
Scenario player fails to download raiden release

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#3582] opened 2019-03-05 10:08 UTC
When running the scenario player it tries to download a raiden release and fails at that, because https://raiden-nightlies.ams3.digitaloceanspaces.com/raiden-v/home/pirate/raiden/venv/RaidenClient/bin/raiden-linux.tar.gz does not exist. Is the path wrong, or is the nightly missing due to some problem?

Traceback:
```
/raiden_releases/downloads/raiden-v/home/pirate/raiden/venv/RaidenClient/bin/raiden-linux.tar.gz' Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/karl/raiden/tools/scenario-player/scenario_player/__main__.py", line 8, in <module>
    main(prog_name='python -m scenario_player')
  File "/home/karl/tools/venv/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/karl/raiden/tools/scenario-player/scenario_player/main.py", line 176, in main
    runner.node_controller.stop()
  File "/home/karl/raiden/tools/scenario-player/scenario_player/node_support.py", line 450, in stop
    gevent.joinall(stop_tasks, raise_error=True)
  File "src/gevent/greenlet.py", line 849, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 865, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/karl/raiden/tools/scenario-player/scenario_player/node_support.py", line 217, in stop
    ret = self.executor.stop(timeout=timeout)
  File "/home/karl/raiden/tools/scenario-player/scenario_player/node_support.py", line 268, in executor
    self._executor = HTTPExecutor(self._command, f'http://{self.base_url}/api/v1/address')
  File "/home/karl/raiden/tools/scenario-player/scenario_player/node_support.py", line 274, in _command
    self._raiden_bin,
  File "/home/karl/raiden/tools/scenario-player/scenario_player/node_support.py", line 332, in _raiden_bin
    return self._runner.release_keeper.get_release(self._raiden_version)
  File "/home/karl/raiden/tools/scenario-player/scenario_player/node_support.py", line 102, in get_release
    release_file_path = self._get_release_file(release_file_name)
  File "/home/karl/raiden/tools/scenario-player/scenario_player/node_support.py", line 142, in _get_release_file
    with requests.get(url, stream=True) as resp, release_file_path.open('wb') as release_file:
  File "/usr/local/lib/python3.7/pathlib.py", line 1176, in open
    opener=self._opener)
  File "/usr/local/lib/python3.7/pathlib.py", line 1030, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/karl/.raiden/scenario-player/raiden_rTraceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/karl/raiden/tools/scenario-player/scenario_player/__main__.py", line 8, in <module>
    main(prog_name='python -m scenario_player')
  File "/home/karl/tools/venv/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/karl/raiden/tools/scenario-player/scenario_player/main.py", line 176, in main
    runner.node_controller.stop()
  File "/home/karl/raiden/tools/scenario-player/scenario_player/node_support.py", line 450, in stop
    gevent.joinall(stop_tasks, raise_error=True)
  File "src/gevent/greenlet.py", line 849, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 865, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "/home/karl/tools/venv/lib/python3.7/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/karl/raiden/tools/scenario-player/scenario_player/node_support.py", line 217, in stop
    ret = self.executor.stop(timeout=timeout)
  File "/home/karl/raiden/tools/scenario-player/scenario_player/node_support.py", line 268, in executor
    self._executor = HTTPExecutor(self._command, f'http://{self.base_url}/api/v1/address')
  File "/home/karl/raiden/tools/scenario-player/scenario_player/node_support.py", line 274, in _command
    self._raiden_bin,
  File "/home/karl/raiden/tools/scenario-player/scenario_player/node_support.py", line 332, in _raiden_bin
    return self._runner.release_keeper.get_release(self._raiden_version)
  File "/home/karl/raiden/tools/scenario-player/scenario_player/node_support.py", line 102, in get_release
    release_file_path = self._get_release_file(release_file_name)
  File "/home/karl/raiden/tools/scenario-player/scenario_player/node_support.py", line 142, in _get_release_file
    with requests.get(url, stream=True) as resp, release_file_path.open('wb') as release_file:
  File "/usr/local/lib/python3.7/pathlib.py", line 1176, in open
    opener=self._opener)
  File "/usr/local/lib/python3.7/pathlib.py", line 1030, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/karl/.raiden/scenario-player/raiden_releases/downloads/raiden-v/home/pirate/raiden/venv/RaidenClient/bin/raiden-linux.tar.gz'
```                 

I'm running the current master on debian stretch.

**Comment by ulope** [comment] 2019-03-05 10:50
This is being caused by the naming change of the download archives we had recently due to adding arm binaries.

Needs to be fixed in `tools/scenario-players/cenario_player/node_support.py`.

In the meantime @karlb you can also give an absolute path to a raiden executable (e.g. the one in your virtualenv's `bin` directory) in the `raiden_version` key of the scenario. e.g.:
`  raiden_version: /somewhere/venvs/raiden/bin/raiden`

**Closed** 2019-03-08 15:11 UTC
Labels: scenario player
