### ISSUE TITLE
MS1, MS3, MS4, MFEE4 Error Message: Selected Pathfinding Service returned unexpected reply

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5242] opened 2019-11-07 10:28 UTC
## Problem Definition
The node logs for MS1, MS3, MS4, MFEE4 scenarios give us this 

```
There was an error with the Pathfinding Service with address https://pfs-goerli.services-dev.raiden.network. Raiden will shut down. Please try a different Pathfinding Service. 
Error Message: Selected Pathfinding Service returned unexpected reply
```

Due to this error the raiden nodes fail to start
More Analysis and logs will follow. 
[ms1_simple_monitoring.tar.gz](https://github.com/raiden-network/raiden/files/3819076/ms1_simple_monitoring.tar.gz)

[ms3_simple_monitoring.tar.gz](https://github.com/raiden-network/raiden/files/3819145/ms3_simple_monitoring.tar.gz)

[ms4_udc_too_low.tar.gz](https://github.com/raiden-network/raiden/files/3819169/ms4_udc_too_low.tar.gz)

**Comment by Dominik1999** [comment] 2019-11-07 13:12
This was caused by an error in the pfs itself. It did not start last night, see https://github.com/raiden-network/raiden-services/issues/616

Should be fixed

**Closed by Dominik1999** 2019-11-07 13:12 UTC
