### ISSUE TITLE
Matrix Request Error when Raiden is booted

### ISSUE THREAD

**Issue by pkafei** [raiden-network/raiden#2234] opened 2018-08-23 12:27 UTC
## Problem

When I run raiden I get this trace-back error in the terminal. I'm able to initially start raiden and I can choose an account and enter my password. After 2 or 3 minutes though raiden hangs or I get this error message as the output.

```
Traceback (most recent call last):
  File "build/raiden/raiden-script.py", line 2, in <module>
  File "raiden/__main__.py", line 11, in main
  File "click/core.py", line 722, in __call__
  File "click/core.py", line 697, in main
  File "click/core.py", line 1043, in invoke
  File "click/core.py", line 895, in invoke
  File "click/core.py", line 535, in invoke
  File "click/decorators.py", line 17, in new_func
  File "raiden/ui/cli.py", line 1053, in run
  File "raiden/ui/cli.py", line 907, in run
  File "raiden/ui/cli.py", line 925, in _run_app
  File "raiden/ui/cli.py", line 749, in run_app
  File "raiden/app.py", line 135, in start
  File "raiden/raiden_service.py", line 310, in start
  File "raiden/raiden_service.py", line 293, in start_async
  File "raiden/network/transport/matrix.py", line 198, in start
  File "raiden/network/transport/matrix.py", line 361, in _join_discovery_room
  File "matrix_client/client.py", line 320, in join_room
  File "matrix_client/api.py", line 195, in join_room
  File "raiden_libs/network/matrix/client.py", line 72, in _send
  File "matrix_client/api.py", line 691, in _send
matrix_client.errors.MatrixRequestError: 500: {"errcode":"M_UNKNOWN","error":"Internal server error"}
[2660] Failed to execute script raiden-script
```
## Information about my system

``
Darwin Kernel Version 17.7.0: Thu Jun 21 22:59:54 PDT 2018; root:xnu-4570.71.2~2/RELEASE_X86_64 x86_64
alias geth='geth --testnet --fast --rpc --rpcapi eth,net,web3 --bootnodes enode://20c9ad97c081d63397d7b685a412227a40e23c8bdc6688c6f37e97cfbc22d2b4d1db1510d8f61e6a8866ad7f0e17c02b14182d37ea7c3c8b9c2683aeb6b733a1@52.169.14.227:30303,enode://6ce05930c72abc632c58e2e4324f7c7ea478cec0ed4fa2528982cf34483094e9cbc9216e7aa349691242576d552a2a56aaeae426c5303ded677ce455ba1acd9d@13.84.180.240:30303'
Geth
Version: 1.8.13-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.3
Operating System: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.10.3/libexec
/usr/local/bin/parity
Parity
  version Parity/v1.11.8-stable-c754a02-20180725/x86_64-macos/rustc1.27.2
Copyright 2015, 2016, 2017, 2018 Parity Technologies (UK) Ltd
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann

alias raiden='cd /Users/sl_company/raiden_mvp && ./raiden-0.5.0-macOS --keystore-path /Users/sl_company/Library/Ethereum/testnet/keystore'
{
  "raiden": "0.5.0",
  "python_implementation": "CPython",
  "python_version": "3.6.5",
  "system": "macOS 10.13.6 64bit",
  "distribution": "bundled"
}
```

**Comment by palango** [comment] 2018-08-23 13:12
I get the same:
```
± % raiden --eth-rpc-endpoint=http://geth.ropsten.ethnodes.brainbot.com:8545 --keystore-path ~/Library/Ethereum/testnet/keystore --network-id ropsten --log-config 'raiden:debug'
Welcome to Raiden, version 0.4.3.dev144+ga8fc56fb!
----------------------------------------------------------------------
| This is an Alpha version of experimental open source software      |
| released under the MIT license and may contain errors and/or bugs. |
| Use of the software is at your own risk and discretion. No         |
| guarantee whatsoever is made regarding its suitability for your    |
| intended purposes and its compliance with applicable law and       |
| regulations. It is up to the user to determine the software´s      |
| quality and suitability and whether its use is compliant with its  |
| respective regulatory regime, especially in the case that you are  |
| operating in a commercial context.                                 |
----------------------------------------------------------------------
The following accounts were found in your machine:

[  0] - 0x5522070585a1a275631ba69c444ac0451AA9Fe4C

Select one of them by index to continue: 0
Enter the password to unlock 0x5522070585a1a275631ba69c444ac0451AA9Fe4C:
2018-08-23 13:10:07 [debug    ] JSONRPCClient created          [raiden.network.rpc.client] available_nonce=0 sender=55220705
Checking if the ethereum node is synchronized

You are connected to the 'ropsten' network and the DB path is: /Users/paul/.raiden/netid_3/55220705/v0_log.db
2018-08-23 13:10:11 [debug    ] Matrix homeserver RTT times    [raiden.network.transport.matrix] rtt_times=[('https://transport03.raiden.network', 0.027827), ('https://transport02.raiden.network', 0.13908033333333333), ('https://transport01.raiden.network', 0.17600000000000002)]
2018-08-23 13:10:11 [info     ] Automatically selecting matrix homeserver based on RTT [raiden.network.transport.matrix] homeserver=https://transport03.raiden.network rtt=0.027827
2018-08-23 13:10:12 [info     ] Lock 4539092384 acquired on /Users/paul/.raiden/netid_3/55220705/.lock [filelock]
2018-08-23 13:10:12 [debug    ] Restoring from snapshot        [raiden.storage.wal]
2018-08-23 13:10:12 [debug    ] Replaying state changes        [raiden.storage.wal] num_state_changes=178
2018-08-23 13:10:12 [debug    ] Restored state from WAL        [raiden.raiden_service] last_restored_block=3895215
2018-08-23 13:10:13 [debug    ] starting at block number       [raiden.tasks] current_block=3895296
2018-08-23 13:10:14 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=55220705 state_change=<Block 3895296>
2018-08-23 13:10:14 [debug    ] Processing pending transactions [raiden.raiden_service] num_pending_transactions=0
2018-08-23 13:10:14 [info     ] LOGIN                          [raiden.network.transport.matrix] current_user=@0x5522070585a1a275631ba69c444ac0451aa9fe4c:transport03.raiden.network homeserver=transport03.raiden.network server_url=https://transport03.raiden.network username=0x5522070585a1a275631ba69c444ac0451aa9fe4c
2018-08-23 13:10:25 [debug    ] new block                      [raiden.tasks] number=3895297
2018-08-23 13:10:26 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=55220705 state_change=<Block 3895297>
2018-08-23 13:10:27 [debug    ] new block                      [raiden.tasks] number=3895298
2018-08-23 13:10:27 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=55220705 state_change=<Block 3895298>
2018-08-23 13:10:35 [debug    ] new block                      [raiden.tasks] number=3895299
2018-08-23 13:10:35 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=55220705 state_change=<Block 3895299>
2018-08-23 13:10:47 [debug    ] new block                      [raiden.tasks] number=3895300
2018-08-23 13:10:47 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=55220705 state_change=<Block 3895300>
Traceback (most recent call last):
  File "/Users/paul/Work/venv-raiden/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/Users/paul/Work/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/paul/Work/raiden/raiden/ui/cli.py", line 1064, in run
    NodeRunner(kwargs, ctx).run()
  File "/Users/paul/Work/raiden/raiden/ui/cli.py", line 923, in run
    app = self._run_app()
  File "/Users/paul/Work/raiden/raiden/ui/cli.py", line 941, in _run_app
    app_ = run_app(**self._options)
  File "/Users/paul/Work/raiden/raiden/ui/cli.py", line 765, in run_app
    raiden_app.start()
  File "/Users/paul/Work/raiden/raiden/app.py", line 132, in start
    self.raiden.start()
  File "/Users/paul/Work/raiden/raiden/raiden_service.py", line 310, in start
    self.start_async().wait()
  File "/Users/paul/Work/raiden/raiden/raiden_service.py", line 293, in start_async
    self.transport.start(self, queueids_to_queues)
  File "/Users/paul/Work/raiden/raiden/network/transport/matrix.py", line 197, in start
    self._join_discovery_room()
  File "/Users/paul/Work/raiden/raiden/network/transport/matrix.py", line 361, in _join_discovery_room
    discovery_room = self._client.join_room(discovery_room_alias_full)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/matrix_client/client.py", line 320, in join_room
    response = self.api.join_room(room_id_or_alias)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/matrix_client/api.py", line 195, in join_room
    return self._send("POST", path)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/raiden_libs/network/matrix/client.py", line 58, in _send
    return super()._send(*args, **kwargs)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/matrix_client/api.py", line 691, in _send
    code=response.status_code, content=response.text
matrix_client.errors.MatrixRequestError: 500: {"errcode":"M_UNKNOWN","error":"Internal server error"}
```

**Comment by ulope** [comment] 2018-08-23 13:37
@CosminNechifor @palango Please try again. Seems the `transport01` server got stuck somehow (the services were stopped but I couldn't restart the containers). A reboot seems to have fixed the problem.

**Comment by palango** [comment] 2018-08-23 13:38
@ulope Works now for me

**Comment by hackaugusto** [comment] 2018-08-23 15:25
@ulope shouldn' the server selection have handled this?

**Comment by CosminNechifor** [comment] 2018-08-23 15:55
@ulope works

**Comment by CosminNechifor** [comment] 2018-08-23 16:00
@ulope This is a duplicate of: #2231

**Comment by ulope** [comment] 2018-08-23 17:10
@hackaugusto

**Comment by CosminNechifor** [comment] 2018-08-24 12:40
Still happening. And my node is unusable because of this/
```
(raiden) ➜  raiden git:(master) ✗ raiden --keystore-path  ~/.ethereum/testnet/keystore --log-config 'raiden:debug'
Welcome to Raiden, version 0.5.2.dev69+g39936e5b!

....

Enter the password to unlock 0x8A0cE8bDA200D64d858957080bf7eDDD3371135F: 
2018-08-24 12:35:37 [debug    ] JSONRPCClient created          [raiden.network.rpc.client] available_nonce=149 sender=8a0ce8bd
Checking if the ethereum node is synchronized

You are connected to the 'ropsten' network and the DB path is: /home/cosmin/.raiden/netid_3/8a0ce8bd/v130024082018_log.db
2018-08-24 12:35:40 [debug    ] Matrix homeserver RTT times    [raiden.network.transport.matrix] rtt_times=[('https://transport02.raiden.network', 0.13191333333333333), ('https://transport03.raiden.network', 0.13700500000000002), ('https://transport01.raiden.network', 0.15338733333333332)]
2018-08-24 12:35:40 [info     ] Automatically selecting matrix homeserver based on RTT [raiden.network.transport.matrix] homeserver=https://transport02.raiden.network rtt=0.13191333333333333
2018-08-24 12:35:41 [info     ] Lock 139845868847568 acquired on /home/cosmin/.raiden/netid_3/8a0ce8bd/.lock [filelock] 
2018-08-24 12:35:41 [debug    ] Restoring from snapshot        [raiden.storage.wal] 
2018-08-24 12:35:41 [debug    ] Replaying state changes        [raiden.storage.wal] num_state_changes=314
2018-08-24 12:35:42 [debug    ] Restored state from WAL        [raiden.raiden_service] last_restored_block=3900709
2018-08-24 12:35:45 [debug    ] starting at block number       [raiden.tasks] current_block=3900741
2018-08-24 12:35:45 [debug    ] BLOCKCHAIN EVENT               [raiden.blockchain_events_handler] chain_event=<Event contract: 9fe1f19d event: {'args': AttributeDict({'channel_identifier': 109, 'participant1': '0x008135fa6977849ADD47BA058929cA2096725466', 'participant2': '0x82641569b2062B545431cF6D7F0A418582865ba7', 'settle_timeout': 500}), 'event': 'ChannelOpened', 'logIndex': 0, 'transactionIndex': 1, 'transactionHash': HexBytes('0xd000ef37c606c88b4d4a6ff0f2019c9874e3b3c7dd64f544e850ac8f95addf6b'), 'address': '0x9FE1f19D8C0d2591Fd01486E575B44f4220eF241', 'blockHash': HexBytes('0xd905bc52912cf16141a297195368f91646f6c833b80429a595ee7b70c5d23f15'), 'blockNumber': 3900730, 'block_number': 3900730, 'channel_identifier': 109, 'participant1': b'\x00\x815\xfaiw\x84\x9a\xddG\xba\x05\x89)\xca \x96rTf', 'participant2': b'\x82d\x15i\xb2\x06+TT1\xcfm\x7f\nA\x85\x82\x86[\xa7', 'settle_timeout': 500}> node=8a0ce8bd
2018-08-24 12:35:45 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=8a0ce8bd state_change=<ContractReceiveRouteNew token_network:9fe1f19d id:109 node1:008135fa node2:82641569>
2018-08-24 12:35:45 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=8a0ce8bd state_change=<Block 3900741>
2018-08-24 12:35:45 [debug    ] Processing pending transactions [raiden.raiden_service] num_pending_transactions=1
2018-08-24 12:35:45 [info     ] settle called                  [raiden.network.proxies.token_network] locked_amount=0 locksroot=0x0000000000000000000000000000000000000000000000000000000000000000 node=8a0ce8bd partner=92746ece partner_locked_amount=0 partner_locksroot=0x0000000000000000000000000000000000000000000000000000000000000000 partner_transferred_amount=0 token_network=9fe1f19d transferred_amount=0
2018-08-24 12:35:45 [debug    ] send_raw_transaction called    [raiden.network.rpc.client] account=0x8A0cE8bDA200D64d858957080bf7eDDD3371135F gasLimit=3767373 gasPrice=6000000000 nonce=149
2018-08-24 12:35:45 [debug    ] send_raw_transaction returned  [raiden.network.rpc.client] account=0x8A0cE8bDA200D64d858957080bf7eDDD3371135F gasLimit=3767373 gasPrice=6000000000 nonce=149 tx_hash=HexBytes('0xd5f089b08718a692b3242a5b61f312706ce21e6fc992be4831a95dacfcfe6164')
2018-08-24 12:36:26 [info     ] settle failed                  [raiden.network.proxies.token_network] locked_amount=0 locksroot=0x0000000000000000000000000000000000000000000000000000000000000000 node=8a0ce8bd partner=92746ece partner_locked_amount=0 partner_locksroot=0x0000000000000000000000000000000000000000000000000000000000000000 partner_transferred_amount=0 token_network=9fe1f19d transferred_amount=0
2018-08-24 12:36:26 [error    ] Channel cannot be settled before closing [raiden.raiden_event_handler] 
2018-08-24 12:36:27 [debug    ] new block                      [raiden.tasks] number=3900743
2018-08-24 12:36:27 [info     ] missed blocks                  [raiden.tasks] current_block=3900743 missed_blocks=1
2018-08-24 12:36:27 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=8a0ce8bd state_change=<Block 3900743>
2018-08-24 12:36:32 [info     ] LOGIN                          [raiden.network.transport.matrix] current_user=@0x8a0ce8bda200d64d858957080bf7eddd3371135f:transport02.raiden.network homeserver=transport02.raiden.network server_url=https://transport02.raiden.network username=0x8a0ce8bda200d64d858957080bf7eddd3371135f
2018-08-24 12:36:33 [debug    ] new block                      [raiden.tasks] number=3900744
2018-08-24 12:36:33 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=8a0ce8bd state_change=<Block 3900744>
2018-08-24 12:36:35 [debug    ] new block                      [raiden.tasks] number=3900745
2018-08-24 12:36:35 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=8a0ce8bd state_change=<Block 3900745>
2018-08-24 12:36:39 [debug    ] new block                      [raiden.tasks] number=3900746
2018-08-24 12:36:39 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=8a0ce8bd state_change=<Block 3900746>
2018-08-24 12:36:41 [debug    ] new block                      [raiden.tasks] number=3900747
2018-08-24 12:36:41 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=8a0ce8bd state_change=<Block 3900747>
2018-08-24 12:36:43 [warning  ] Got invited to a room by invalid signed user - ignoring [raiden.network.transport.matrix] current_user=@0x8a0ce8bda200d64d858957080bf7eddd3371135f:transport02.raiden.network room_id=!pFNwxLCToFpBxpeafw:transport03.raiden.network user=<User id="@0x008311788dff04e3c0426a3eb19622b2035ba49d:transport03.raiden.network">
2018-08-24 12:36:48 [debug    ] new block                      [raiden.tasks] number=3900748
2018-08-24 12:36:49 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=8a0ce8bd state_change=<Block 3900748>
2018-08-24 12:36:52 [debug    ] new block                      [raiden.tasks] number=3900749
2018-08-24 12:36:52 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=8a0ce8bd state_change=<Block 3900749>
2018-08-24 12:37:08 [debug    ] new block                      [raiden.tasks] number=3900750
2018-08-24 12:37:08 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=8a0ce8bd state_change=<Block 3900750>
Traceback (most recent call last):
  File "/home/cosmin/.virtualenvs/raiden/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 1064, in run
    NodeRunner(kwargs, ctx).run()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 923, in run
    app = self._run_app()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 941, in _run_app
    app_ = run_app(**self._options)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 765, in run_app
    raiden_app.start()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/app.py", line 132, in start
    self.raiden.start()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/raiden_service.py", line 310, in start
    self.start_async().wait()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/raiden_service.py", line 293, in start_async
    self.transport.start(self, queueids_to_queues)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/network/transport/matrix.py", line 197, in start
    self._join_discovery_room()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/network/transport/matrix.py", line 361, in _join_discovery_room
    discovery_room = self._client.join_room(discovery_room_alias_full)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/matrix_client/client.py", line 320, in join_room
    response = self.api.join_room(room_id_or_alias)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/matrix_client/api.py", line 195, in join_room
    return self._send("POST", path)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/raiden_libs/network/matrix/client.py", line 72, in _send
    return super()._send(method, path, *args, **kwargs)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/matrix_client/api.py", line 691, in _send
    code=response.status_code, content=response.text
matrix_client.errors.MatrixRequestError: 500: {"errcode":"M_UNKNOWN","error":"Internal server error"}
```

**Comment by LefterisJP** [comment] 2018-08-25 13:54
So @ulope what needs to be done now for this issue? If I understand correctly it sounds as if it was a matrix server problem.

**Comment by christianbrb** [comment] 2018-10-16 07:32
Needs to be reported upstream

**Comment by andrevmatos** [comment] 2018-10-18 14:52
I don't think it should be a problem anymore since #2485, as after it, the discovery room is effectively owned by all servers in the federation, each one attributing its own alias to it, the same goes for p2p rooms, as they aren't contacted by [canonical] alias anymore, only invite system, even the ones created in debug/dev/test environment, which have these aliases set.

**Comment by ulope** [comment] 2019-01-14 14:21
Needs to be verified if the bug is fixed.

**Comment by ulope** [comment] 2019-07-05 15:48
This most likely has been fixed on the client side. We haven't had any reports of this in the last few months.

**Closed by ulope** 2019-07-05 15:48 UTC
Labels: P2, matrix
