### ISSUE TITLE
Gevent patching

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#1900] opened 2018-07-20 10:21 UTC
## Problem Definition

There are some messages regarding gevent monkey patching. We need to investigate if they are valid and fix them if necessary.

When running `pytest`:
```
Users/paul/Work/venv-raiden/lib/python3.6/site-packages/grequests.py:21: MonkeyPatchWarning: Patching more than once will result in the union of all True parameters being patched
  curious_george.patch_all(thread=False, select=False)
```

In sphinx docs generation:
```
/Users/paul/Work/raiden/raiden/main.py:2: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016
  monkey.patch_all()
```

**Comment by ulope** [comment] 2018-07-20 12:43
The first one is (in our case) harmless, since we use `patch_all()` without any parameters meaning that everything is patched. The question is if we really need grequests at all, since a completely patched gevent should make everything requests does async anyway.

The second one is caused by `patch_all()` being called too late (i.e. after some modules have already been imported). I don't have a good idea right now how to fix that.

**Comment by hackaugusto** [comment] 2018-08-27 12:29
Closing this issue, I believe this is not a problem because we are making sure to monkey patch early

**Closed by hackaugusto** 2018-08-27 12:29 UTC
