### ISSUE TITLE
Travis tests too slow due to duplicated logs

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3012] opened 2018-11-13 10:36 UTC
## Problem Definition

Travis seems to fail very regurarly in our longest build with "log exceeded max size" errors. Example log: https://gist.github.com/LefterisJP/c9c39b56e8dae96d6a24855b328682da

Seems that this started happening since the switch to json logging for debug. And the root cause is probably the fact that the log itself is duplicated.

**Comment by rakanalh** [comment] 2018-11-13 10:59
The logs aren't duplicated... the tests spin up multiple nodes and each node logs almost the same payload to the debug log file which from the initial look might seem like the logs are being duplicated.

Examples:
```
{"node": "c7bf9cc3", "state_change": "{\"block_number\": 17, \"gas_limit\": 9835299, \"block_hash\": \"0x930ee3f6b75a81bc8e5bfa93d8a06fee3c3d85ba4415278ae59e8804c1a3c0d2\", \"_type\": \"raiden.transfer.state_change.Block\", \"_version\": 0}", "event": "State change", "logger": "raiden.raiden_service", "level": "debug", "timestamp": "2018-11-13 10:53:28"}
{"known_block_number": 21, "latest_block_number": 22, "latest_block_hash": "0xad047c3a34dbce7ceea70147b74de57966778fac86785e28e0cf09b49fc977ce", "latest_block_gas_limit": 9787376, "event": "Received new block", "logger": "raiden.tasks", "level": "debug", "timestamp": "2018-11-13 10:53:28"}
{"node": "d6f32c4c", "state_change": "{\"block_number\": 17, \"gas_limit\": 9835299, \"block_hash\": \"0x930ee3f6b75a81bc8e5bfa93d8a06fee3c3d85ba4415278ae59e8804c1a3c0d2\", \"_type\": \"raiden.transfer.state_change.Block\", \"_version\": 0}", "event": "State change", "logger": "raiden.raiden_service", "level": "debug", "timestamp": "2018-11-13 10:53:28"}
{"known_block_number": 22, "latest_block_number": 23, "latest_block_hash": "0x7b5d38d32486a5e62426167cea496cb9d542716d881b038e679176fa7ec7877a", "latest_block_gas_limit": 9777820, "event": "Received new block", "logger": "raiden.tasks", "level": "debug", "timestamp": "2018-11-13 10:53:29"}
```
`node` and `timestamp` are different for this new block state change.

```
{"homeserver": "matrix.local.raiden", "server_url": "http://localhost:8008", "username": "0xc7bf9cc3faad8ea24392f92863c374965282d91f", "event": "Login", "logger": "raiden.network.transport.matrix", "level": "debug", "timestamp": "2018-11-13 10:53:26"}
{"homeserver": "matrix.local.raiden", "server_url": "http://localhost:8008", "username": "0xd6f32c4c261338cca233611ec4a19f642d2de29f", "event": "Login", "logger": "raiden.network.transport.matrix", "level": "debug", "timestamp": "2018-11-13 10:53:26"}
```
`username` is different for the same log message.

```
{"node": "2c78248d", "contract": "504372e7", "to_address": "c7bf9cc3", "amount": 300000000000000000, "event": "transfer successful", "logger": "raiden.network.proxies.token", "level": "info", "timestamp": "2018-11-13 10:53:18"}
{"node": "2c78248d", "contract": "504372e7", "to_address": "d6f32c4c", "amount": 300000000000000000, "event": "transfer called", "logger": "raiden.network.proxies.token", "level": "debug", "timestamp": "2018-11-13 10:53:18"}
```

`to_address` is different.

I think the problem of exceeding the limit is caused by the fact that JSON is a bit more character-hungry.

**Comment by hackaugusto** [comment] 2018-11-13 13:47
@rakanalh This is a good example https://api.travis-ci.org/v3/job/453946335/log.txt . The log's and stderr's outputs contain the same data with different formats in the same order:

`strderr` starts at 2638

```
---------------------------- Captured stderr setup -----------------------------
INFO [11-12|13:18:02.287] Maximum peer count                       ETH=25 LES=0 total=25
2018-11-12 13:18:03 [debug    ] geth command                   [raiden.tests.utils.geth] command=['geth', '--nodekeyhex', 'f68952f08b60b79a5dbd3ec754ee33e6e52101fcf1d8055fc89979c253b14832', '--port', '29950', '--rpcport', '29949', '--bootnodes', 'enode://4fd93e573bf5949fadaf092a1e49341267902e76d886bd02360a550df77672b6d1a1c78c9d31f542d1fc6633d8cc85a0535da432c221560e6e1f32dc8b25b9c9@127.0.0.1:29950', '--unlock', '0', '--password', '/tmp/pytest-of-travis/pytest-0/test_echo_node_response_matrix0/pw', '--nodiscover', '--rpc', '--rpcapi', 'eth,net,web3,personal,txpool', '--rpcaddr', '0.0.0.0', '--networkid', '337', '--verbosity', '1', '--datadir', '/tmp/pytest-of-travis/pytest-0/test_echo_node_response_matrix0/f68952f0', '--mine']
2018-11-12 13:18:09 [debug    ] JSONRPCClient created          [raiden.network.rpc.client] available_nonce=0 client=Geth/v1.8.13-stable-225171a4/linux-amd64/go1.10.3 node=28b89c9b
2018-11-12 13:18:09 [debug    ] Calculated gas price for transaction [raiden.network.rpc.client] calculated_gas_price=18000000000 node=28b89c9b node_gas_price=18000000000
2018-11-12 13:18:09 [debug    ] send_raw_transaction called    [raiden.network.rpc.client] gasLimit=332473 gasPrice=18000000000 node=28b89c9b nonce=0
2018-11-12 13:18:09 [debug    ] send_raw_transaction returned  [raiden.network.rpc.client] gasLimit=332473 gasPrice=18000000000 node=28b89c9b nonce=0 tx_hash=0x27441a863c47dda4683a151f535b27921881de0fa654ea08ef0f77d3020fcc8c
```
Duplicated log output starts at 3094
```
------------------------------ Captured log setup ------------------------------
_base.py                   192 DEBUG    {'command': ['geth', '--nodekeyhex', 'f68952f08b60b79a5dbd3ec754ee33e6e52101fcf1d8055fc89979c253b14832', '--port', '29950', '--rpcport', '29949', '--bootnodes', 'enode://4fd93e573bf5949fadaf092a1e49341267902e76d886bd02360a550df77672b6d1a1c78c9d31f542d1fc6633d8cc85a0535da432c221560e6e1f32dc8b25b9c9@127.0.0.1:29950', '--unlock', '0', '--password', '/tmp/pytest-of-travis/pytest-0/test_echo_node_response_matrix0/pw', '--nodiscover', '--rpc', '--rpcapi', 'eth,net,web3,personal,txpool', '--rpcaddr', '0.0.0.0', '--networkid', '337', '--verbosity', '1', '--datadir', '/tmp/pytest-of-travis/pytest-0/test_echo_node_response_matrix0/f68952f0', '--mine'], 'event': 'geth command', 'logger': 'raiden.tests.utils.geth', 'level': 'debug', 'timestamp': '2018-11-12 13:18:03'}
_base.py                   192 DEBUG    {'node': '28b89c9b', 'available_nonce': 0, 'client': 'Geth/v1.8.13-stable-225171a4/linux-amd64/go1.10.3', 'event': 'JSONRPCClient created', 'logger': 'raiden.network.rpc.client', 'level': 'debug', 'timestamp': '2018-11-12 13:18:09'}
_base.py                   192 DEBUG    {'node': '28b89c9b', 'calculated_gas_price': 18000000000, 'node_gas_price': 18000000000, 'event': 'Calculated gas price for transaction', 'logger': 'raiden.network.rpc.client', 'level': 'debug', 'timestamp': '2018-11-12 13:18:09'}
_base.py                   192 DEBUG    {'node': '28b89c9b', 'nonce': 0, 'gasLimit': 332473, 'gasPrice': 18000000000, 'event': 'send_raw_transaction called', 'logger': 'raiden.network.rpc.client', 'level': 'debug', 'timestamp': '2018-11-12 13:18:09'}
_base.py                   192 DEBUG    {'tx_hash': '0x27441a863c47dda4683a151f535b27921881de0fa654ea08ef0f77d3020fcc8c', 'node': '28b89c9b', 'nonce': 0, 'gasLimit': 332473, 'gasPrice': 18000000000, 'event': 'send_raw_transaction returned', 'logger': 'raiden.network.rpc.client', 'level': 'debug', 'timestamp': '2018-11-12 13:18:09'}
```
`stderr` starts at 3553
```
----------------------------- Captured stderr call -----------------------------
2018-11-12 13:18:54 [info     ] Echo node started              [raiden.utils.echo_node] 
2018-11-12 13:18:54 [debug    ] echo worker                    [raiden.utils.echo_node] qsize=0
2018-11-12 13:18:55 [debug    ] Received new block             [raiden.tasks] known_block_number=51 latest_block_gas_limit=9521214 latest_block_hash=0xe36481cf1e4958138cded2fc97bb8563521a3fbf08ca4512ffbef33c53a283f4 latest_block_number=52
2018-11-12 13:18:55 [debug    ] State change                   [raiden.raiden_service] node=23dcdd88 state_change={"block_number": 47, "gas_limit": 9567834, "block_hash": "0x857b770507cca462c57a4ae3b19ccf3e718994ced0793c7175d6fe44f468e0ce", "_type": "raiden.transfer.state_change.Block", "_version": 0}
2018-11-12 13:18:55 [debug    ] echo_node callback             [raiden.utils.echo_node] block_number=AttributeDict({'difficulty': 2, 'proofOfAuthorityData': HexBytes('0xd88301080d846765746888676f312e31302e33856c696e757800000000000000be11a1a9b1a72ccaef64405c6693af4e437ad5b135c4885943a1ad01e3e2e98c7d84c373ac4352a4991fc0e9c73e9712d4df08532db007901b4b12eb6359723f01'), 'gasLimit': 9521214, 'gasUsed': 0, 'hash': HexBytes('0xe36481cf1e4958138cded2fc97bb8563521a3fbf08ca4512ffbef33c53a283f4'), 'logsBloom': HexBytes('0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'), 'miner': '0x0000000000000000000000000000000000000000', 'mixHash': HexBytes('0x0000000000000000000000000000000000000000000000000000000000000000'), 'nonce': HexBytes('0x0000000000000000'), 'number': 52, 'parentHash': HexBytes('0x9ba5ca66a31271b8fb6edcb11e2ab43401005c098f7a29e3b4dc5f8ff7bbbf45'), 'receiptsRoot': HexBytes('0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421'), 'sha3Uncles': HexBytes('0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347'), 'size': 606, 'stateRoot': HexBytes('0x06b1e2b2e6d747da51b753c56a820ebc2671c82de63881e32412cba15c63cb3f'), 'timestamp': 1542028735, 'totalDifficulty': 105, 'transactions': [], 'transactionsRoot': HexBytes('0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421'), 'uncles': []})
```
Duplicated log output start at 8860
```
------------------------------ Captured log call -------------------------------
_base.py                   192 INFO     {'event': 'Echo node started', 'logger': 'raiden.utils.echo_node', 'level': 'info', 'timestamp': '2018-11-12 13:18:54'}
_base.py                   192 DEBUG    {'qsize': 0, 'event': 'echo worker', 'logger': 'raiden.utils.echo_node', 'level': 'debug', 'timestamp': '2018-11-12 13:18:54'}
_base.py                   192 DEBUG    {'known_block_number': 51, 'latest_block_number': 52, 'latest_block_hash': '0xe36481cf1e4958138cded2fc97bb8563521a3fbf08ca4512ffbef33c53a283f4', 'latest_block_gas_limit': 9521214, 'event': 'Received new block', 'logger': 'raiden.tasks', 'level': 'debug', 'timestamp': '2018-11-12 13:18:55'}
_base.py                   192 DEBUG    {'node': '23dcdd88', 'state_change': '{"block_number": 47, "gas_limit": 9567834, "block_hash": "0x857b770507cca462c57a4ae3b19ccf3e718994ced0793c7175d6fe44f468e0ce", "_type": "raiden.transfer.state_change.Block", "_version": 0}', 'event': 'State change', 'logger': 'raiden.raiden_service', 'level': 'debug', 'timestamp': '2018-11-12 13:18:55'}
_base.py                   192 DEBUG    {'block_number': AttributeDict({'difficulty': 2, 'proofOfAuthorityData': HexBytes('0xd88301080d846765746888676f312e31302e33856c696e757800000000000000be11a1a9b1a72ccaef64405c6693af4e437ad5b135c4885943a1ad01e3e2e98c7d84c373ac4352a4991fc0e9c73e9712d4df08532db007901b4b12eb6359723f01'), 'gasLimit': 9521214, 'gasUsed': 0, 'hash': HexBytes('0xe36481cf1e4958138cded2fc97bb8563521a3fbf08ca4512ffbef33c53a283f4'), 'logsBloom': HexBytes('0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'), 'miner': '0x0000000000000000000000000000000000000000', 'mixHash': HexBytes('0x0000000000000000000000000000000000000000000000000000000000000000'), 'nonce': HexBytes('0x0000000000000000'), 'number': 52, 'parentHash': HexBytes('0x9ba5ca66a31271b8fb6edcb11e2ab43401005c098f7a29e3b4dc5f8ff7bbbf45'), 'receiptsRoot': HexBytes('0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421'), 'sha3Uncles': HexBytes('0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347'), 'size': 606, 'stateRoot': HexBytes('0x06b1e2b2e6d747da51b753c56a820ebc2671c82de63881e32412cba15c63cb3f'), 'timestamp': 1542028735, 'totalDifficulty': 105, 'transactions': [], 'transactionsRoot': HexBytes('0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421'), 'uncles': []}), 'event': 'echo_node callback', 'logger': 'raiden.utils.echo_node', 'level': 'debug', 'timestamp': '2018-11-12 13:18:55'}
```

**Comment by rakanalh** [comment] 2018-11-13 21:31
From the logs provided by Augusto, it seemed like a test "ERROR"ing might lead to this issue. 
1. I tested this scenario, no logs captured.
2. Tried raising an exception from a greenlet, no logs captured
3. Tried raising an exception from the tear down of test, no logs captured

**Comment by hackaugusto** [comment] 2018-11-15 11:22
@rakanalh have you tried raising an exception from a fixture like this?

```python
@pytest.fixture
def f():
  yield
   raise Exception('at teardown')
```

This happens in our fixture setup because we stop the apps in the fixture, and not in the tests, and if a unrecoverable exception is raised there, then we get an ERROR, probably in addition, to a FAILURE.

**Comment by rakanalh** [comment] 2018-11-23 11:05
This was resolved by: https://github.com/raiden-network/raiden/pull/3042.

Example build where failure took place but duplicate logs were not emitted.
https://travis-ci.org/raiden-network/raiden/jobs/457572735

**Closed by rakanalh** 2018-11-23 11:05 UTC
Labels: investigating
