### ISSUE TITLE
Crash with latest master

### ISSUE THREAD

**Issue by offerm** [raiden-network/raiden#3707] opened 2019-03-28 20:43 UTC
When running without services
As of commit:
```
commit ff8b01c81ffe774eadabcf8563d75122b1d3999b (HEAD -> master, raiden-network/master, origin/master, origin/HEAD)
Author: Lefteris Karapetsas <lefteris@refu.co>
Date:   Tue Mar 26 18:08:11 2019 +0100

    Use the service contracts provided via the CLI if they are given
```

after making a payment:
```
 curl -i -X POST http://localhost:5001/api/v1/payments/0x352E04105F25898C9e1dd8Ee5f277208b4df003B/0x133499f529A8D7cF00D8C5f7E73841DDB62b9Ca3 -H 'Content-Type: application/json' --data-raw '{"amount": 54, "identifier": 987654321}'
HTTP/1.1 200 OK
mimetype: application/json
Content-Type: application/json
Content-Length: 398
Date: Thu, 28 Mar 2019 20:39:00 GMT

{"initiator_address": "0x4F6799E2341379eA52213919622B9bEc80a1b655", "secret_hash": "0x43a00d6748e10fb12d7c200a90ea24660c448899a085cb041891e0374a14d95f", "target_address": "0x133499f529A8D7cF00D8C5f7E73841DDB62b9Ca3", "token_address": "0x352E04105F25898C9e1dd8Ee5f277208b4df003B", "amount": 54, "secret": "0x5ad081bcb126c7a8f52097633702d713f79078a38e69203267a1e7a7cc12f12c", "identifier": 987654321}
```

restarting the payee causes a crash:

```
2019-03-28 20:39:53.849999 [info     ] Automatically selecting matrix homeserver based on RTT [raiden.network.transport.matrix.utils] sorted_servers=['https://transport01.raiden.network', 'https://transport03.raiden.network', 'https://transport02.raiden.network']
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/admin/raiden/raiden/__main__.py", line 15, in <module>
    main()
  File "/Users/admin/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/admin/raiden/raiden/ui/cli.py", line 494, in run
    app = runner.run()
  File "/Users/admin/raiden/raiden/ui/runners.py", line 276, in run
    return self._start_services()
  File "/Users/admin/raiden/raiden/ui/runners.py", line 95, in _start_services
    app_ = run_app(**self._options)
  File "/Users/admin/raiden/raiden/ui/app.py", line 513, in run_app
    raiden_app.start()
  File "/Users/admin/raiden/raiden/app.py", line 152, in start
    self.raiden.start()
  File "/Users/admin/raiden/raiden/raiden_service.py", line 526, in start
    self._initialize_monitoring_services_queue(chain_state)
  File "/Users/admin/raiden/raiden/raiden_service.py", line 958, in _initialize_monitoring_services_queue
    update_services_from_balance_proof(self, chain_state, balance_proof)
  File "/Users/admin/raiden/raiden/raiden_service.py", line 219, in update_services_from_balance_proof
    update_path_finding_service_from_balance_proof(raiden, chain_state, new_balance_proof)
  File "/Users/admin/raiden/raiden/raiden_service.py", line 245, in update_path_finding_service_from_balance_proof
    raiden.transport.send_global(constants.PATH_FINDING_BROADCASTING_ROOM, msg)
  File "/Users/admin/raiden/raiden/network/transport/matrix/transport.py", line 554, in send_global
    room_name = make_room_alias(self.network_id, room)
  File "/Users/admin/raiden/raiden/utils/runnable.py", line 80, in __getattribute__
    return super().__getattribute__(name)
  File "/Users/admin/raiden/raiden/network/transport/matrix/transport.py", line 606, in network_id
    assert self._raiden_service is not None
AssertionError
--- Logging error ---
```

the `start` method is doing (raiden_services.py:526)
>      self._initialize_monitoring_services_queue(chain_state)

which leads to asset error in "/Users/admin/raiden/raiden/network/transport/matrix/transport.py", line 606

**Comment by rakanalh** [comment] 2019-03-29 08:26
Duplicate of https://github.com/raiden-network/raiden/issues/3656

**Comment by LefterisJP** [comment] 2019-03-29 08:27
@offerm Even though what I did in PR #3709 solves the problem for you, it does not solve the underling problem which is described in #3656. A proper solution for that will come asap. In the meantime you can use the code of #3709 to at least go ahead with your work.

**Comment by rakanalh** [comment] 2019-03-29 18:09
Should be resolved by https://github.com/raiden-network/raiden/pull/3702

**Closed by rakanalh** 2019-03-29 18:09 UTC
