### ISSUE TITLE
pfs4_use_best_path fail Error in fee calculations

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5008] opened 2019-10-01 07:59 UTC
Description
=========
Seems like an error in fee calculations 

`
 f'Value mismatch for \"{field}\". '\nscenario_player.exceptions.legacy.ScenarioAssertionError: Value mismatch for \"balance\". Should: \"999000000000000000\" Is: \"1000000000000000000\" Channel: {'partner_address': '0xFA69302C97320a37b2317F95091dC101327299F0', 'channel_identifier': 547, 'reveal_timeout': 50, 'token_address': '0x62083c80353Df771426D209eF578619EE68D5C7A', 'token_network_address': '0x9526EC0E58ac5Bb1e24d655E964f0eAA46054d16', 'balance': 1000000000000000000, 'settle_timeout': 500, 'total_deposit': 1000000000000000000, 'total_withdraw': 0, 'state': 'opened'}`

```
{"task": "<AssertTask: {'from': 0, 'to': 4, 'total_deposit': 1000000000000000000, 'balance': 999000000000000000}>", "event": "Task errored", "logger": "scenario_player.tasks.base", "level": "error", "timestamp": "2019-10-01 02:21:52.447706", "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 74, in __call__\n    return self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 70, in _run\n    return self._process_response(response_dict)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/channels.py\", line 155, in _process_response\n    f'Value mismatch for \"{field}\". '\nscenario_player.exceptions.legacy.ScenarioAssertionError: Value mismatch for \"balance\". Should: \"999000000000000000\" Is: \"1000000000000000000\" Channel: {'partner_address': '0xFA69302C97320a37b2317F95091dC101327299F0', 'channel_identifier': 547, 'reveal_timeout': 50, 'token_address': '0x62083c80353Df771426D209eF578619EE68D5C7A', 'token_network_address': '0x9526EC0E58ac5Bb1e24d655E964f0eAA46054d16', 'balance': 1000000000000000000, 'settle_timeout': 500, 'total_deposit': 1000000000000000000, 'total_withdraw': 0, 'state': 'opened'}"}
```

[Scenario_player_Logs-pfs4_use_best_path-1-latest-2019-10-01.tar.gz](https://github.com/raiden-network/scenario-player/files/3675268/Scenario_player_Logs-pfs4_use_best_path-1-latest-2019-10-01.tar.gz)

Expected Behavior
===============
SP should be able to assert on the fees in the task correctly

**Comment by Dominik1999** [comment] 2019-10-01 09:59
@agatsoh the logs of the nodes are empty. Can you please provide the correct logs and check every time if everything is there?

**Comment by Dominik1999** [comment] 2019-10-01 11:59
ok so locally, it seems to run into a race condition. 

- for the pfs the shorter path over node 4 does not have enough capacity
- this might be caused by the reason that the capacity update of node 4 is sent to the pfs only shortly before the path is requested
- this happened in my local run when node 4 was last in channel opening and depositing

I added a `wait_blocks: 2` before the transfer and now it succeeded 2 times in a row.

I will close this issue until it happens again

**Closed** 2019-10-01 12:13 UTC

**Comment by christianbrb** [comment] 2019-10-23 14:44
Related and going to be fixed by https://github.com/raiden-network/raiden/issues/5078
