### ISSUE TITLE
Sending insufficient fund payment via WebUI returns success

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3600] opened 2019-03-07 23:58 UTC
## Problem Definition

While using the WebUI in the EthCC demo, we tried to send an impossible payment (one for which we would not have sufficient funds). Instead of getting an insufficient funds errors, a green popup saying that payment succeeded appeared.

## Task

Investigate where the problem lies and fix it.

**Comment by kelsos** [comment] 2019-03-08 06:16
@LefterisJP I encountered the same situation yesterday with the last tested RC.

I tried to send to my offline nodes and the rest API responded with 200. On the logs I could see that the partner was unreachable.

**Comment by rakanalh** [comment] 2019-03-13 15:45
@kelsos are you sure it was returning 200? in my PR above #3623, i have written a test that checks whether there's a proper response and there is. The client returns 409 when you try to send a payment larger than balance. How do i proceed from here?

**Comment by kelsos** [comment] 2019-03-13 15:49
@rakanalh In my case, I sent to an offline node. I am pretty confident there was a 200 response in the logs, which was really weird because in the logs there where the expected messages (partner unreachable etc). I was using the last rc version before `pluto` when this happened to me.

**Comment by rakanalh** [comment] 2019-03-13 15:59
Added one more test case and it does not reproduce the issue. Could you please try to re-produce it if you have the time?

**Comment by kelsos** [comment] 2019-03-13 16:05
So I did try this and the following happened.
```
2019-03-13 16:02:57.245829 [debug    ] Initiating payment             [raiden.api.rest] amount=1 node=0e809a05 payment_identifier=1552492977849 registry_address=0x40bC6AA6514D8b6a3E169e62816385721A594E92 target_address=0x82641569b2062B545431cF6D7F0A418582865ba7 token_address=0xd0A1E359811322d97991E03f863a0C30C2cF029C
2019-03-13 16:02:57.246689 [debug    ] Initiating transfer            [raiden.api.python] amount=1 identifier=1552492977849 initiator=0e809a05 target=82641569 token=d0a1e359
2019-03-13 16:02:57.276869 [info     ] Partner for channel isn't reachable, ignoring [raiden.routing] from_address=0e809a05 partner_address=82641569 routing_source=Internal Routing status=unreachable
2019-03-13 16:02:57.277697 [warning  ] No routes available            [raiden.routing] from_address=0e809a05 to_address=82641569
2019-03-13 16:02:57.278996 [debug    ] State change                   [raiden.raiden_service] node=0e809a05 state_change={"transfer": {"payment_network_identifier": "0x40bC6AA6514D8b6a3E169e62816385721A594E92", "payment_identifier": "1552492977849", "amount": "1", "token_network_identifier": "0x111157460c0F41EfD9107239B7864c062aA8B978", "initiator": "0x0E809A051034723beE67871a5A4968aE22d36C5A", "target": "0x82641569b2062B545431cF6D7F0A418582865ba7", "secret": "0x1b86232f04dc6fd9c712fde2c2e6ea1aef4245990201f2020e1fda584cfcd40d", "_type": "raiden.transfer.mediated_transfer.state.TransferDescriptionWithSecretState", "_version": 0}, "routes": [], "_type": "raiden.transfer.mediated_transfer.state_change.ActionInitInitiator", "_version": 0}
2019-03-13 16:02:57.294942 [debug    ] Raiden event                   [raiden.raiden_service] node=0e809a05 raiden_event={"payment_network_identifier": "0x40bC6AA6514D8b6a3E169e62816385721A594E92", "token_network_identifier": "0x111157460c0F41EfD9107239B7864c062aA8B978", "identifier": "1552492977849", "target": "0x82641569b2062B545431cF6D7F0A418582865ba7", "reason": "there is no route available", "_type": "raiden.transfer.events.EventPaymentSentFailed", "_version": 0}
2019-03-13 16:02:57.306564 [info     ] 127.0.0.1 - - [2019-03-13 17:02:57] "POST /api/v1/payments/0xd0A1E359811322d97991E03f863a0C30C2cF029C/0x82641569b2062B545431cF6D7F0A418582865ba7 HTTP/1.1" 200 538 0.062836 [raiden.api.rest.pywsgi] 

```

**Comment by marcosmartinez7** [comment] 2019-03-15 18:54
Happened to me too.

The situation was when doing a mediated payment. 

A -> B -> C 

The A->B payment mediated payment works, then the B->C payment failed. 

The logs were exactly the same as @kelsos last comment.

**Comment by konradkonrad** [comment] 2019-03-27 11:25
I tried to reproduce with yet another variation of integration tests, but I could not. Waiting for @kelsos for a manual reproduction based on `master`.

**Comment by kelsos** [comment] 2019-04-01 14:20
I attempted to run the simplest scenario of sending to a channel with an offline node. 
The latest master behaves as it was before the issue appeared. There is no 200 response at least until the client timeout's the request. Usually, the 200 would return quite fast.

I am closing the issue since this doesn't seem to be valid anymore.

**Closed by kelsos** 2019-04-01 14:20 UTC
Labels: API, investigating, medium severity bug

**Comment by LefterisJP** [comment] 2019-04-01 14:21
Now I am curious how the hell we fixed this ...
