### ISSUE TITLE
Cannot start the node after issue 3135

### ISSUE THREAD

**Issue by arsenyjin** [raiden-network/raiden#3139] opened 2018-12-08 14:04 UTC
The node crashed with the deposit error seen in https://github.com/raiden-network/raiden/issues/3135. Then once restarted it crashed again with a different error  and was not able to reconnect to the network, network works without issues, new nodes also able to connect 

Here is the error message:

https://gist.github.com/arsenyjin/f29e4f31a1b1823d4b763f3a1e77f142

**Comment by arsenyjin** [comment] 2018-12-08 14:11
[node_747b50e3.zip](https://github.com/raiden-network/raiden/files/2659734/node_747b50e3.zip)

Here are all the logs and the database file

**Comment by LefterisJP** [comment] 2018-12-08 14:39
@arsenyjin For #3135 the error was so far seen only in a new token network and the first channel of that token network. Was that the case with your first crash here too? Or did you get the deposit error at some other point?

**Comment by czepluch** [comment] 2018-12-08 14:41
@LefterisJP Just added a comment about this in #3135 . In this case it happened over and over again. A couple of deposits were successful, but many failed. I didn't manage to understand the pattern for when it fails and when it doesn't yet.

**Comment by rakanalh** [comment] 2018-12-11 16:18
After investigating the logs and the provided database, i realized that the node did not experience the issue reported in this gist:
https://gist.github.com/czepluch/612bf068847046c1230fcb2e32abcbb9

There were instances where `EventPaymentSentFailed` event was emitted but it did not crash the node judging by looking at the logs.

However, regarding the main problem in this report. I have come to the conclusion that the crash was caused by a `RaidenUnrecoverableError`. This is because as apparent, the node crashed and was offline. Before the crash happened, `channel_identifier:4` with `partner:81eaf015` was closed by the current node `node:747b50e3` and then missed the settlement timeout. 

According to this:
https://github.com/raiden-network/raiden/blob/master/raiden/raiden_event_handler.py#L331-L338

At the time of processing the `ReceiveContractChannelSettled` state change, the state machine reacts by trying to unlock the balance. But since it was offline at the time, the partner of the channel was able to perform the unlock. Unlocking in this case would mean that the locked amounts will be transferred back to the channel's participants and will be removed afterwards. 
This means that the above will be `False` for both conditions and therefore, triggering the error.

**Comment by rakanalh** [comment] 2018-12-11 16:30
Since the node restarted, it tried to send the transaction `ContractSendChannelBatchUnlock` but this error happened. I think the problem lies with the `pending_transaction` implementation is that it's not forward looking. Pending transactions are invalidated based on channels which have happened until the node crashed.

https://github.com/raiden-network/raiden/blob/master/raiden/raiden_service.py#L366-L387

However, according to the code above... what we should be doing is processing the transactions knowing which events exist in the "future" blocks because at some point in time, and in the case of this bug, `ChannelUnlocked` event from the contracts might be somewhere within the missed blocks that we have not looked at yet, but we are prevented from doing so until the pending transaction we have is processed. The point is, it could have been invalidated by the looking at the list of events that lie in the blocks list that we haven't yet examined.

**Comment by rakanalh** [comment] 2018-12-12 08:50
What you said makes sense. I was looking at:
https://github.com/raiden-network/raiden-contracts/blob/ce4c328157eae5b8bc61202e00796301b44f318b/raiden_contracts/contracts/TokenNetwork.sol#L836-L837

and judging that the lock data have been cleared. Because when inspecting the provided database, the last set of state changes / events that took place in that channel were:
```
State change:
<ContractReceiveChannelSettled token_network:7d371630 channel:4 settle_block:9625701>
Resulting event:
<ContractSendChannelBatchUnlock token_address: f5b9359c token_network_id:7d371630 channel:4 participant:81eaf015>
```
where the locksroot at that point is `47915945` (pex'ed)

Looking for the last state_change in that same database for the locksroot shows that we have a state change:
```
state_change_identifier=2055, data=<ReceiveUnlock msgid:12842682061281522173 secrethash:18db002d balance_proof:<BalanceProofSignedState nonce:5 transferred_amount:2000000000000000000 locked_amount:10000000000000000000 locksroot:47915945 token_network:7d371630 channel_identifier:4 message_hash:c88b234d signature:3d0e1c82 sender:81eaf015 chain_id:42>
```

Note: Just noticed that the strange thing here is that the state change is `ReceiveUnlock`.

So given that none of the conditions matched in the last code block:
https://github.com/raiden-network/raiden/blob/8bb02c11dd863930a1f5dfbed0e417eec784d925/raiden/raiden_event_handler.py#L331-L338

Means that the unlock data in the contracts contained `0x0` values for the locksroot and therefore we did not even attempt to restore the `ReceiveUnlock` state change.

**Comment by LefterisJP** [comment] 2018-12-12 13:07
> Note: Just noticed that the strange thing here is that the state change is ReceiveUnlock.

Why strange? That makes sense. This is the completion of a transfer. `ReceiveUnlock` means we got the Unlock message from the partner which completes the transfer and has the final locksroot in it.

> and therefore we did not even attempt to restore the ReceiveUnlock state change.

??

> Means that the unlock data in the contracts contained 0x0 values for the locksroot

If that is indeed the case the only way I can imagine this can happen is:

1. The attack I described in #3114 
2. The following scenario:
    i. The node actually [sent](https://github.com/raiden-network/raiden/blob/e167d2ee265c8f7e164f9ff001e756b72de01015/raiden/network/proxies/token_network.py#L877) the onchain unlock successfully but was restarted right afterwards.
    ii. When it restarts the `SendChannelBatchUnlock()` will be in its `pending_transactions` and it will [try](https://github.com/raiden-network/raiden/blob/e167d2ee265c8f7e164f9ff001e756b72de01015/raiden/raiden_service.py#L585) to reapply it.
    iii. Since the [participant_details](https://github.com/raiden-network/raiden/blob/8bb02c11dd863930a1f5dfbed0e417eec784d925/raiden/raiden_event_handler.py#L319) call uses the latest block and not the one for which the state change was generated the locksroot will be `0x0` since the original onchain unlock succeeded.
    iv. With a `0x0` locksroot we end up as @rakanalh described in the `UnrecoverableError`.

**Comment by rakanalh** [comment] 2018-12-12 13:38
> > and therefore we did not even attempt to restore the ReceiveUnlock state change.
> 
> ??

What i meant was this:
https://github.com/raiden-network/raiden/blob/d05bb74d70fa196bf14bf334546014e7316fb8f2/raiden/raiden_event_handler.py#L341-L349

**Comment by rakanalh** [comment] 2018-12-12 22:30
Alright, i have figured out the issue here.

The failing node was mediating a transfer which expired during the time it was offline.

```
(Pdb++) task.mediator_state.transfers_pair[0]
<MediationPairState payee:<LockedTransferSignedState msgid:9776033918122327677 id:1544249795971 token:0xf5b9359cc8e83b24e0436e78e6006608b53b5f46 lock:<HashTimeLockState amount:10000000000000000000 expiration:9624073 secrethash:d57d4752> target:0x451f566bbe5eb60545c336ac659aab371f3818b1> 81eaf015 payer:<LockedTransferUnsignedState id:1544249795971 token:0xf5b9359cc8e83b24e0436e78e6006608b53b5f46 balance_proof:<BalanceProofUnsignedState nonce:5 transferred_amount:30220000000000000000 locked_amount:10000000000000000000 locksroot:47915945 token_network:7d371630 channel_identifier:4 chain_id:42> lock:<HashTimeLockState amount:10000000000000000000 expiration:9624073 secrethash:d57d4752> target:0x451f566bbe5eb60545c336ac659aab371f3818b1>>
(Pdb++) task.mediator_state.transfers_pair[0].payer_state
'payer_expired'
(Pdb++) task.mediator_state.transfers_pair[0].payee_state
'payee_expired'
```
While the lock in the `payer_channel` was never removed because we did not receive `LockExpired` message due to the node being offline.
```
(Pdb++) channel_state.partner_state.secrethashes_to_lockedlocks
{b'\xd5}GR\xd7\xe0\xc4R\xd1\x82\x93xX\x0e\xdc\xfd\x88gt\x1bSqHc\xc7Y~P\xd9\x15\xb8\xb2': <HashTimeLockState amount:10000000000000000000 expiration:9624073 secrethash:d57d4752>}
```
where `channel_state` is the payer_channel of the mediated transfer.

This resulted in the fact that when `get_batch_unlock` is called during the handling of `ContractReceiveChannelSettled` here:
https://github.com/raiden-network/raiden/blob/6b913826fcc5da01fc5b2d6c73cdf1c89fb1b0fd/raiden/transfer/channel.py#L1744
The returned merkle tree leaves will contain the expired lock and therefore triggering the `ContractSendChannelBatchUnlock` which should NOT happen because there are no actual *pending* locks to be unlocked.
https://github.com/raiden-network/raiden/blob/6b913826fcc5da01fc5b2d6c73cdf1c89fb1b0fd/raiden/transfer/channel.py#L847-L863

So the failure in the event handler is a valid one. The state machine failed in figuring out whether it should send the batch unlock call or not.

**Comment by rakanalh** [comment] 2018-12-13 12:56
So discussing with @LefterisJP and @konradkonrad, we decided that this issue is not something the client needs to act upon because it breaks the rule of having to be online during reveal timeout. 

Given that this issue took place because there was a pending lock which was expired by the transfer's initiator but the mediator was offline and never received the lock expiry message, the state *should be* kept and the lock shouldn't be removed because at the time of the settle we can't tell if the lock expired during the life-time of the channel or sometime during the settle timeout. In addition, the state should be kept because in the presence of the monitoring service, the MS will call `updateNonClosingBalanceProof` in the token network smart contract on our behalf (in case our node was offline) which means that we should have the same data that the MS used to call that method in the SC.

That being said, @LefterisJP's PR (https://github.com/raiden-network/raiden/pull/3154) prevents the client from crashing when this case takes place which we think is enough for the time being.

**Closed by rakanalh** 2018-12-13 12:56 UTC
Labels: investigating
