### ISSUE TITLE
Node crashed when Unhandled exception occurs maybe caused by Insufficient funds

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#2924] opened 2018-10-30 08:50 UTC
## Intro

Tried to deposit to a channel and node crashed. Tried it after restart again and node crashed again

--

## Problem Definition

The Ethereum account had ~2$ for gas costs. I could repeat this crashing several times.

```
2018-10-29 13:43:17 [debug    ] Depositing to channel          [raiden.api.rest] channel_identifier=57 node=2a7d58e6 registry_address=0xB9633dd9a9a71F22C933bF121d7a22008f66B908 total_deposit=1000000000000000
2018-10-29 13:43:18 [debug    ] setTotalDeposit called         [raiden.network.proxies.token_network] channel_identifier=57 new_total_deposit=1000000000000000 node=2a7d58e6 partner=f0daca3b previous_total_deposit=0 token_network=a5c9ecf5
2018-10-29 13:43:18 [debug    ] approve called                 [raiden.network.proxies.token] allowance=1000000000000000 allowed_address=a5c9ecf5 contract=c02aaa39 node=2a7d58e6
2018-10-29 13:43:19 [debug    ] Getting channel list           [raiden.api.rest] node=2a7d58e6 partner_address=None registry_address=0xB9633dd9a9a71F22C933bF121d7a22008f66B908 token_address=None
2018-10-29 13:43:19 [info     ] 127.0.0.1 - - [2018-10-29 14:43:19] "GET /api/1/channels HTTP/1.1" 200 465 0.002551 [raiden.api.rest.pywsgi] 
2018-10-29 13:43:20 [debug    ] Calculated gas price for transaction [raiden.network.rpc.client] calculated_gas_price=6471317016 node=2a7d58e6 node_gas_price=8000000000
2018-10-29 13:43:20 [debug    ] send_raw_transaction called    [raiden.network.rpc.client] gasLimit=6400023 gasPrice=6471317016 node=2a7d58e6 nonce=1
2018-10-29 13:43:20 [critical ] Unhandled exception when processing endpoint request [raiden.api.rest] node=2a7d58e6
Traceback (most recent call last):
  File "site-packages/raiden/network/rpc/smartcontract_proxy.py", line 77, in transact
  File "site-packages/raiden/network/rpc/client.py", line 414, in send_transaction
  File "site-packages/web3/eth.py", line 274, in sendRawTransaction
  File "site-packages/web3/manager.py", line 112, in request_blocking
ValueError: {'code': -32010, 'message': 'Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 41416577742691368 and got: 9219772000000000.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/flask/app.py", line 1813, in full_dispatch_request
  File "site-packages/flask/app.py", line 1799, in dispatch_request
  File "site-packages/flask_restful/__init__.py", line 480, in wrapper
  File "site-packages/flask/views.py", line 88, in view
  File "site-packages/flask_restful/__init__.py", line 595, in dispatch_request
  File "site-packages/webargs/core.py", line 478, in wrapper
  File "site-packages/raiden/api/v1/resources.py", line 76, in patch
  File "site-packages/raiden/api/rest.py", line 1166, in patch_channel
  File "site-packages/raiden/api/rest.py", line 1043, in _deposit
  File "site-packages/raiden/api/python.py", line 416, in set_total_channel_deposit
  File "site-packages/raiden/network/proxies/payment_channel.py", line 164, in set_total_deposit
  File "site-packages/raiden/network/proxies/token_network.py", line 590, in set_total_deposit
  File "site-packages/raiden/network/proxies/token.py", line 64, in approve
  File "site-packages/raiden/network/rpc/smartcontract_proxy.py", line 85, in transact
raiden.exceptions.ReplacementTransactionUnderpriced: Transaction was rejected. This is potentially caused by the reuse of the previous transaction nonce as well as paying an amount of gas less than or equal to the previous transaction's gas amount
2018-10-29 13:43:20 [debug    ] REST API stopped               [raiden.api.rest] node=2a7d58e6
2018-10-29 13:43:20 [info     ] 127.0.0.1 - - [2018-10-29 14:43:20] "PATCH /api/1/channels/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/0xf0DAca3B7Cb562059D89bD5d8291a482b20f9D52 HTTP/1.1" 500 432 3.413908 [raiden.api.rest.pywsgi] 
2018-10-29 13:43:20 [debug    ] REST API stopped               [raiden.api.rest] node=2a7d58e6
```

[here](https://gist.github.com/Dominik1999/90069420cdd261036617b3c7efe82b8a) are more logs 

### Issue checklist
Read through [Requirements for safe usage](https://raiden-network.readthedocs.io/en/stable/overview_and_guide.html#requirements-for-safe-usage) mentioned in our documentation and make sure your usage follows the requirements.

1. Is your Ethereum node syncing and up to date with the blockchain?
2. Are you using the same Ethereum account with anything other than the Raiden node? Or are you running multiple Raiden nodes with the same Ethereum account?
3. Does your Ethereum account used by Raiden have sufficient ETH?
4. Did you alter or delete the local DB that exists by default at ~/.raiden?
4. Did you stop / restart your raiden node while having open channels and/or pending transfers? if so, please provide further information.
5. Did you stop / restart your Ethereum node while Raiden was running?
6. Did you switch from one Ethereum node to another? example: switching from a local Ethereum node to an Infura one.
7. Is Raiden REST API protected from public access?

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
Linux dominik-ThinkPad-T450s 4.19.0-041900-generic #201810221809 SMP Mon Oct 22 22:11:45 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.25+commit.59dbf8f1.Linux.g++

Geth (I use the brainbot node via VPN Access)

raiden-v0.15.1.dev6+g14cba904-linux
```

**Comment by LefterisJP** [comment] 2018-10-30 08:59
The crash tells you what went wrong:

`ValueError: {'code': -32010, 'message': 'Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 41416577742691368 and got: 9219772000000000.'}`

you did not have enough funds in the ethereum account.

**Comment by LefterisJP** [comment] 2018-10-30 09:48
I will close this as duplicate of #2923 as dominik already replied there.

**Closed by LefterisJP** 2018-10-30 09:48 UTC
