### ISSUE TITLE
token network list is empty!!!

### ISSUE THREAD

**Issue by zhouzhou84** [raiden-network/raiden#2054] opened 2018-08-03 01:55 UTC
## Problem Definition

after installation, I use the command `geth --testnet --datadir=/home/ubuntu/data/eth_ropsten --rpc --rpcapi eth,net,web3`   and `raiden --keystore-path  ~/data/eth_ropsten/keystore` to start. it's alright.

Then I use `curl -i http://localhost:5001/api/1/address` to check if the address it return is same as the account I log in. it's same. ok, then I type `curl -i http://localhost:5001/api/1/tokens` , it return a empty list, no token network there. But other use this command, it returns a list filled with 7 addresses ! THE EMPTY LIST IS MY BIG PROBLEM!!

I want to have a try to register a token network, and I deploy a token named"WWC", and register it , some friends in the raiden gitter group see my address when them type the command`curl -i http://localhost:5001/api/1/tokens`. In short, some command is ok,but some is invaild!

Is there something wrong with my net and how to solve this problem, I am in despair...
 
 ### raiden-debug.log
``` 2018-08-03 01:17:04 [debug    ] Matrix homeserver RTT times    [raiden.network.transport.matrix] rtt_times=[('https://transport03.raiden.network', 0.18367566666666665), ('https://transport01.raiden.network', 0.18506), ('https://transport02.raiden.network', 0.24544166666666667)]
2018-08-03 01:17:04 [info     ] Automatically selecting matrix homeserver based on RTT [raiden.network.transport.matrix] homeserver=https://transport03.raiden.network rtt=0.18367566666666665
2018-08-03 01:17:05 [info     ] Lock 139705051158232 acquired on /home/ubuntu/.raiden/netid_3/3c465708/.lock [filelock]
2018-08-03 01:17:07 [debug    ] starting at block number       [raiden.tasks] current_block=3761861
2018-08-03 01:17:07 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3761861>
2018-08-03 01:17:08 [info     ] LOGIN                          [raiden.network.transport.matrix] current_user=@0x3c46570896f3ec1323280df466716d1076a7162b:transport03.raiden.network homeserver=transport03.raiden.network server_url=https://transport03.raiden.network username=0x3c46570896f3ec1323280df466716d1076a7162b
2018-08-03 01:17:09 [info     ] TRANSPORT STARTED              [raiden.network.transport.matrix] current_user=@0x3c46570896f3ec1323280df466716d1076a7162b:transport03.raiden.network
2018-08-03 01:17:19 [debug    ] new block                      [raiden.tasks] number=3761862
2018-08-03 01:17:19 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3761862>
2018-08-03 01:17:24 [debug    ] new block                      [raiden.tasks] number=3761863
2018-08-03 01:17:24 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3761863>
2018-08-03 01:17:40 [info     ] 127.0.0.1 - - [2018-08-03 01:17:40] "GET /api/1/address HTTP/1.1" 200 197 0.001419 [raiden.api.rest.pywsgi]
2018-08-03 01:17:42 [debug    ] new block                      [raiden.tasks] number=3761864
2018-08-03 01:17:42 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3761864>
2018-08-03 01:17:52 [info     ] 127.0.0.1 - - [2018-08-03 01:17:52] "GET /api/1/tokens HTTP/1.1" 200 137 0.002111 [raiden.api.rest.pywsgi]
2018-08-03 01:18:04 [debug    ] new block                      [raiden.tasks] number=3761865
2018-08-03 01:18:04 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3761865>
2018-08-03 01:18:22 [debug    ] new block                      [raiden.tasks] number=3761866
2018-08-03 01:18:22 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3761866>
2018-08-03 01:18:28 [debug    ] new block                      [raiden.tasks] number=3761867
2018-08-03 01:18:28 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3761867>
2018-08-03 01:18:32 [debug    ] new block                      [raiden.tasks] number=3761868
2018-08-03 01:18:32 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3761868>
2018-08-03 01:18:35 [debug    ] new block                      [raiden.tasks] number=3761869
2018-08-03 01:18:35 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3761869>
2018-08-03 01:18:52 [debug    ] new block                      [raiden.tasks] number=3761870
2018-08-03 01:18:52 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3761870>
2018-08-03 01:19:00 [debug    ] new block                      [raiden.tasks] number=3761871
2018-08-03 01:19:00 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3761871>
2018-08-03 01:19:24 [debug    ] new block                      [raiden.tasks] number=3761872
2018-08-03 01:19:24 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3761872>
2018-08-03 01:19:33 [debug    ] new block                      [raiden.tasks] number=3761873
2018-08-03 01:19:33 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3761873>
2018-08-03 01:19:41 [debug    ] new block                      [raiden.tasks] number=3761874
2018-08-03 01:19:41 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3761874>
2018-08-03 01:20:01 [debug    ] new block                      [raiden.tasks] number=3761875
2018-08-03 01:20:01 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3761875>
2018-08-03 01:20:04 [debug    ] new block                      [raiden.tasks] number=3761876
```

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
ubuntu@ip-172-31-15-69:~/nodejs/bin$ uname -a
Linux ip-172-31-15-69 4.4.0-1061-aws #70-Ubuntu SMP Fri May 25 21:47:34 UTC 2018                                                                                      x86_64 x86_64 x86_64 GNU/Linux
ubuntu@ip-172-31-15-69:~/nodejs/bin$ command -v solc && solc --version
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Linux.g++
ubuntu@ip-172-31-15-69:~/nodejs/bin$ command -v geth && geth version
/home/ubuntu/go-ethereum/build/bin/geth
Geth
Version: 1.8.13-unstable
Git Commit: 1064b9e69189efd65c5de9149f37614cde9b5944
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.3
Operating System: linux
GOPATH=/home/ubuntu/gocode
GOROOT=/usr/local/go
ubuntu@ip-172-31-15-69:~/nodejs/bin$ command -v parity && parity --version
ubuntu@ip-172-31-15-69:~/nodejs/bin$ command -v raiden && raiden version
/usr/bin/raiden
{
  "raiden": "0.4.2",
  "python_implementation": "CPython",
  "python_version": "3.6.6",
  "system": "Linux 64bit_ELF 4.4.0-1061-aws x86_64",
  "distribution": "bundled"
}
ubuntu@ip-172-31-15-69:~/nodejs/bin$ [ -d .git ] && git rev-parse HEAD
ubuntu@ip-172-31-15-69:~/nodejs/bin$

```

**Comment by andrevmatos** [comment] 2018-08-03 14:14
@zhouzhou84 that's very weird. The Raiden node "knows" about token networks through events fetched from your eth node. Maybe your ETH node wasn't yet synced at the time you started Raiden?
Would you mind, please, backuping and moving your `~/.raiden` and then restarting Raiden after being sure your `geth` is in sync, and post here if the result is different?

**Comment by zhouzhou84** [comment] 2018-08-03 14:31
Here it is midnight...I will try it, but I am sure that the ropsten is synced On 2018-08-03 22:25 , André Vitor de Lima Matos Wrote: @zhouzhou84 that's very weird. The Raiden node "knows" about token networks through events fetched from your eth node. Maybe your ETH node wasn't yet synced at the time you started Raiden? Would you mind, please, backuping and moving your ~/.raiden and then restarting Raiden after being sure your geth is in sync, and post here if the result is different? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by zhouzhou84** [comment] 2018-08-06 01:41
@andrevmatos hello, I move `~/.raiden` to other location, and restart raiden, and the geth is synced,but the result is same.

one terminal:
`ubuntu@ip-172-31-15-69:~$ raiden --keystore-path  ~/data/eth_ropsten/keystore
Welcome to Raiden, version 0.4.2!
----------------------------------------------------------------------
| This is an Alpha version of experimental open source software      |
| released under the MIT license and may contain errors and/or bugs. |
| Use of the software is at your own risk and discretion. No         |
| guarantee whatsoever is made regarding its suitability for your    |
| intended purposes and its compliance with applicable law and       |
| regulations. It is up to the user to determine the software´s      |
| quality and suitability and whether its use is compliant with its  |
| respective regulatory regime, especially in the case that you are  |
| operating in a commercial context.                                 |
----------------------------------------------------------------------
The following accounts were found in your machine:

[  0] - 0x3C46570896F3eC1323280Df466716d1076a7162B
[  1] - 0x13AE1c7fb262be079d7850d435D75a9bFC141b8e

Select one of them by index to continue: 0
Enter the password to unlock 0x3C46570896F3eC1323280Df466716d1076a7162B:
Checking if the ethereum node is synchronized

You are connected to the 'ropsten' network and the DB path is: /home/ubuntu/.raiden/netid_3/3c465708/log.db
2018-08-06 01:37:19 [info     ] Automatically selecting matrix homeserver based on RTT [raiden.network.transport.matrix] homeserver=https://transport01.raiden.network rtt=0.173385
2018-08-06 01:37:20 [info     ] Lock 140283698392704 acquired on /home/ubuntu/.raiden/netid_3/3c465708/.lock [filelock]
2018-08-06 01:37:21 [info     ] LOGIN                          [raiden.network.transport.matrix] current_user=@0x3c46570896f3ec1323280df466716d1076a7162b:transport01.raiden.network homeserver=transport01.raiden.network server_url=https://transport01.raiden.network username=0x3c46570896f3ec1323280df466716d1076a7162b
2018-08-06 01:37:22 [info     ] TRANSPORT STARTED              [raiden.network.transport.matrix] current_user=@0x3c46570896f3ec1323280df466716d1076a7162b:transport01.raiden.network
The Raiden API RPC server is now running at http://127.0.0.1:5001/.

See the Raiden documentation for all available endpoints at
http://raiden-network.readthedocs.io/en/stable/rest_api.html
2018-08-06 01:37:51 [info     ] 127.0.0.1 - - [2018-08-06 01:37:51] "GET /api/1/address HTTP/1.1" 200 197 0.001446 [raiden.api.rest.pywsgi]
2018-08-06 01:38:08 [info     ] 127.0.0.1 - - [2018-08-06 01:38:08] "GET /api/1/tokens HTTP/1.1" 200 137 0.001992 [raiden.api.rest.pywsgi]
2018-08-06 01:40:15 [info     ] missed blocks                  [raiden.tasks] current_block=3779946 missed_blocks=1
`
other terminal:
`ubuntu@ip-172-31-15-69:~$ geth --datadir=/home/ubuntu/data/eth_ropsten attach
Welcome to the Geth JavaScript console!

instance: Geth/v1.8.13-unstable-1064b9e6/linux-amd64/go1.10.3
coinbase: 0x3c46570896f3ec1323280df466716d1076a7162b
at block: 3779930 (Mon, 06 Aug 2018 01:35:49 UTC)
 datadir: /home/ubuntu/data/eth_ropsten
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> eth.syncing
false
> eth.blockNumber
3779930
> exit
ubuntu@ip-172-31-15-69:~$ curl -i http://localhost:5001/api/1/address
HTTP/1.1 200 OK
mimetype: application/json
Content-Type: application/json
Content-Length: 61
Date: Mon, 06 Aug 2018 01:37:51 GMT

{"our_address": "0x3C46570896F3eC1323280Df466716d1076a7162B"}ubuntu@ip-172-31-15-69:~$
ubuntu@ip-172-31-15-69:~$ curl -i http://localhost:5001/api/1/tokens
HTTP/1.1 200 OK
mimetype: application/json
Content-Type: application/json
Content-Length: 2
Date: Mon, 06 Aug 2018 01:38:08 GMT

[]
ubuntu@ip-172-31-15-69:~$
`

**Comment by palango** [comment] 2018-08-06 10:03
@zhouzhou84 There should be a file called `raiden-debug.log` in the raiden directory. Can you please attach it here as it contains useful information for us to debug this problem. Thank you!

**Comment by zhouzhou84** [comment] 2018-08-06 10:11
@palango I'm sorry but I have attached it already at the beginning

**Comment by palango** [comment] 2018-08-06 10:12
@zhouzhou84 Is the log there from before or after moving the `.raiden` directory. For me it looks like it is the one from before, as it starts at `current_block=3761861`.

**Comment by zhouzhou84** [comment] 2018-08-06 10:28
@palango yeah,you are right,this is log from before. After moving the `.raiden`  directory, there is a new `raiden-debug.log` file in my `~` directory, it's strange too, the origrn file is in my `raiden` directory. Anyway the new one is 
```
2018-08-06 01:34:55 [debug    ] Matrix homeserver RTT times    [raiden.network.transport.matrix] rtt_times=[('https://transport01.raiden.network', 0.1840103333333333), ('https://transport03.raiden.network', 0.18584533333333333), ('https://transport02.raiden.network', 0.24432566666666666)]
2018-08-06 01:34:55 [info     ] Automatically selecting matrix homeserver based on RTT [raiden.network.transport.matrix] homeserver=https://transport01.raiden.network rtt=0.1840103333333333
2018-08-06 01:34:55 [info     ] Lock 139924971524728 acquired on /home/ubuntu/.raiden/netid_3/3c465708/.lock [filelock]
2018-08-06 01:34:58 [debug    ] starting at block number       [raiden.tasks] current_block=3779924
2018-08-06 01:34:58 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3779924>
2018-08-06 01:35:00 [info     ] LOGIN                          [raiden.network.transport.matrix] current_user=@0x3c46570896f3ec1323280df466716d1076a7162b:transport01.raiden.network homeserver=transport01.raiden.network server_url=https://transport01.raiden.network username=0x3c46570896f3ec1323280df466716d1076a7162b
2018-08-06 01:35:00 [debug    ] ROOM                           [raiden.network.transport.matrix] aliases=['#test:transport01.raiden.network'] current_user=@0x3c46570896f3ec1323280df466716d1076a7162b:transport01.raiden.network room=<Room id="!fqQVZEXgokgQhcYpMI:transport01.raiden.network" alias="#test:transport01.raiden.network">
2018-08-06 01:35:01 [info     ] TRANSPORT STARTED              [raiden.network.transport.matrix] current_user=@0x3c46570896f3ec1323280df466716d1076a7162b:transport01.raiden.network
2018-08-06 01:35:24 [debug    ] new block                      [raiden.tasks] number=3779925
2018-08-06 01:35:24 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3779925>
2018-08-06 01:35:33 [debug    ] new block                      [raiden.tasks] number=3779926
2018-08-06 01:35:33 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3779926>
2018-08-06 01:35:41 [debug    ] new block                      [raiden.tasks] number=3779927
2018-08-06 01:35:41 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3779927>
2018-08-06 01:35:42 [info     ] Lock 139924971524728 released on /home/ubuntu/.raiden/netid_3/3c465708/.lock [filelock]
2018-08-06 01:37:19 [debug    ] Matrix homeserver RTT times    [raiden.network.transport.matrix] rtt_times=[('https://transport01.raiden.network', 0.173385), ('https://transport03.raiden.network', 0.18184233333333333), ('https://transport02.raiden.network', 0.24244933333333332)]
2018-08-06 01:37:19 [info     ] Automatically selecting matrix homeserver based on RTT [raiden.network.transport.matrix] homeserver=https://transport01.raiden.network rtt=0.173385
2018-08-06 01:37:20 [info     ] Lock 140283698392704 acquired on /home/ubuntu/.raiden/netid_3/3c465708/.lock [filelock]
2018-08-06 01:37:20 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<ContractReceiveNewPaymentNetwork network:<PaymentNetworkState id:dfd10bae>>
2018-08-06 01:37:20 [debug    ] starting at block number       [raiden.tasks] current_block=3779937
2018-08-06 01:37:20 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3779937>
2018-08-06 01:37:21 [info     ] LOGIN                          [raiden.network.transport.matrix] current_user=@0x3c46570896f3ec1323280df466716d1076a7162b:transport01.raiden.network homeserver=transport01.raiden.network server_url=https://transport01.raiden.network username=0x3c46570896f3ec1323280df466716d1076a7162b
2018-08-06 01:37:22 [debug    ] ROOM                           [raiden.network.transport.matrix] aliases=['#test:transport01.raiden.network'] current_user=@0x3c46570896f3ec1323280df466716d1076a7162b:transport01.raiden.network room=<Room id="!fqQVZEXgokgQhcYpMI:transport01.raiden.network" alias="#test:transport01.raiden.network">
2018-08-06 01:37:22 [info     ] TRANSPORT STARTED              [raiden.network.transport.matrix] current_user=@0x3c46570896f3ec1323280df466716d1076a7162b:transport01.raiden.network
2018-08-06 01:37:51 [info     ] 127.0.0.1 - - [2018-08-06 01:37:51] "GET /api/1/address HTTP/1.1" 200 197 0.001446 [raiden.api.rest.pywsgi]
2018-08-06 01:38:08 [info     ] 127.0.0.1 - - [2018-08-06 01:38:08] "GET /api/1/tokens HTTP/1.1" 200 137 0.001992 [raiden.api.rest.pywsgi]
2018-08-06 01:38:12 [debug    ] new block                      [raiden.tasks] number=3779938


and so on .......



2018-08-06 04:13:36 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3780531>
2018-08-06 04:13:40 [debug    ] new block                      [raiden.tasks] number=3780532
2018-08-06 04:13:40 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3780532>
2018-08-06 09:38:20 [debug    ] Matrix homeserver RTT times    [raiden.network.transport.matrix] rtt_times=[('https://transport01.raiden.network', 0.179059), ('https://transport03.raiden.network', 0.18693833333333335), ('https://transport02.raiden.network', 0.2509923333333333)]
2018-08-06 09:38:20 [info     ] Automatically selecting matrix homeserver based on RTT [raiden.network.transport.matrix] homeserver=https://transport01.raiden.network rtt=0.179059
2018-08-06 09:38:21 [info     ] Lock 140395931073728 acquired on /home/ubuntu/.raiden/netid_3/3c465708/.lock [filelock]
2018-08-06 09:38:22 [debug    ] starting at block number       [raiden.tasks] current_block=3782537
2018-08-06 09:38:22 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3782537>
2018-08-06 09:38:23 [info     ] LOGIN                          [raiden.network.transport.matrix] current_user=@0x3c46570896f3ec1323280df466716d1076a7162b:transport01.raiden.network homeserver=transport01.raiden.network server_url=https://transport01.raiden.network username=0x3c46570896f3ec1323280df466716d1076a7162b
2018-08-06 09:38:24 [debug    ] ROOM                           [raiden.network.transport.matrix] aliases=['#test:transport01.raiden.network'] current_user=@0x3c46570896f3ec1323280df466716d1076a7162b:transport01.raiden.network room=<Room id="!fqQVZEXgokgQhcYpMI:transport01.raiden.network" alias="#test:transport01.raiden.network">
2018-08-06 09:38:24 [info     ] TRANSPORT STARTED              [raiden.network.transport.matrix] current_user=@0x3c46570896f3ec1323280df466716d1076a7162b:transport01.raiden.network
2018-08-06 09:38:28 [debug    ] new block                      [raiden.tasks] number=3782538
2018-08-06 09:38:28 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3782538>
2018-08-06 09:38:35 [info     ] 127.0.0.1 - - [2018-08-06 09:38:35] "GET /api/1/address HTTP/1.1" 200 197 0.001471 [raiden.api.rest.pywsgi]
2018-08-06 09:38:42 [debug    ] new block                      [raiden.tasks] number=3782539
2018-08-06 09:38:42 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3782539>
2018-08-06 09:38:44 [info     ] 127.0.0.1 - - [2018-08-06 09:38:44] "GET /api/1/tokens HTTP/1.1" 200 137 0.001930 [raiden.api.rest.pywsgi]
2018-08-06 09:38:52 [debug    ] new block                      [raiden.tasks] number=3782540
2018-08-06 09:38:52 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3782540>
2018-08-06 09:38:55 [debug    ] new block                      [raiden.tasks] number=3782541



and 

2018-08-06 09:40:03 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3782548>
2018-08-06 09:40:19 [debug    ] new block                      [raiden.tasks] number=3782549
2018-08-06 09:40:19 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3782549>
2018-08-06 09:40:34 [debug    ] new block                      [raiden.tasks] number=3782550
2018-08-06 09:40:34 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3782550>
2018-08-06 09:40:51 [debug    ] new block                      [raiden.tasks] number=3782551
2018-08-06 09:40:51 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3782551>
2018-08-06 09:41:01 [debug    ] new block                      [raiden.tasks] number=3782552
2018-08-06 09:41:01 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3782552>
2018-08-06 09:41:30 [debug    ] new block                      [raiden.tasks] number=3782553
2018-08-06 09:41:30 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3782553>
2018-08-06 09:41:33 [debug    ] new block                      [raiden.tasks] number=3782554
2018-08-06 09:41:33 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=3c465708 state_change=<Block 3782554>
2018-08-06 09:41:39 [info     ] Lock 140395931073728 released on /home/ubuntu/.raiden/netid_3/3c465708/.lock [filelock]

```

**Comment by palango** [comment] 2018-08-06 10:35
@zhouzhou84 Thanks! Can you please attach the whole file here? Should be possible by dragging it onto the comment file. 

Also: As there are multiple runs in the log file, do you still remember at which time you moved the `.raidem` directory?

**Comment by zhouzhou84** [comment] 2018-08-06 10:44
I will attach it tomorrow , maybe after I set up a issue, I move it. thank you so much On 2018-08-06 18:36 , Paul Lange Wrote: @zhouzhou84 Thanks! Can you please attach the whole file here? Should be possible by dragging it onto the comment file. Also: As there are multiple runs in the log file, do you still remember at which time you moved the .raidem directory? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by zhouzhou84** [comment] 2018-08-07 01:36
[raiden-debug.log](https://github.com/raiden-network/raiden/files/2264620/raiden-debug.log)
[new_raiden-debug.log](https://github.com/raiden-network/raiden/files/2264621/new_raiden-debug.log)

**Comment by palango** [comment] 2018-08-07 09:14
@zhouzhou84 Thanks for the logs, unfortunately they don't include the information I'm looking for. Can you please execute the following steps to make sure your Raiden node starts from scratch:
- Move the `.raiden` directory to some other location
- Move all existing `raiden-debug.log` files to some other folder, so we get fresh ones
- Start Raiden again, wait a couple of minutes.
- Stop Raiden and upload the log file again.

Thank you so much for you help!

**Comment by zhouzhou84** [comment] 2018-08-07 09:30
it's very very strange, I follow your step to delete the file and folder, and start the geth and raiden, at first 
it's 
```
2018-08-07 09:23:20 [info     ] Lock 139856254181272 acquired on /home/ubuntu/.raiden/netid_3/3c465708/.lock [filelock]
Traceback (most recent call last):
  File "raiden-script.py", line 2, in <module>
  File "site-packages/raiden/__main__.py", line 11, in main
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1043, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "site-packages/click/decorators.py", line 17, in new_func
  File "site-packages/raiden/ui/cli.py", line 1037, in run
  File "site-packages/raiden/ui/cli.py", line 893, in run
  File "site-packages/raiden/ui/cli.py", line 911, in _run_app
  File "site-packages/raiden/ui/cli.py", line 735, in run_app
  File "site-packages/raiden/app.py", line 131, in start
  File "site-packages/raiden/raiden_service.py", line 278, in start
  File "site-packages/raiden/raiden_service.py", line 253, in start_async
  File "site-packages/raiden/tasks.py", line 140, in first_run
  File "site-packages/raiden/tasks.py", line 146, in run_callbacks
  File "site-packages/raiden/raiden_service.py", line 372, in _callback_new_block
  File "site-packages/raiden/blockchain_events_handler.py", line 243, in on_blockchain_event
  File "site-packages/raiden/blockchain_events_handler.py", line 92, in handle_channel_new
  File "site-packages/raiden/raiden_service.py", line 449, in connection_manager_for_token_network
  File "site-packages/raiden/connection_manager.py", line 87, in __init__
  File "site-packages/raiden/api/python.py", line 60, in __init__
RuntimeError: The RaidenService must be started before the API can be used
[32073] Failed to execute script raiden-script
--- Logging error ---
Exception ignored in: <bound method BaseFileLock.__del__ of <filelock.UnixFileLock object at 0x7f32d2599f98>>
Traceback (most recent call last):
  File "site-packages/filelock.py", line 330, in __del__
  File "site-packages/filelock.py", line 317, in release
  File "logging/__init__.py", line 1307, in info
  File "logging/__init__.py", line 1443, in _log
  File "logging/__init__.py", line 1453, in handle
  File "logging/__init__.py", line 1515, in callHandlers
  File "logging/__init__.py", line 864, in handle
  File "logging/__init__.py", line 999, in emit
  File "logging/__init__.py", line 917, in handleError
  File "/usr/local/lib/python3.6/traceback.py", line 100, in print_exception
  File "site-packages/raiden/log_config.py", line 156, in tracebackexception_format
  File "site-packages/raiden/log_config.py", line 142, in processor_wrapper
ImportError: sys.meta_path is None, Python is likely shutting down

```

then I start raiden again ,it WORKS when I check token network with ` curl -i http://localhost:5001/api/1/tokens` ,and it shows
```
ubuntu@ip-172-31-15-69:~$ curl -i http://localhost:5001/api/1/tokens
HTTP/1.1 200 OK
mimetype: application/json
Content-Type: application/json
Content-Length: 828
Date: Tue, 07 Aug 2018 09:24:44 GMT

["0x0f114A1E9Db192502E7856309cc899952b3db1ED", "0x2F4Aaa4112E1891cC32b630e167a7179cFbE7b03", "0xf01C9ED31c396dcA09a1DeeECBe2F12fC819E3Be", "0x68fB3bc1572b917096C9FcaF0A0A46a7b79544f6", "0x2608096B2aEbD85bc3c61444cA43dC136Cd5CEd8", "0x34767417888B7d1dA5e21f288Af2562d202CefD0", "0xB4D614d4903A15002Aeb816f06BDc6c4B7C71d34", "0xe8b470f695f15585955bBE42d0a41E583183f237", "0xa4B9467aBF384008085142a93670985Ecf9E61EE", "0xc778417E063141139Fce010982780140Aa0cD5Ab", "0x138CDf9A70f28Aa2c6C61FDf43078e9bA10EBba7", "0x277998a7d6c7B2aA21ec829d60E688eA04d0BB20", "0xc5569f4a8b3047Cc8b7093829296a722Bbe4d9Cd", "0x2E2A012D28cC95ed6A254fe14501722925719e72", "0x5d662156c457Ee5B0169dD9475E537E7e73546D5", "0x857f67519691Ef449156aadbcCaC71284D6194A7", "0xd18da7B6E727f288aA056842723476284Beae36E", "0xFF24D15afb9Eb080c089053be99881dd18aa1090"]ubuntu@ip-172-31-15-69:~$

```
[raiden-debug.log](https://github.com/raiden-network/raiden/files/2265823/raiden-debug.log)

**Comment by andrevmatos** [comment] 2018-08-07 09:35
That first error is caused by #2057 and should be already fixed in master, so no worries. About it starting to work now, that's the expected behavior, stranger was it wasn't working before, and we can't see how. Nice it's fixed for you.

**Comment by palango** [comment] 2018-08-07 09:35
@zhouzhou84 We know about the first error. It has already been fixed and will be made available in the next release.

The new logs indicate that getting the token networks worked fine this time. Thanks for your patience and don't hesitate to ask when you run into problems in the future.

**Closed by palango** 2018-08-07 09:35 UTC
