### ISSUE TITLE
Make `/ui/assets/config/config.production.json` available before syncing blocks

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/raiden#6318] opened 2020-06-16 12:21 UTC
## Problem Definition

When Raiden initially syncs and the status endpoint returns `syncing` or `unavailable`, `GET /ui/assets/config/config.production.json` returns `{"errors": "Service unavailable, try again later"}`.

As this config file is necessary for the WebUI to function correctly it should be available at the same time as the WebUI is available. 

This leads to this bug in the WebUI: https://github.com/raiden-network/webui/issues/475

### System Description

Raiden v1.0.1

**Comment by ulope** [comment] 2020-06-16 12:23
Duplicate of #6072

**Closed by ulope** 2020-06-16 12:23 UTC
Labels: Type / Bug
