### ISSUE TITLE
Node crashes when closing channels

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/raiden#5051] opened 2019-10-08 12:41 UTC
Tried closing channels that were automatically opened when joining a token network and it resulted in my node crashing with this error:

```FATAL: The channel was not open at the provided block (b'\xe8\xe9\x0b\xf4i`j\xd91!\xfc\xbb\x0f2`\xbe(\x0b\xb7S\x82\xf4\xa88\xf7\xe7\xf6X\xb0\x1a"\x13'). This call should never have been attempted.```

Not sure if this is somehow related to issue #5048 and perhaps should belong as a comment there.

[node_0faa9bcd.zip](https://github.com/raiden-network/raiden/files/3702371/node_0faa9bcd.zip)
[07-11-node0faa.log.zip](https://github.com/raiden-network/raiden/files/3702364/07-11-node0faa.log.zip)

**Comment by Dominik1999** [comment] 2019-10-08 13:32
I think this might be an error of the geth node not working on Rinkeby. We try to reproduce that with other clients. 

Please do not use the bb geth node for now

**Comment by rakanalh** [comment] 2019-10-08 13:46
@taleldayekh please try to reproduce the issue on another eth node. If not reproducible, please close the issue.

**Comment by taleldayekh** [comment] 2019-10-08 14:10
I could close the channels using a Infura node without the node crashing.

**Comment by rakanalh** [comment] 2019-10-14 10:23
Let's look at the logs and summarize why Raiden raised this exception.

**Comment by rakanalh** [comment] 2019-10-15 12:28
My guess for this is that the database has a `pending_transaction` that Raiden tries to execute (maybe a deposit transaction?). While this is happening the channel is closed so the previous pending transaction fails or the channel might have been closed by the partner while we're trying to deposit.

If that's the case, receiving the state change for `ChannelClosed` should have invalidated any pending transaction that operates on that presumably open channel.

**Comment by LefterisJP** [comment] 2019-10-15 13:14
Will have a look here. Unassigned Jochen as this may not be the same as the issue he is working on

**Comment by Dominik1999** [comment] 2019-10-16 09:37
can we label this as a bug? Or is it something else?

**Comment by LefterisJP** [comment] 2019-10-16 09:40
The label is "investigating" at the moment. Which means trying to figure out what it is and why it happened.

**Comment by LefterisJP** [comment] 2019-10-16 16:01
> You should be able to find the partner transaction on the blockchain, no?

It's rather difficult to analyze this only via etherscan since the TokenNetwork is not verified on Rinkeby, and since our own nodes are not archive nodes and as such can't do queries for a specific block due to pruning.

I think my theory holds as a problem which needs solving but for this issue my theory of the partner closing seems to not hold as I can't see any close transaction sent by the partner at all (it would start with `0x82fd7795`): https://rinkeby.etherscan.io/address/0x9fB5E3610D635ca2d1409B8DEDBB96fe38B2d36E

On the other hand our node does send a close transaction and it does succeed: https://rinkeby.etherscan.io/tx/0xf249ac5d9205a52c9ae51f5050f8d6773bb51787157fcbb59a7c1b83ea9f80bb

But it only sends that once.

So perhaps clicking the close channel multiple times? The second time just like I described [above](https://github.com/raiden-network/raiden/issues/5051#issuecomment-542727450) at the right moment in order to create the race? Would have to see if that is also reproducable.

**Comment by LefterisJP** [comment] 2019-10-16 16:32
Okay looking onchain it does not seem to be any form of race.

- token_network_address: `0x11e5a4247AE70f790fEAb91d6eEbe6fE89D84161`
- channel_identifier: `2`
- our_address: `0x0faA9bCdFcC07E9cCD94c4CC7d799fcCAf22c0C2`
- partner_address: `0x9fB5E3610D635ca2d1409B8DEDBB96fe38B2d36E`

Channel lifetime

- Opened at: 5220593
- Closed at:  5220678 
- The error happens due to a channel close triggered much later at: 5226579

**Comment by LefterisJP** [comment] 2019-10-16 19:10
@taleldayekh Do you have logs/DB from an earlier run where this channel was opened?

**Comment by taleldayekh** [comment] 2019-10-16 19:39
Hi @LefterisJP  unfortunately I don't have any of the logs on my machine anymore.

**Comment by rakanalh** [comment] 2019-10-17 08:24
> But **exactly** because they are added to the end of the state changes list, the `ActionChannelClose` state change will pass fine since our local view of the channel will not have yet processed the `ContractReceiveChannelClosed`.

We have:

https://github.com/raiden-network/raiden/blob/a8f16643016b6f638ee698a052c65988929229d3/raiden/transfer/node.py#L985-L992

That invalidated a transaction based on the state change that was incoming. Maybe after batch state change dispatch was implemented, we did not take into account this scenario.
I think the suggested approach to place blockchain transaction at the beginning or introduce a new functionaly such that: while we are dispatching state changes, events are purged based on what the state changes are similar to the function above.

**Comment by LefterisJP** [comment] 2019-10-17 10:48
@rakanalh As I wrote above the problem is that the `ContractReceiveChannelClosed` has not been seen by the node for this issue. It's not the race I theorized about in the beginning.

I think that we need to close this issue since there is no logs from the run where the close happened so we can try to see why the event was not turned into a state change.

Perhaps we can re-open once we see this happen again and this time with enough logs?

**Comment by rakanalh** [comment] 2019-10-17 12:57
I think we can close it.

My question before we do is: assuming that the node was running when the channel was opened and it received the `OPENED` event. But it was offline when the channel was closed and the block at which the channel was closed was pruned. Do we still get the event?

**Comment by LefterisJP** [comment] 2019-10-17 14:05
> My question before we do is: assuming that the node was running when the channel was opened and it received the OPENED event. But it was offline when the channel was closed and the block at which the channel was closed was pruned. Do we still get the event?

We should according to the code since we query from the last seen state change block.

@taleldayekh Can you try the following? Use the same account in Rinkeby: `0x0faA9bCdFcC07E9cCD94c4CC7d799fcCAf22c0C2` but with a deleted database and once it's up and running and all events are queried from the blockchain close it and send us the DB and logs?

I want to see if the channel close event for [this](https://rinkeby.etherscan.io/tx/0xf249ac5d9205a52c9ae51f5050f8d6773bb51787157fcbb59a7c1b83ea9f80bb) transaction will be seen.

**Comment by taleldayekh** [comment] 2019-10-17 14:30
Sorry guys it's gone with the logs, removed all excess accounts that was not used after updating my os, though it was enough to upload the logs. Will remember to keep them for the next time.

**Closed** 2019-10-17 14:35 UTC
Labels: could not reproduce
