### ISSUE TITLE
Raiden crashes

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2220] opened 2018-08-21 09:37 UTC
## Problem Definition

When starting Raiden, using the remote parity node I have experienced the following stacktrace which was followed by the client crashing. 
```
./raiden-0.5.1-linux --keystore-path  ~/.ethereum/testnet/keystore --log-config 'raiden:debug' --eth-rpc-endpoint "some endpoint"
Welcome to Raiden, version 0.5.1!
----------------------------------------------------------------------
| This is an Alpha version of experimental open source software      |
| released under the MIT license and may contain errors and/or bugs. |
| Use of the software is at your own risk and discretion. No         |
| guarantee whatsoever is made regarding its suitability for your    |
| intended purposes and its compliance with applicable law and       |
| regulations. It is up to the user to determine the software´s      |
| quality and suitability and whether its use is compliant with its  |
| respective regulatory regime, especially in the case that you are  |
| operating in a commercial context.                                 |
----------------------------------------------------------------------
The following accounts were found in your machine:

[  0] - 0x97a9F9222bA359E5547055500769E5cd662ca0AF
[  1] - 0x8A0cE8bDA200D64d858957080bf7eDDD3371135F

Select one of them by index to continue: 0
Enter the password to unlock 0x97a9F9222bA359E5547055500769E5cd662ca0AF: 
2018-08-21 09:21:10 [debug    ] JSONRPCClient created          [raiden.network.rpc.client] available_nonce=21 sender=97a9f922
Checking if the ethereum node is synchronized

You are connected to the 'ropsten' network and the DB path is: /home/cosmin/.raiden/netid_3/97a9f922/log.db
2018-08-21 09:21:14 [debug    ] Matrix homeserver RTT times    [raiden.network.transport.matrix] rtt_times=[('https://transport03.raiden.network', 0.023908333333333337), ('https://transport01.raiden.network', 0.033168666666666666), ('https://transport02.raiden.network', 0.12614866666666666)]
2018-08-21 09:21:14 [info     ] Automatically selecting matrix homeserver based on RTT [raiden.network.transport.matrix] homeserver=https://transport03.raiden.network rtt=0.023908333333333337
2018-08-21 09:21:14 [info     ] Lock 139870216404384 acquired on /home/cosmin/.raiden/netid_3/97a9f922/.lock [filelock] 
2018-08-21 09:21:14 [debug    ] Restoring from snapshot        [raiden.storage.wal] 
2018-08-21 09:21:14 [debug    ] Replaying state changes        [raiden.storage.wal] num_state_changes=188
2018-08-21 09:21:14 [debug    ] Restored state from WAL        [raiden.raiden_service] last_restored_block=3876461
2018-08-21 09:21:15 [debug    ] starting at block number       [raiden.tasks] current_block=3880309
2018-08-21 09:21:15 [debug    ] BLOCKCHAIN EVENT               [raiden.blockchain_events_handler] chain_event=<Event contract: 9fe1f19d event: {'args': AttributeDict({'channel_identifier': 84, 'participant1': '0x3206bE478B6cE18d8b920Bf444aA0f090d597c44', 'participant2': '0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1', 'settle_timeout': 600}), 'event': 'ChannelOpened', 'logIndex': 7, 'transactionIndex': 9, 'transactionHash': HexBytes('0x0de0b2435749a4ab310761dd5c6024d08d4e9c2ab8ff365874023d6657696044'), 'address': '0x9FE1f19D8C0d2591Fd01486E575B44f4220eF241', 'blockHash': HexBytes('0x1f9640eab66a956efc45185c9b3efcfc5d2c42cb8b68d1b9917d60ab94c07bd2'), 'blockNumber': 3879097, 'block_number': 3879097, 'channel_identifier': 84, 'participant1': b'2\x06\xbeG\x8bl\xe1\x8d\x8b\x92\x0b\xf4D\xaa\x0f\t\rY|D', 'participant2': b'\x90\xf8\xbfjG\x9f2\x0e\xad\x07D\x11\xa4\xb0\xe7\x94N\xa8\xc9\xc1', 'settle_timeout': 600}> node=97a9f922
Traceback (most recent call last):
  File "raiden-script.py", line 2, in <module>
  File "site-packages/raiden/__main__.py", line 11, in main
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1043, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "site-packages/click/decorators.py", line 17, in new_func
  File "site-packages/raiden/ui/cli.py", line 1058, in run
  File "site-packages/raiden/ui/cli.py", line 917, in run
  File "site-packages/raiden/ui/cli.py", line 935, in _run_app
  File "site-packages/raiden/ui/cli.py", line 759, in run_app
  File "site-packages/raiden/app.py", line 132, in start
  File "site-packages/raiden/raiden_service.py", line 310, in start
  File "site-packages/raiden/raiden_service.py", line 275, in start_async
  File "site-packages/raiden/tasks.py", line 166, in first_run
  File "site-packages/raiden/tasks.py", line 172, in run_callbacks
  File "site-packages/raiden/raiden_service.py", line 417, in _callback_new_block
  File "site-packages/raiden/blockchain_events_handler.py", line 291, in on_blockchain_event
  File "site-packages/raiden/blockchain_events_handler.py", line 116, in handle_channel_new
  File "site-packages/raiden/network/rpc/client.py", line 289, in get_transaction_from
  File "site-packages/web3/utils/datastructures.py", line 33, in __getitem__
KeyError: 'from'
[19636] Failed to execute script raiden-script
Exception ignored in: <bound method BaseFileLock.__del__ of <filelock.UnixFileLock object at 0x7f3612903da0>>
Traceback (most recent call last):
  File "site-packages/filelock.py", line 330, in __del__
  File "site-packages/filelock.py", line 317, in release
  File "logging/__init__.py", line 1306, in info
  File "logging/__init__.py", line 1441, in _log
  File "logging/__init__.py", line 1411, in makeRecord
  File "logging/__init__.py", line 300, in __init__
  File "threading.py", line 1240, in current_thread
  File "site-packages/gevent/threading.py", line 131, in __init__
ImportError: sys.meta_path is None, Python is likely shutting down
```
[raiden-debug.txt](https://github.com/raiden-network/raiden/files/2305682/raiden-debug.txt)

### System Description
```
Linux 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Linux.g++
/usr/bin/geth
Geth
Version: 1.8.12-stable
Git Commit: 37685930d953bcbe023f9bc65b135a8d8b8f1488
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.1
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.10
```

**Comment by czepluch** [comment] 2018-08-21 09:54
Note this only happens the first time Raiden is started after deleting the db. At least to me.

**Comment by CosminNechifor** [comment] 2018-08-21 09:55
Same thing happens here.

**Comment by andrevmatos** [comment] 2018-08-21 09:56
Looks like duplicated from #2211, and fixed in #2212. You sure you're on current master?

**Comment by CosminNechifor** [comment] 2018-08-21 09:57
I got this on 0.5.1 release. I will check it on current master.

**Comment by czepluch** [comment] 2018-08-21 09:59
Great. Neither of us are on current master afaik. We were trying to recreate the issue in https://github.com/raiden-network/raiden/issues/2218 when this happened and I guess neither of us realized it was a duplicate.

**Comment by andrevmatos** [comment] 2018-08-21 10:00
Ok, the marking as duplicate of #2211

**Closed by andrevmatos** 2018-08-21 10:00 UTC
