### ISSUE TITLE
Rest API unhandled exceptions should crash the node

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden#2179] opened 2018-08-14 11:00 UTC
## Problem Definition

After a lot of debugging, it was made clear that `gevent` already bubbles up unhandled exceptions up to the parent greenlet, which is the expected behavior. Except when the greenlet is spawned by the `APIServer`, where flask handles all exceptions and return `500` errors, where we want the node to crash. We must make sure the node also exits if any unhandled exception happens in the greenlet which handles a request.
Related: #2123 
Requires: #2171

**Comment by hackaugusto** [comment] 2018-08-14 15:11
To clarify, flask has a different policy then Raiden, instead of crashing on uncaught exceptions they are printed and the server continues serving.

In Raiden we must handle the recoverable exceptions or crash the node. This means the [logic used in flask](https://github.com/pallets/flask/blob/dfd3619d6f8796d48fc4e32f819cec9e8aa59156/flask/app.py#L1801-L1816) must be tweaked. Possible fixes:

- Install a error handler that will re-raise the exception
- Overwrite the [handle_user_exception](https://github.com/pallets/flask/blob/dfd3619d6f8796d48fc4e32f819cec9e8aa59156/flask/app.py#L1680) to always raise exceptions
- Overwite the [full_dispatch_event](https://github.com/pallets/flask/blob/dfd3619d6f8796d48fc4e32f819cec9e8aa59156/flask/app.py#L1801-L1816) and completely skip the exception handlers.

I would go with option 1, because there may be use internal flask exceptions that we are unaware of.

**Comment by hackaugusto** [comment] 2018-08-28 07:12
This is not done, the flask server is still handling all the exceptions.

**Comment by andrevmatos** [comment] 2018-08-28 07:26
@hackaugusto care to show steps to reproduce? [raiden/tests/integration/api/test_restapi.py::test_crash_on_unhandled_exception](https://github.com/raiden-network/raiden/blob/9426dec0c8585f1075ee19a0df3de4c90036995c/raiden/tests/integration/api/test_restapi.py#L158-L178) aims to test exactly that. The exception is still handled and may become a `E500` response, but the `APIServer` crashes right after, and the exception will be re-raised with #2208

**Comment by andrevmatos** [comment] 2018-09-04 08:44
@hackaugusto can you confirm this is still an issue after #2208 ?

**Comment by hackaugusto** [comment] 2018-09-04 11:05
Lets close this, I cant reproduce the problem.

**Closed by hackaugusto** 2018-09-04 11:05 UTC
Labels: enhancement
