### ISSUE TITLE
Make token networks opt-in

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#2687] opened 2018-10-05 12:10 UTC
Right now we follow all token networks by default, meaning we have to keep internal state and query for blocks for all of them. At the moment we have 227 token networks in ropsten. This means we're doing a lot of bookkeeping for networks that most users will never join.

Instead we should do the syncing of a token network on demand, meaning whenever a channel is opened or a network is joined.

We could further improve this by also leaving token network in which all channels are settled and all funds have transferred.

**Comment by ulope** [comment] 2018-10-05 13:36
Doing this on demand could be problematic when users are connected to a light or pruning node as old state might not be available locally anymore (but I guess it's no worse than starting raiden for the first time while connected to such a node).

**Comment by hackaugusto** [comment] 2019-09-30 15:26
Note: Adding this would be a bit complicated because of how we handle restarts:

- When a user opt in a new network, we have to dispatch some sort of state change
- Right after the above, the node has to start querying the blockchain for all the events of that token network, since its deployment.

Here is the tricky part, once the node starts fetching the events, somehow it has to know when it is synchronized with the canonical chain, until then it cannot use any of the data. I can think of a few ways of implementing this:

- The events are fetched, decoded, and kept in memory, until the current confirmed block is reached, a lock is acquired to stop the event fetching and all the events are dispatched. This would construct the local graph and update all the channels is one go. The problem with this approach is that it is fragile to restarts and memory usage is unbounded.
- The events are fetched and decoded like above, but instead of keeping them into memory they are persisted into the database. The advantage is that memory usage will be bounded and the code will be resilient to restarts. The problem is like above, once all events are ready the node will take a little while processing all the changes.
- Have a separate state tree for not synchronized token networks, these would be in a separate state tree that doesn't allow them to be used for payments until they are fully synchronized and then merged with the main state. This has the best flexibility of all approaches but is the most complex option code wise.

Before we try to tackled this, it is probably a good idea to introduce [this solution](https://github.com/raiden-network/raiden-contracts/issues/705#issuecomment-535019395) and `Remove the local routing module` #4982 first. These two strategies allows a node to automatically learn when to opt-in a network, automatically forbids unwanted channels from being open, and remove the necessity for the node to track the whole history of a token network smart contract.

**Comment by hackaugusto** [comment] 2020-05-20 05:27
Closing this since event fetching is slow regardless of the strategy.

Turns out that event fetching does a linear search in both clients. The approach used in Raiden is to fetch all the events with a single query:

https://github.com/raiden-network/raiden/pull/5003

The total number of smart contracts in the query will have marginal performance impact.

Notes: There are different problems, besides the speed of `eth_getLogs` that may appear. The size of the node's state may grow a lot with lots of TNs. The size of the request payload may also grow too large. But these are different problems then what the issue described.

**Closed by hackaugusto** 2020-05-20 05:27 UTC
Labels: State / In discussion, Type / Optimization
