### ISSUE TITLE
Raiden crashes after trying to register token network through webUI

### ISSUE THREAD

**Issue by lullis** [raiden-network/raiden#5779] opened 2020-01-29 18:29 UTC
When running latest develop branch while connected to Görli, the WebUI shows some of the Tokens generated by the Scenario Player + the Test Token. I wanted to register the Wizard Token, which led to the following:

```
2020-01-29 18:24:57.713109 [info     ] 127.0.0.1 - - [2020-01-29 19:24:57] "PUT /api/v1/tokens/0x95B2d84De40a0121061b105E6B54016a49621B44 HTTP/1.1" 500 161 3.064439 [raiden.api.rest.pywsgi] 
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "/home/raphael/code/brainbot/raiden/client/raiden/api/rest.py", line 439, in _run
    self.wsgiserver.serve_forever()
  File "/home/raphael/.virtualenvs/raiden/lib/python3.7/site-packages/gevent/baseserver.py", line 389, in serve_forever
    self._stop_event.wait()
  File "src/gevent/event.py", line 133, in gevent._event.Event.wait
  File "src/gevent/_abstract_linkable.py", line 208, in gevent.__abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 178, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 196, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 182, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
raiden.exceptions.BrokenPreconditionError: Number of token networks will exceed the max of 5
2020-01-29T18:24:57Z <Greenlet "APIServer|Greenlet-3" at 0x7f945954b4d0: _run> failed with BrokenPreconditionError

FATAL: An unexpected exception occured. A traceback has been written to /tmp/raiden-exception-2020-01-29T18-2580ljbh9m.txt
Number of token networks will exceed the max of 5
ReturnCode.FATAL
```

Aside from the lacking exception handling at the API, does this mean that it won't be possible to register the Wizard token on Raiden?

**Comment by palango** [comment] 2020-01-30 09:05
The registration error is caused by the deployment and will be fixed with the next deployment of the contracts.

We should handle the error better though.

**Closed** 2020-01-31 10:09 UTC
Labels: Component / API, Type / Bug, Type / Crash, [SP 3]
