### ISSUE TITLE
PFS7 Simple Path, SP not able to Assert the correct sum value

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5093] opened 2019-10-15 07:05 UTC
## Problem Definition

Scenario Player is not able to properly assert on the scenario
**` Expected sum value \"500000000000000000\" for channel fields \"balance\". Actual value: \"499685000000000000\".`**

`
{"task": "<AssertSumTask: {'from': 0, 'balance_sum': 500000000000000000}>", "event": "Task errored", "logger": "scenario_player.tasks.base", "level": "error", "timestamp": "2019-10-14 03:07:01.731026", "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 74, in __call__\n    return self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 70, in _run\n    return self._process_response(response_dict)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/channels.py\", line 244, in _process_response\n    f'Expected sum value \"{assert_value}\" for channel fields \"{field}\". '\nscenario_player.exceptions.legacy.ScenarioAssertionError: Expected sum value \"500000000000000000\" for channel fields \"balance\". Actual value: \"499685000000000000\". Channels: [{'reveal_timeout': 50, 'balance': 490000000000000000, 'state': 'opened', 'total_withdraw': 0, 'settle_timeout': 500, 'total_deposit': 1000000000000000000, 'channel_identifier': 2151, 'partner_address': '0x3f831beC72795C4d239e674CadFab2A541DaB22D', 'token_network_address': '0x9526EC0E58ac5Bb1e24d655E964f0eAA46054d16', 'token_address': '0x62083c80353Df771426D209eF578619EE68D5C7A'}, {'reveal_timeout': 50, 'balance': 9685000000000000, 'state': 'opened', 'total_withdraw': 0, 'settle_timeout': 500, 'total_deposit': 1000000000000000000, 'channel_identifier': 2154, 'partner_address': '0xc03301d7b4C1E8B4EC8a92e27721a131e5d4b9bb', 'token_network_address': '0x9526EC0E58ac5Bb1e24d655E964f0eAA46054d16', 'token_address': '0x62083c80353Df771426D209eF578619EE68D5C7A'}]"}
`

[Scenario_player_Logs-pfs7_multiple_payments-1-latest-2019-10-14.tar.gz](https://github.com/raiden-network/raiden/files/3727741/Scenario_player_Logs-pfs7_multiple_payments-1-latest-2019-10-14.tar.gz)

**Comment by rakanalh** [comment] 2019-10-16 08:44
Duplicate of #5078

**Closed by rakanalh** 2019-10-16 08:44 UTC
