### ISSUE TITLE
BF2 Raiden node gets No route between nodes found

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5627] opened 2020-01-10 11:10 UTC
## Problem Definition

Scenario:

node0: `0xe95906dc9eB6bd492845B77e331784323401C212`
node1: `0x6eb488CB84726642dD42D617192AC9ff5dd75aA0`
node2: `0x3FC72031A5f7Cf60DBD89d9faaC41CBF74f333e8`
node3: `0xD42E9f94ccf24695D1a5C24C7FF58964dCda3418`
node4: `0x3e487a7044b660c7439511818f6008192819DdC8`

```json
{
  "task": "<TransferTask: {'from': 0, 'to': 2, 'amount': 10000000000000000, 'lock_timeout': 30}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "timestamp": "2020-01-10 00:45:34.702252",
  "exception": "Traceback (most recent call last):
    File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 74, in __call__
      return self._run(*args, **kwargs)
    File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 59, in _run
      f'HTTP status code \"{resp.status_code}\" while fetching {url}. '
  scenario_player.exceptions.legacy.RESTAPIStatusMismatchError: HTTP status code \"409\" while fetching http://127.0.0.1:37451/api/v1/payments/0x62083c80353Df771426D209eF578619EE68D5C7A/0x3FC72031A5f7Cf60DBD89d9faaC41CBF74f333e8. Expected 2..: {\"errors\": \"Payment couldn't be completed because: No route between nodes found.\"}"
}

}
```

what the Exception says:

1. **Payment couldn't be completed because: No route between nodes found**

2. Failed during TransferTask
line 192
`- transfer: {from: 0, to: 2, amount: 10_000_000_000_000_000, lock_timeout: 30}`

3. Occurs at API call:

`http://127.0.0.1:37451/api/v1/payments/0x62083c80353Df771426D209eF578619EE68D5C7A/0x3FC72031A5f7Cf60DBD89d9faaC41CBF74f333e8`

`0x62083c80353Df771426D209eF578619EE68D5C7A` : token address
`0x3FC72031A5f7Cf60DBD89d9faaC41CBF74f333e8` : node2

https://drive.google.com/drive/folders/1MdROjSbLLifDGI_oiuVdFEN_N1eDxWAs?usp=sharing

**Comment by agatsoh** [comment] 2020-01-13 08:21
Today also there was the same exception logs for today can be found here 
https://drive.google.com/drive/folders/1h2OU8pfC1UEBcvfZQ32kpbkZnMmXs0FB?usp=sharing

**Comment by palango** [comment] 2020-01-13 13:52
The logs show that the PFS did not return a route:
```
  1 {
  2   "log_message": "No route between nodes found.",
  3   "http_error": 404,
  4   "error": "No route between nodes found.",
  5   "error_code": 2201,
  6   "event": "An error with the path request occured",
  7   "logger": "raiden.routing",
  8   "level": "warning",
  9   "timestamp": "2020-01-13 00:39:52.971757"
 10 }
 11 {
 12   "event": "Request to Pathfinding Service was not successful. No routes to the target are found.",
 13   "logger": "raiden.routing",
 14   "level": "warning",
 15   "timestamp": "2020-01-13 00:39:52.972024"
 16 }
 17 {
 18   "errors": "Payment couldn't be completed because: No route between nodes found.",
 19   "status_code": 409,
 20   "event": "Error processing request",
 21   "logger": "raiden.api.rest",
 22   "level": "error",
 23   "timestamp": "2020-01-13 00:39:52.975503"
 24 }
```

**Comment by palango** [comment] 2020-01-13 14:18
The according PFS logs:
```json
{
  "source": "0xdd8815d1ad23FE2b46881502604c0078B34919e7",
  "target": "0x65685EbFe96FF07172451015764540886a1C8386",
  "value": 1e+16,
  "max_paths": 3,
  "diversity_penalty": 5,
  "fee_penalty": 100,
  "event": "Finding paths for payment",
  "level": "debug",
  "logger": "pathfinding_service.model.token_network",
  "timestamp": "2020-01-13 00:39:52.915529"
}
{
  "nodes": [
    "0xdd8815d1ad23FE2b46881502604c0078B34919e7",
    "0x4B4676c5f5A56356f9Bb5282A076c01731Cf1f70",
    "0x65685EbFe96FF07172451015764540886a1C8386"
  ],
  "value": 1e+16,
  "event": "Checking path validity",
  "level": "debug",
  "logger": "pathfinding_service.model.token_network",
  "timestamp": "2020-01-13 00:39:52.965325"
}
{
  "edge": {
    "view": "<ChannelView cid=7873 from=0x4B4676c5f5A56356f9Bb5282A076c01731Cf1f70 to=0x65685EbFe96FF07172451015764540886a1C8386 capacity=0>"
  },
  "available_capacity": 0,
  "required_capacity": 1e+16,
  "event": "Path invalid because of missing capacity (without fees)",
  "level": "debug",
  "logger": "pathfinding_service.model.token_network",
  "timestamp": "2020-01-13 00:39:52.965853"
}
{
  "nodes": [
    "0xdd8815d1ad23FE2b46881502604c0078B34919e7",
    "0x4B4676c5f5A56356f9Bb5282A076c01731Cf1f70",
    "0x65685EbFe96FF07172451015764540886a1C8386"
  ],
  "is_valid": false,
  "fees": null,
  "event": "Created Path object",
  "level": "debug",
  "logger": "pathfinding_service.model.token_network",
  "timestamp": "2020-01-13 00:39:52.966232"
}
{
  "source": "0xdd8815d1ad23FE2b46881502604c0078B34919e7",
  "target": "0x65685EbFe96FF07172451015764540886a1C8386",
  "value": 1e+16,
  "max_paths": 3,
  "diversity_penalty": 5,
  "fee_penalty": 100,
  "paths": [],
  "event": "Returning paths for payment",
  "level": "info",
  "logger": "pathfinding_service.model.token_network",
  "timestamp": "2020-01-13 00:39:52.966583"
}
{
  "error": "NoRouteFound(None)",
  "details": {
    "from_": "0xdd8815d1ad23FE2b46881502604c0078B34919e7",
    "to": "0x65685EbFe96FF07172451015764540886a1C8386",
    "value": 1e+16
  },
  "message": "No route between nodes found.",
  "event": "Error while handling request",
  "level": "warning",
  "logger": "pathfinding_service.api",
  "timestamp": "2020-01-13 00:39:52.968171"
}

```

**Comment by palango** [comment] 2020-01-13 16:46
This seems to be fixed with https://github.com/raiden-network/raiden/pull/5634

I could not reproduce it on 81e535808f6f4d047495b76a555f623d3a6838f0 , but on f9bbbc0aeadf2ce1a54f3ed22de948133bc461df , which is roughly the same state as the scenario player used, it fails at exactly the same line in the scenario.

**Closed by palango** 2020-01-13 16:46 UTC
Labels: Component / PFS, Component / Scenario Player, State / Needs more info
