### ISSUE TITLE
Easy Onboarding with Raiden - Installation Wizzard

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#4058] opened 2019-05-13 14:51 UTC
## What do we need?

We need a Raiden installation wizard such that our Persona* could transact an ERC20 token on his own Raiden-Node using the new Raiden services that only contain 5 or fewer clicks.

## Motivation

The current setup of a Raiden node on testnet and mainnet consists of many steps and many options to choose. See [Installation guide](https://raiden-network.readthedocs.io/en/latest/overview_and_guide.html#installation).
We need to make this way easier for first time users that just want to play around and for us to have a bigger network. 

## Specification

Please translate [this process](https://www.figma.com/file/POjZxS9VCNeKZ5Kmh4vFEzDB/Raiden-Client-Onboarding?node-id=0%3A1) into a installation wizard that executes the following steps (maybe the installation wizard starts in step 4?):
1. the user chooses the OS of her system
2. the users downloads the latest stable Raiden master
3. the user unzips the installation wizard
4. the user opens the wizard
5. the user chooses to use the Ethereum mainnet or the Görli testnet
(we first do the testnet approach because this is easier)
6. the users enters her rpc (which is the endpoint of the Ethereum Node that is needed for Raiden). Here we offer the user to use [infura](https://infura.io/) (check it out, it is a service provider for remote ethereum nodes)
7. the rpc gets confirmed 
8. Raiden is initialized (this happens all automatically in the backend), 
8.1. so the user gets an ETH address
8.2. gets Test-ETH minted to that address 
8.3. gets Test-RDN tokens to that address
8.4. Raiden is installed 
8.5. a pathfinding service is selected automatically
8.6. a monitoring service is selected automatically
9. the Raiden WebUI starts
10. the user clicks on "Join Network" and joins a token network
11. the user sends tokes 

## How to start?

- [ ] try to install Raiden yourself, run it and send tokens via the WebUI to each other (this way you see the current process and why we need the wizzard)
- [ ] define the architecture of the programm together 
- [ ] find what is already there (we already have a one click installer that could be used for step 8, and our scenaro player is already able to get tokens automatically for some nodes 
- [ ] define how everything should look like frontend-wise
- [ ] ... 

## Resources
Please consider the following resources:
- One click installer issue (raiden-network/raiden#3525)
- One click installer repo (https://github.com/raiden-network/raiden-installer)
- WebUI repo (https://github.com/raiden-network/webui)
- Workshop repo (https://github.com/raiden-network/workshop/tree/eth_cape_town)
- Utils in Raiden Contracts (https://github.com/raiden-network/raiden-contracts/tree/master/raiden_contracts/utils)

**Comment by Dominik1999** [comment] 2019-05-13 15:17
@christianbrb FYI

**Comment by christianbrb** [comment] 2019-05-14 07:09
@Dominik1999 @taleldayekh added some additional information (https://github.com/raiden-network/raiden/issues/4058#issue-443443594)

We also need to consider, that the WebUI may also be used to interact with a remote host without the onboarding wizard.

**Comment by taleldayekh** [comment] 2019-05-17 08:35
I summarized some of my notes on the first iteration in this flowchart for future discussions.
![onboarding_installer_iteration_1](https://user-images.githubusercontent.com/43838780/57914665-64e69400-788f-11e9-9cc0-7d76811c5176.jpg)

**Comment by Dominik1999** [comment] 2019-05-17 08:37
that looks very good to me. Now let's sit down, with @lullis and see, how we can translate this into code

**Comment by LefterisJP** [comment] 2019-05-17 09:07
Has Infura implemented the 2 endpoints we need? Last I heard they did not have and without them using Raiden is [not safe](https://raiden-network.readthedocs.io/en/stable/overview_and_guide.html#using-eth-rpc-endpoint-infura).

**Comment by Dominik1999** [comment] 2019-05-17 09:17
> Has Infura implemented the 2 endpoints we need? Last I heard they did not have and without them using Raiden is not safe.

I think not yet, how could we know? For the testnets we still can take infura, right? And for the mainnet, we put some info in the disclaimer. The goal of the wizzard is for people being able to play around with Raiden and open nodes.

**Comment by LefterisJP** [comment] 2019-05-17 09:23
@christianbrb and I are cced in a conversation with the infura people. And last we heard they are still working on it.

> The goal of the wizzard is for people being able to play around with Raiden and open nodes.

Sure but this is sort of false advertising. It makes people think Raiden is something, while it's not when they try to use it for real and try to actually use infura.

>  For the testnets we still can take infura, right?

Makes no difference, testnets or mainnet. The problem is gonna be there. They may crash with the problem described in the link I posted above or they may not.

**Comment by LefterisJP** [comment] 2019-08-05 09:36
I am closing this as the wizard is there. For separate issues/features on the wizard do it on the wizard repo: https://github.com/raiden-network/raiden-installer

**Closed by LefterisJP** 2019-08-05 09:36 UTC
Labels: usability
