### ISSUE TITLE
Raiden crashes during state change replay when restarting node

### ISSUE THREAD

**Issue by err508** [raiden-network/raiden#2131] opened 2018-08-09 12:50 UTC
## Problem Definition

Traceback: 
```
Traceback (most recent call last):
  File "/home/no_name/raiden/.raiden/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/home/no_name/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/home/no_name/raiden/.raiden/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/no_name/raiden/.raiden/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/no_name/raiden/.raiden/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/no_name/raiden/.raiden/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/no_name/raiden/.raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/no_name/raiden/.raiden/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/no_name/raiden/raiden/ui/cli.py", line 1049, in run
    NodeRunner(kwargs, ctx).run()
  File "/home/no_name/raiden/raiden/ui/cli.py", line 903, in run
    app = self._run_app()
  File "/home/no_name/raiden/raiden/ui/cli.py", line 921, in _run_app
    app_ = run_app(**self._options)
  File "/home/no_name/raiden/raiden/ui/cli.py", line 745, in run_app
    raiden_app.start()
  File "/home/no_name/raiden/raiden/app.py", line 135, in start
    self.raiden.start()
  File "/home/no_name/raiden/raiden/raiden_service.py", line 289, in start
    self.start_async().wait()
  File "/home/no_name/raiden/raiden/raiden_service.py", line 212, in start_async
    storage,
  File "/home/no_name/raiden/raiden/storage/wal.py", line 32, in restore_from_latest_snapshot
    events.extend(state_manager.dispatch(state_change))
  File "/home/no_name/raiden/raiden/transfer/architecture.py", line 142, in dispatch
    state_change,
  File "/home/no_name/raiden/raiden/transfer/node.py", line 1054, in state_transition
    iteration = handle_state_change(chain_state, state_change)
  File "/home/no_name/raiden/raiden/transfer/node.py", line 708, in handle_state_change
    state_change,
  File "/home/no_name/raiden/raiden/transfer/node.py", line 433, in handle_chain_init
    state_change.our_address,
AttributeError: 'ActionInitChain' object has no attribute 'our_address'
2018-08-09 12:44:13 [info     ] Lock 140049462678584 released on /home/no_name/.raiden/netid_3/5d519dbd/.lock [filelock] 
```

`raiden-debug.log` output: 
```
2018-08-09 12:43:39 [debug    ] JSONRPCClient created          [raiden.network.rpc.client] available_nonce=0 sender=5d519dbd
2018-08-09 12:44:07 [debug    ] Matrix homeserver RTT times    [raiden.network.transport.matrix] rtt_times=[('https://transport01.raiden.network', 0.05481466666666667), ('https://transport03.raiden.network', 0.12624833333333332), ('https://transport02.raiden.network', 0.328347)]
2018-08-09 12:44:07 [info     ] Automatically selecting matrix homeserver based on RTT [raiden.network.transport.matrix] homeserver=https://transport01.raiden.network rtt=0.05481466666666667
2018-08-09 12:44:13 [info     ] Lock 140049462678584 acquired on /home/username/.raiden/netid_3/5d519dbd/.lock [filelock] 
2018-08-09 12:44:13 [debug    ] No snapshot found, replaying all state changes [raiden.storage.wal] 
2018-08-09 12:44:13 [debug    ] Replaying state changes        [raiden.storage.wal] num_state_changes=564
2018-08-09 12:44:13 [info     ] Lock 140049462678584 released on /home/username/.raiden/netid_3/5d519dbd/.lock [filelock] 
```
### System Description

```
uname -a
Linux box 4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

command -v solc && solc --version
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.23+commit.124ca40d.Linux.g++

command -v geth && geth version
/usr/bin/geth
Geth
Version: 1.8.2-stable
Git Commit: b8b9f7f4476a30a0aaf6077daade6ae77f969960
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.4
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.9

command -v raiden && raiden version
/home/username/raiden/.raiden/bin/raiden
{
  "raiden": "0.4.3.dev112+gd4c08c1",
  "python_implementation": "CPython",
  "python_version": "3.6.3",
  "system": "Linux 64bit_ELF 4.15.0-29-generic x86_64",
  "distribution": "source"
}

[ -d .git ] && git rev-parse HEAD
d4c08c1325741cd269babd2fb1a3a72cb4896bfc
```

**Comment by palango** [comment] 2018-08-09 13:06
This is caused by changes in the state change which make it incompatible with the one you have stored in the WAL. Until #862 is done you need to remove your Raiden database.

**Comment by hackaugusto** [comment] 2018-08-09 13:25
As @palango said, this is not a bug, it's a backwards incompatible change. Closing the issue

**Closed by hackaugusto** 2018-08-09 13:25 UTC
