### ISSUE TITLE
sync problem when depositing to a channel

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/raiden#1877] opened 2018-07-18 13:07 UTC
while connection manager was waiting for a confirmation of a deposit of 100 tokens, I did manual deposit of 12 tokens from webui. webui failed with error 500, 100 tokens got deposited properly.

```
Traceback (most recent call last):
  File "/home/xoza/.pyenv/versions/360_raiden/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/xoza/.pyenv/versions/360_raiden/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/xoza/.pyenv/versions/360_raiden/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/xoza/.pyenv/versions/360_raiden/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/xoza/.pyenv/versions/360_raiden/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/xoza/.pyenv/versions/360_raiden/lib/python3.6/site-packages/webargs/core.py", line 441, in wrapper
    return func(*args, **kwargs)
  File "/home/xoza/src/raiden/raiden/api/v1/resources.py", line 65, in patch
    **kwargs,
  File "/home/xoza/src/raiden/raiden/api/rest.py", line 790, in patch_channel
    result = self._deposit(registry_address, channel_state, total_deposit)
  File "/home/xoza/src/raiden/raiden/api/rest.py", line 693, in _deposit
    total_deposit,
  File "/home/xoza/src/raiden/raiden/api/python.py", line 358, in set_total_channel_deposit
    channel_proxy.set_total_deposit(total_deposit)
  File "/home/xoza/src/raiden/raiden/network/proxies/payment_channel.py", line 110, in set_total_deposit
    self.token_network.set_total_deposit(total_deposit, self.participant2)
  File "/home/xoza/src/raiden/raiden/network/proxies/token_network.py", line 428, in set_total_deposit
    raise ValueError(f'deposit {amount_to_deposit} must be greater than 0.')
ValueError: deposit -88 must be greater than 0.
```

**Comment by andrevmatos** [comment] 2018-07-18 14:11
Hmm, that's probably because, after the `total_deposit` changes, webUI needs to fetch the current balance, do the math over it, and send a new `total_deposit`. As the API result wasn't updated yet (assuming it'll be), webUI can't know how much more it needs to set

**Comment by rakanalh** [comment] 2018-07-23 12:41
Duplicate of #1916

**Closed** 2018-07-23 12:43 UTC
Labels: bug, ui
