### ISSUE TITLE
Refund transfer making first node to crash

### ISSUE THREAD

**Issue by rorolopetegui** [raiden-network/raiden#5936] opened 2020-02-25 19:13 UTC
Hi, 
Specs that i'm using:
-Release  v0.200.0-rc2 with Python 3.7.3 and fresh install with "pip install -r requirements.txt" and a "python setup.py develop".
-I'm running a local geth node for developing purposes. 
Scenario: 4 Nodes, and with the next scenario to make a mediated transfer with refund (Nothing special i think): 
-Node 1 which has channels to node 2, and 3.
-Node 4 which has channels to node 2, and 3.
All nodes will make a deposit of 10 tokens, so i can freely make transfers from everywhere i want.
To reproduce the error:
-Try a mediated from node 1 to 4... and with it, i can see the first route that the transfer will take. Lets say that the transfer will go from Node 1 -> Node 2 -> Node 4
*Now i just need to "burn" the tokens from Node 2 to Node 4, so the next mediated that i made will generate a Refund from Node 2 -> Node 1 and then try another route. 
-Try another mediated with an amount higher than the capacity of the Node 2 -> Node 4 

We'll see the Node 1 crashes, and the mediated will be made correctly as expected

Screenshots (First scenario, with a payment made from Node 2 to 4 of 8 tokens)
Node 1:
![Node1](https://user-images.githubusercontent.com/35036353/75278551-d6714c80-57e8-11ea-924b-75915410b670.png)
Node 2:
![Node2](https://user-images.githubusercontent.com/35036353/75278549-d5d8b600-57e8-11ea-8fc3-58d84d60dabd.png)
Node 3:
![Node3](https://user-images.githubusercontent.com/35036353/75278547-d5401f80-57e8-11ea-9921-5454a07379b7.png)
Node 4:
![Node4](https://user-images.githubusercontent.com/35036353/75278544-d4a78900-57e8-11ea-91b3-8f3b12da26ee.png)

Make payment from Node 1 to Node 4 with an amount of 3 tokens
The transfer will try first Node 1 -> Node 2 -> Node 4
And the Node 2 will send a refund transfer.
![Node1Payment](https://user-images.githubusercontent.com/35036353/75278702-1cc6ab80-57e9-11ea-8269-fb676b06a14f.png)

Confirmation of the transfer 
![Node1Confirmation](https://user-images.githubusercontent.com/35036353/75278803-4c75b380-57e9-11ea-9587-0d45560ff737.png)
And the Node 4 has the amount transfered...
![Node4Confirmation](https://user-images.githubusercontent.com/35036353/75278998-9a8ab700-57e9-11ea-9b5f-0db4fb137278.png)

After that, Node 1 will crash, here's the tracestack:
```
2020-02-25 19:05:49.523849 [critical ] Unhandled exception when processing endpoint request [raiden.api.rest] node=0x5516f531042D25aAeD938B2d7aF54C50cDA3d448
Traceback (most recent call last):
  File "/home/rorolopetegui/Documents/Projects/Rsk/raidenOne/clientEnv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rorolopetegui/Documents/Projects/Rsk/raidenOne/clientEnv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rorolopetegui/Documents/Projects/Rsk/raidenOne/clientEnv/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/rorolopetegui/Documents/Projects/Rsk/raidenOne/clientEnv/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/rorolopetegui/Documents/Projects/Rsk/raidenOne/clientEnv/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/rorolopetegui/Documents/Projects/Rsk/raidenOne/raiden/api/v1/resources.py", line 259, in get
    return self.rest_api.get_pending_transfers()
  File "/home/rorolopetegui/Documents/Projects/Rsk/raidenOne/raiden/api/rest.py", line 1394, in get_pending_transfers
    token_address=token_address, partner_address=partner_address
  File "/home/rorolopetegui/Documents/Projects/Rsk/raidenOne/raiden/api/python.py", line 1278, in get_pending_transfers
    return transfer_tasks_view(transfer_tasks, token_address, channel_id)
  File "/home/rorolopetegui/Documents/Projects/Rsk/raidenOne/raiden/api/python.py", line 153, in transfer_tasks_view
    transfer, role = get_transfer_from_task(secrethash, transfer_task)
  File "/home/rorolopetegui/Documents/Projects/Rsk/raidenOne/raiden/api/python.py", line 130, in get_transfer_from_task
    transfer = transfer_task.manager_state.initiator_transfers[secrethash].transfer
KeyError: b'\x02\xc1\xcb}Rz\x0b\x0b\xf7~\x93\xcbN\t\xfb\xbcb\xe2\xaf\xac\x0cm\xbd\x96\xee\xac\xa0\xda\xe3\x18\x91\xf3'
2020-02-25 19:05:50.526864 [info     ] 127.0.0.1 - - [2020-02-25 16:05:50] "GET /api/v1/pending_transfers HTTP/1.1" 500 161 1.003519 [raiden.api.rest.pywsgi] 
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/rorolopetegui/Documents/Projects/Rsk/raidenOne/raiden/api/rest.py", line 440, in _run
    self.wsgiserver.serve_forever()
  File "/home/rorolopetegui/Documents/Projects/Rsk/raidenOne/clientEnv/lib/python3.7/site-packages/gevent/baseserver.py", line 364, in serve_forever
    self._stop_event.wait()
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
KeyError: b'\x02\xc1\xcb}Rz\x0b\x0b\xf7~\x93\xcbN\t\xfb\xbcb\xe2\xaf\xac\x0cm\xbd\x96\xee\xac\xa0\xda\xe3\x18\x91\xf3'
2020-02-25T19:05:50Z <Greenlet "APIServer|Greenlet-3" at 0x7f31f8476048: <bound method APIServer._run of <raiden.api.rest.APIServer object at 0x7f31f8468cf8>>> failed with KeyError

FATAL: An unexpected exception occured. A traceback has been written to /tmp/raiden-exception-2020-02-25T19-0540hiwn0g.txt
b'\x02\xc1\xcb}Rz\x0b\x0b\xf7~\x93\xcbN\t\xfb\xbcb\xe2\xaf\xac\x0cm\xbd\x96\xee\xac\xa0\xda\xe3\x18\x91\xf3'

```

**Comment by palango** [comment] 2020-02-26 10:40
@rorolopetegui Thanks for the report. `0.200.0-rc2` is quite old. The issue you're seeing has already been reported here: https://github.com/raiden-network/raiden/issues/5480

It is fixed in the development version, so at the moment you're better of trying the development version. See https://raiden-network.readthedocs.io/en/latest/overview_and_guide.html#for-developers for some information.

I'm closing this as a duplicate of #5480, let us know when you run into any other problems!

**Closed by palango** 2020-02-26 10:40 UTC
