### ISSUE TITLE
BF1: AssertSumTask error

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5219] opened 2019-11-05 09:00 UTC
## Problem Definition

`{"json": {"errors": "Payment couldn't be completed because: there is no route available"}, "event": "Received response", "logger": "scenario_player.tasks.api_base", "level": "debug", "timestamp": "2019-11-05 04:12:14.505142"}`

Also assert sum failures

`{"task": "<AssertSumTask: {'from': 0, 'balance_sum': 1105000000000000000}>", "event": "Task errored", "logger": "scenario_player.tasks.base", "level": "error", "timestamp": "2019-11-05 05:42:12.027318", "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 74, in __call__\n    return self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 70, in _run\n    return self._process_response(response_dict)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/channels.py\", line 254, in _process_response\n    f'Expected sum value \"{assert_value}\" for channel fields \"{field}\". '\nscenario_player.exceptions.legacy.ScenarioAssertionError: Expected sum value \"1105000000000000000\" for channel fields \"balance\". Actual value: \"1106000000000000000\". Channels: [{'token_address': '0x62083c80353Df771426D209eF578619EE68D5C7A', 'partner_address': '0xD0660c58b9B1aaB52b7Ea96156756AA442082f14', 'total_deposit': 1000000000000000000, 'balance': 1106000000000000000, 'state': 'opened', 'channel_identifier': 1801, 'settle_timeout': 40, 'total_withdraw': 0, 'token_network_address': '0xDa1fBc048f503635950058953f5c60FC1F564ee6', 'reveal_timeout': 20}]"}`

[Scenario_player_Logs-bf1_basic_functionality-1-latest-2019-11-05.tar.gz](https://github.com/raiden-network/raiden/files/3808058/Scenario_player_Logs-bf1_basic_functionality-1-latest-2019-11-05.tar.gz)

**Comment by agatsoh** [comment] 2019-11-05 11:58
Closer inspection of the node logs
**MatrixRequestError** For nodes 0, 1 ,2 , 4
```
{"current_user": "@0xa26f98ef27077066cca77ca7ca601358f55bb739:transport02.raiden.network", "node": "0xa26F98EF27077066Cca77cA7cA601358F55bB739", "transport_uuid": "a1eb9a64-622e-474d-88e8-f8281420c2c9", "room_name": "#raiden_goerli_0x8ce96fd8241e28e075983f75e4c67d6663ed4216_0xa26f98ef27077066cca77ca7ca601358f55bb739:transport02.raiden.network", "error": "MatrixRequestError('404: {\"errcode\":\"M_NOT_FOUND\",\"error\":\"Room alias #raiden_goerli_0x8ce96fd8241e28e075983f75e4c67d6663ed4216_0xa26f98ef27077066cca77ca7ca601358f55bb739:transport02.raiden.network not found\"}')", "event": "No room for peer, trying to create", "logger": "raiden.network.transport.matrix.transport", "level": "debug", "greenlet_name": "RetryQueue node:0xa26F98EF27077066Cca77cA7cA601358F55bB739 recipient:0x8cE96fd8241E28e075983F75E4C67D6663ed4216", "timestamp": "2019-11-05 04:20:20.952394"}
```
**ServiceRequestIOURejected** for node 3
```
{"error": "ServiceRequestIOURejected('No route between nodes found. (2201)')", "event": "Pathfinding Service rejected IOU", "logger": "raiden.network.pathfinding", "level": "debug", "timestamp": "2019-11-05 04:12:14.398986"}
```

**Comment by rakanalh** [comment] 2019-11-06 09:16
@agatsoh:
```
{"json": {"errors": "Payment couldn't be completed because: there is no route available"}, "event": "Received response", "logger": "scenario_player.tasks.api_base", "level": "debug", "timestamp": "2019-11-05 04:12:14.505142"}
```
Could be because the first transfer intentionally triggers this. This is obvious to me because you reached the summation assert which means that subsequent transfers passed. 

```
{"current_user": "@0xa26f98ef27077066cca77ca7ca601358f55bb739:transport02.raiden.network", "node": "0xa26F98EF27077066Cca77cA7cA601358F55bB739", "transport_uuid": "a1eb9a64-622e-474d-88e8-f8281420c2c9", "room_name": "#raiden_goerli_0x8ce96fd8241e28e075983f75e4c67d6663ed4216_0xa26f98ef27077066cca77ca7ca601358f55bb739:transport02.raiden.network", "error": "MatrixRequestError('404: {\"errcode\":\"M_NOT_FOUND\",\"error\":\"Room alias #raiden_goerli_0x8ce96fd8241e28e075983f75e4c67d6663ed4216_0xa26f98ef27077066cca77ca7ca601358f55bb739:transport02.raiden.network not found\"}')", "event": "No room for peer, trying to create", "logger": "raiden.network.transport.matrix.transport", "level": "debug", "greenlet_name": "RetryQueue node:0xa26F98EF27077066Cca77cA7cA601358F55bB739 recipient:0x8cE96fd8241E28e075983F75E4C67D6663ed4216", "timestamp": "2019-11-05 04:20:20.952394"}
```

This is part of what the transport does to join / create a room and create it's alias on a specific server and is not considered a faulty behaviour (yet).

You're posting alot of stuff but none of them are useful unless you state at which point the scenario failed. You shouldn't post every failure you see in the logs because some of them, similar to the above might have been parts of an intentional failed assert.

Could you update the issue description on what exactly the issue is?

**Comment by agatsoh** [comment] 2019-11-06 11:06
@rakanalh 

Scenario in a nutshell
node 0 => `0x8cE96fd8241E28e075983F75E4C67D6663ed4216`
node 1 => `0xD0660c58b9B1aaB52b7Ea96156756AA442082f14`
node 2 => `0x78690120B063b234b7ed8540Afc3e948dd10B2ec`
node 3 => `0xB0F7eCB3DBC8474dF29e0501d576A25b71d8ED0e`
node 4 => `0xa26F98EF27077066Cca77cA7cA601358F55bB739`

The Scenario fails at this point 

<pre>
{
  "task": "<AssertSumTask: {'from': 0, 'balance_sum': 1105000000000000000}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "timestamp": "2019-11-05 05:42:12.027318",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 74, in __call__\n    return self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 70, in _run\n    return self._process_response(response_dict)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/channels.py\", line 254, in _process_response\n    f'Expected sum value \"{assert_value}\" for channel fields \"{field}\". '\nscenario_player.exceptions.legacy.ScenarioAssertionError: Expected sum value \"1105000000000000000\" for channel fields \"balance\". Actual value: \"1106000000000000000\". Channels: [{'token_address': '0x62083c80353Df771426D209eF578619EE68D5C7A', 'partner_address': '0xD0660c58b9B1aaB52b7Ea96156756AA442082f14', 'total_deposit': 1000000000000000000, 'balance': 1106000000000000000, 'state': 'opened', 'channel_identifier': 1801, 'settle_timeout': 40, 'total_withdraw': 0, 'token_network_address': '0xDa1fBc048f503635950058953f5c60FC1F564ee6', 'reveal_timeout': 20}]"
}
</pre>

What does the exception say:
1. It fails during "task": "<**AssertSumTask** : {'from': 0, 'balance_sum': 1105000000000000000}>

2. In the BF1 scenario this is line number 233
https://github.com/raiden-network/raiden/blob/develop/raiden/tests/scenarios/bf1_basic_functionality.yaml#L233

3. Expected sum value \"1105000000000000000\" for channel fields \"balance\". Actual value: \"1106000000000000000\"
which means: 
Asserted value is: `1_105_000_000_000_000_000`
Actual value is  : `1_106_000_000_000_000_000`

It also gives the actual state of the channel
<pre>

[
  {
    "token_address": "0x62083c80353Df771426D209eF578619EE68D5C7A",
    "partner_address": "0xD0660c58b9B1aaB52b7Ea96156756AA442082f14",
    "total_deposit": 1000000000000000000,
    "balance": <b>1106000000000000000</b>,
    "state": "opened",
    "channel_identifier": 1801,
    "settle_timeout": 40,
    "total_withdraw": 0,
    "token_network_address": "0xDa1fBc048f503635950058953f5c60FC1F564ee6",
    "reveal_timeout": 20
  }
]

</pre>

4. Which commit made the change to sum value `1_105_000_000_000_000_000` ?
https://github.com/raiden-network/raiden/commit/265ff6eb4208e7096db1ca64c50db7b6c0654d18#diff-44f346fb37486eb90221b76f3ce31a1e
This commit was made on 31st Oct 2019

5. Status of bf1_basic_functionality runs since the change was made 
SP runs for BF1 scenario from 31st Oct
31stOct    None(All Scenarios did not run)
2ndNov     Success
3rdNov     Fail
4thNov     Success
5thNov     Fail

6. Question to be analysed 
since the last change took place on 31st of Oct why is the scenario showing flaky behaviour.

**Comment by rakanalh** [comment] 2019-11-06 13:04
Thanks @agatsoh. Will look into it.

**Comment by LefterisJP** [comment] 2019-11-07 12:15
```
0 <-> 1 <-> 2 <-> 3
^                 ^
|                 |
v                 |
4<-----------------
```

The node addresses are:

[0] Alice   - 0x8cE96fd8241E28e075983F75E4C67D6663ed4216
[1] Bob     - 0xD0660c58b9B1aaB52b7Ea96156756AA442082f14
[2] Carol   - 0x78690120B063b234b7ed8540Afc3e948dd10B2ec
[3] Dan     - 0xB0F7eCB3DBC8474dF29e0501d576A25b71d8ED0e
[4] Erin    - 0xa26F98EF27077066Cca77cA7cA601358F55bB739


Hey @agatsoh I have a question. Is this from the SP nightly runs or is it something you run on your own?

If it is a scenario that you run on your own then how did you run it and are you 100% sure you did not change anything in the scenario?

The reason I am asking is that I am looking at the DB and logs and trying to understand where does the extra `1_000_000_000_000_000` comes in the balance of node 0. It's the exact amount of a single transfer.

And it happens while node 3 sends the 100 transfers to node 0. At that time I also see 1 transfer coming in from node 4.

```
< EventPaymentReceivedSuccess                    
        token_network_registry_address='0x62436bbadb629498107278486c2a367ffdfeb2f3'                                                                                                                                                                                              
        token_network_address='0xda1fbc048f503635950058953f5c60fc1f564ee6'
        identifier=14742463402259348632
        amount=1000000000000000
        initiator='[Dan]'
< EventUnlockClaimSuccess
        identifier=14742463402259348632
        secrethash='0x4cb8150bc2d4fd5cf1421698609520a319885584304862c05f43d30370e133c1'
```

That should not be possible according to the scenario's yaml for two reasons:

- Node 4 should have closed its channel beforehand so it should be out of the game.
- Node 4 initiates no transfers in the entire scenario.

**Comment by LefterisJP** [comment] 2019-11-07 12:17
I wrote a question beforehand but I misread an address mapping so it's invalid, thus I deleted it.

**Comment by LefterisJP** [comment] 2019-11-07 13:56
## Explanation

All right so I kind of figured it.

There is nothing wrong with the  transfer right before the assertion:

https://github.com/raiden-network/raiden/blob/e42e1175f5089ea0f9410615c5d4dae337c68e35/raiden/tests/scenarios/bf1_basic_functionality.yaml#L224-L228

All of the 100 transfers are made fine.

And also since the assertion before closing the channel passed we know all transfers succeeded:

https://github.com/raiden-network/raiden/blob/e42e1175f5089ea0f9410615c5d4dae337c68e35/raiden/tests/scenarios/bf1_basic_functionality.yaml#L202-L207

What we don't know is which path they took ...

The sum of balances of `channel-0-1` before 100 transfers from 3 -> 0:
`1105000000000000000-100000000000000000 = 1005000000000000000`

So balance of `channel-0-4` should have been

`1895000000000000000 - 1005000000000000000 = 890000000000000000`

But according to the balance checks while looking at the DB channel 0-4 has a balance of `889000000000000000` before closing.

So there is the problem. One of the transfers with node 0 as its target took a different path than expected.

That can be confirmed when looking at the unlocks/secret reveals of the two channels of node 0:

For `channel-0-4` we seem to have `9` `ReceiveUnlock`, so `9` transfers passed from us in the direction `4->0` and `120` `ReceiveSecretReveal` so `120` transfers passed from us in the direction `0->4`

For `channel-0-1` we seem to have `111` ReceiveUnlock, so `111` transfers passed from us in the direction `1->0` and `5` `ReceiveSecretReveal` so `5` transfers passed from us in the direction `0->1`

The number 9 does not match the addition of any of the sending tasks, and neither does 111 so some transfer task used two different paths.

Now you may ask why do we care which path any of the transfers took? They succeeded so it should be fine.

The `channel-0-4` is closed and settled here:

https://github.com/raiden-network/raiden/blob/e42e1175f5089ea0f9410615c5d4dae337c68e35/raiden/tests/scenarios/bf1_basic_functionality.yaml#L208-L223

## Conclusion and TL;DR

**Since the scenario closes/settles a channel that channel's balance is taken out of the calculation.  From that point on we need to be thinking on channel and not node balances and as such can't afford to not know which patch a transfer took**

## How to address this?

Possible solutions:

-  Do not close and settle a channel in BF1 so we still care only about node balance sums and not per channel balances
- Somehow make the paths deterministic and assert on channel balances and not node sum balances

**Comment by Dominik1999** [comment] 2019-11-07 14:06
nice analysis @czepluch or @christianbrb can you take over and address Lefteris' findings in the scenario somehow?

**Comment by czepluch** [comment] 2019-11-12 11:34
I'd suggest to just move the close and settle of the channel [0, 4] to after the last balance assert. Currently I am just struggling to run scenarios locally, so can't verify that it still works this way.

**Closed** 2019-11-14 15:03 UTC
Labels: Component / Scenario Player, Severity / Medium, State / Needs more info, Type / Bug
