### ISSUE TITLE
Find a way to reproduce our bugs more reliable and efficient - Solution 1: Run scenarios in parallel

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#5417] opened 2019-12-02 13:44 UTC
## The scenario player is too inefficient and unreliable for reproducing bugs

Our last three major bug categories - presence bug, performance issues, general "No route found", we found by running scenarios on the scenario player. However, it is hard to reproduce any bugs and test bug fixes with the current scenario player setup. Running scenarios is simply too and complex slow to be used as a tool for bug fixing.

## Possible solution 1 to that problem
Run scenarios in parallel. We need to find out how that works. 
Keep in mind: @nlsdfnbch has got a branch in the scenario player which runs the scenarios in parallel. Testing had started, but we’ve been still finding issues and therefore where holding it back

**Comment by rakanalh** [comment] 2019-12-03 09:13
I tried running 2 scenarios in parallel **using 2 different funding accounts** (passed with `--keystore-file`) as such:

```
~/.pyenv/versions/scenario-player/bin/scenario_player run --service-port=6000 --chain=goerli:http://parity.goerli.ethnodes.brainbot.com:8545 --keystore-file=/home/rakan/.ethereum/testnet/keystore/UTC--2018-07-17T10-41-46.341359860Z--6d1ae2fa14078b5dbc46501bcc0623c67aa7b5cf raiden/tests/scenarios/pfs1_get_a_simple_path.yaml
```

```
~/.pyenv/versions/scenario-player/bin/scenario_player run --chain=goerli:http://parity.goerli.ethnodes.brainbot.com:8545 --keystore-file=/home/rakan/.ethereum/keystore/UTC--2018-10-25T13-50-01.085338680Z--4252ccc23552bf3d3eedfab8e286815831479bda raiden/tests/scenarios/pfs1_get_a_simple_path.yaml
```

Initially, i saw an exception:
```
2019-12-02 14:12:29.184384 [info     ] Scenario Player version:       [scenario_player.main] version_info={'raiden': '0.100.5a1.dev926+gb08e2de08', 'raiden_db_version': 23, 'python_implementation': 'CPython', 'python_version': '3.7.0', 'system': 'Linux 64bit_ELF 5.3.12-arch1-1', 'architecture': 'x86_64', 'distribution': 'source', 'scenario_player': '0.6.5', 'raiden-contracts': '0.33.0'}
Please enter your password: :
2019-12-02 14:12:34.564288 [info     ] Using account                  [scenario_player.main] account=0x6D1aE2fA14078B5Dbc46501Bcc0623C67aA7b5cF
Process ServiceProcess-1:
Traceback (most recent call last):
  File "/home/rakan/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/rakan/.pyenv/versions/3.7.0/envs/scenario-player/lib/python3.7/site-packages/scenario_player/services/common/app.py", line 96, in run
    waitress.serve(app, host=self.host, port=self.port)
  File "/home/rakan/.pyenv/versions/3.7.0/envs/scenario-player/lib/python3.7/site-packages/waitress/__init__.py", line 11, in serve
    server = _server(app, **kw)
  File "/home/rakan/.pyenv/versions/3.7.0/envs/scenario-player/lib/python3.7/site-packages/waitress/server.py", line 85, in create_server
    sockinfo=sockinfo)
  File "/home/rakan/.pyenv/versions/3.7.0/envs/scenario-player/lib/python3.7/site-packages/waitress/server.py", line 229, in __init__
    self.bind_server_socket()
  File "/home/rakan/.pyenv/versions/3.7.0/envs/scenario-player/lib/python3.7/site-packages/waitress/server.py", line 360, in bind_server_socket
    self.bind(sockaddr)
  File "/home/rakan/.pyenv/versions/3.7.0/envs/scenario-player/lib/python3.7/site-packages/waitress/wasyncore.py", line 369, in bind
    return self.socket.bind(addr)
OSError: [Errno 98] Address already in use
```

But that got ignored somehow and the SP continued to run as intended where the scenario succeeded.

That exception seems to happen because the SP starts an http server on port 5000 for "spaas" (SP as a service) so multiple SPs would race towards using that port number.

https://github.com/raiden-network/scenario-player/blob/d0a5b925baf607f1f84b0735bd8afbb5ed33fa92/scenario_player/utils/configuration/spaas.py#L24-L29 

Apparently, this can be added to the scenario to prevent the exception

**Comment by rakanalh** [comment] 2019-12-03 09:14
I have a pending PR: https://github.com/raiden-network/scenario-player/pull/437

That could help with this if it gets accepted.

**Comment by rakanalh** [comment] 2019-12-03 09:36
Closing.

**Closed by rakanalh** 2019-12-03 09:36 UTC
Labels: Flag / Testing, Type / Enhancement

**Comment by Dominik1999** [comment] 2019-12-03 09:39
Can you also run 3 and 4 in parallel now?

**Comment by rakanalh** [comment] 2019-12-03 10:15
Using different funding accounts, yes!
