### ISSUE TITLE
Failing to start raiden node with clean setup

### ISSUE THREAD

**Issue by durkmurder** [raiden-network/raiden#6070] opened 2020-04-15 14:07 UTC
## Problem Definition

Starting from `raiden-v0.200.0-rc3-linux-x86_64` I can't start raiden daemon. I get next error:
```
FATAL: An unexpected exception occurred. A traceback has been written to /tmp/raiden-exception-2020-04-15T11-38owwyrvby.txt
[TokenNetworkRegistry]Address 0x3DE1B1E10Ae71C3E3b793e545A047d1B4FAB587a has wrong code.. Please update your Raiden installation.
ReturnCode.FATAL
```
I am starting raiden node in next way:
```
./raiden-v0.200.0-rc3-linux-x86_64 --keystore-path path-to-keystore --eth-rpc-endpoint https://ropsten.infura.io/v3/INFURA_ID --network-id ropsten --datadir raiden-data-dir --accept-disclaimer --gas-price fast --environment-type development --routing-mode private --api-address 127.0.0.1:5001 --resolver-endpoint https://127.0.0.1:6001
```

Same issue happens with rc4 and rc5, but rc2 works ok.

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Raiden version:
{
  "raiden": "0.200.0rc3",
  "raiden_db_version": 26,
  "python_implementation": "CPython",
  "python_version": "3.7.6",
  "system": "Linux 64bit_ELF 5.3.0-46-generic",
  "architecture": "x86_64",
  "distribution": "bundled"
}
```

**Comment by czepluch** [comment] 2020-04-16 10:19
We are looking into this. In the mean time, you can try it out with `goerli`. That should work.

**Comment by palango** [comment] 2020-05-04 08:29
Hi @durkmurder  We might have fixed that problem. Can you retry with the latest RC again and let us know if it works now?

**Comment by palango** [comment] 2020-05-11 11:16
Closing as we need more infos to continue with this. Please reopen if you still have these issues.

**Comment by durkmurder** [comment] 2020-05-11 13:16
Hey, sorry for taking so long. I have tried rc8 and I am getting a new error:
```
FATAL: An unexpected exception occurred. A traceback has been written to /tmp/raiden-exception-2020-05-11T13-15iwuvlbji.txt
[TokenNetworkRegistry]Address 0x3DE1B1E10Ae71C3E3b793e545A047d1B4FAB587a has wrong code.. Please update your Raiden installation.
```

Traceback:

```
Traceback (most recent call last):
  File "raiden/ui/startup.py", line 279, in raiden_bundle_from_contracts_deployment
  File "raiden/network/proxies/proxy_manager.py", line 174, in token_network_registry
  File "raiden/network/proxies/token_network_registry.py", line 68, in __init__
  File "raiden/network/rpc/client.py", line 368, in check_address_has_code_handle_pruned_block
  File "raiden/network/rpc/client.py", line 350, in check_address_has_code
raiden.exceptions.ContractCodeMismatch: [TokenNetworkRegistry]Address 0x3DE1B1E10Ae71C3E3b793e545A047d1B4FAB587a has wrong code.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "raiden/ui/cli.py", line 610, in run
  File "raiden/ui/runners.py", line 21, in run_services
  File "raiden/ui/app.py", line 349, in run_app
  File "raiden/ui/startup.py", line 281, in raiden_bundle_from_contracts_deployment
  File "raiden/ui/startup.py", line 168, in handle_contract_code_mismatch
raiden.exceptions.RaidenError: [TokenNetworkRegistry]Address 0x3DE1B1E10Ae71C3E3b793e545A047d1B4FAB587a has wrong code.. Please update your Raiden installation.
```

**Comment by palango** [comment] 2020-05-11 14:44
@durkmurder Can you please tell me what version or binary you used to run this and the command you used to start?

There's also a log file that would help if you attach it.

**Comment by durkmurder** [comment] 2020-05-11 18:21
`./raiden-v0.200.0-rc8-linux-x86_64 --keystore-path keystore-path --eth-rpc-endpoint https://ropsten.infura.io/v3/INFURA_ID --network-id ropsten --datadir datadir-path --accept-disclaimer --gas-price fast --environment-type development --routing-mode private --api-address 127.0.0.1:5001 --resolver-endpoint https://127.0.0.1:6001`

No logs, datadir is empty after launching, whatever was in console I have already attached.

**Comment by palango** [comment] 2020-05-12 09:14
@durkmurder Thanks for the infos, I can reproduce this with your latest command.

This happens because we accidentally didn't deploy the most recent contracts on ropsten. Is there any special reason why you want to use ropsten? Otherwise it works fine on goerli.

**Comment by durkmurder** [comment] 2020-05-13 07:21
@palango Ropsten is my default choice, I didn't find any info that it's broken for raiden so naturally I have expected that it would work. I can try goerli. My opinion is that it has to work everywhere or it has to be written somewhere that only selected networks are supported.

**Comment by palango** [comment] 2020-05-13 08:05
> Ropsten is my default choice, I didn't find any info that it's broken for raiden so naturally I have expected that it would work.

I totally agree, I would have expected the same. I created https://github.com/raiden-network/raiden-contracts/issues/1384 to track the missing contracts. 

However we're working on mainnet tests, so this doesn't have high priority right now. Görli is a safe bet now.

**Closed by palango** 2020-05-13 08:05 UTC
Labels: State / Investigating
