### ISSUE TITLE
Support closing the NettingChannel without requiring a transfer

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#172] opened 2016-10-19 10:48 UTC
To close the channel a participant is required to make a transfer, there are only two methods available for closing the smart contract, [`closeSingleTransfer`](https://github.com/raiden-network/raiden/blob/a9f79acc1a8e8874badd9e5ebf709c2360844936/raiden/smart_contracts/NettingChannelContract.sol#L58) and [`close`](https://github.com/raiden-network/raiden/blob/a9f79acc1a8e8874badd9e5ebf709c2360844936/raiden/smart_contracts/NettingChannelContract.sol#L63), the first require one transfer from either party and the later a transfer from each.
- [ ] Implement a close function that doesnt required a transfer for either participant.

**Comment by czepluch** [comment] 2016-10-19 16:29
This seems like a duplicate of https://github.com/raiden-network/raiden/issues/157

**Comment by czepluch** [comment] 2016-10-19 16:31
Oh, just looked at #24 , guess that one explains the problem indeed.

**Comment by LefterisJP** [comment] 2016-12-11 14:29
closed by #276

**Closed by LefterisJP** 2016-12-11 14:29 UTC
Labels: low_hanging_fruit, mvp_protocol
