### ISSUE TITLE
Fix `test_echo_node_lottery` test

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3750] opened 2019-04-04 17:06 UTC
## Problem Definition

It seems that the following tests are flaky/failing often on Circle and sometimes even locally on master.

`raiden/tests/integration/test_echo_node.py::test_event_transfer_received_success`
`raiden/tests/integration/test_echo_node.py::test_echo_node_response`

Update: `raiden/tests/integration/test_echo_node.py::test_echo_node_response()` also times out locally in master at the following position:

```
    @pytest.mark.parametrize('number_of_nodes', [4])
    @pytest.mark.parametrize('number_of_tokens', [1])
    @pytest.mark.parametrize('channels_per_node', [CHAIN])
    @pytest.mark.parametrize('reveal_timeout', [15])
    @pytest.mark.parametrize('settle_timeout', [120])
    def test_echo_node_response(token_addresses, raiden_chain, network_wait):
        app0, app1, app2, echo_app = raiden_chain
        address_to_app = {app.raiden.address: app for app in raiden_chain}
        token_address = token_addresses[0]
        echo_api = RaidenAPI(echo_app.raiden)
    
        echo_node = EchoNode(echo_api, token_address)
        echo_node.ready.wait(timeout=30)
        assert echo_node.ready.is_set()
        expected = list()
    
        # Create some transfers
        for num, app in enumerate([app0, app1, app2]):
            amount = 1 + num
            payment_status = RaidenAPI(app.raiden).transfer_async(
                app.raiden.default_registry.address,
                token_address,
                amount,
                echo_app.raiden.address,
                10 ** (num + 1),
            )
            payment_status.payment_done.wait(timeout=20)
            expected.append(amount)
    
        while echo_node.num_handled_transfers < len(expected):
>           gevent.sleep(.5)

raiden/tests/integration/test_echo_node.py:99:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../.virtualenvs/raiden/lib/python3.7/site-packages/gevent/hub.py:159: in sleep
    hub.wait(t)
src/gevent/_hub_primitives.py:46: in gevent.__hub_primitives.WaitOperationsGreenlet.wait
    ???
src/gevent/_hub_primitives.py:55: in gevent.__hub_primitives.WaitOperationsGreenlet.wait
    ???
src/gevent/_waiter.py:151: in gevent.__waiter.Waiter.get
    ???
src/gevent/_greenlet_primitives.py:59: in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
    ???
src/gevent/_greenlet_primitives.py:59: in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
    ???
src/gevent/_greenlet_primitives.py:63: in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   Failed: Timeout >540.0s
```

**Comment by LefterisJP** [comment] 2019-04-09 14:10
So I spent some time debugging this error. At the moment it looks like a deadlock in the matrix transport to me and I have pinned it down to a general area but posting my findings so far here in order to see if anyone from the transport team can help.

I ran the test  with the following command:

`pytest  -xs raiden/tests/integration/test_echo_node.py::test_event_transfer_received_success --log-config="raiden:DEBUG" --log-file /tmp/LOG.txt `

The logs from a failing run can be seen [here](https://gist.github.com/LefterisJP/911dfa9422f400e97e8d062132db3621).

It contains some additional debugging information put by me to detect where the deadlock is happening:

```diff
diff --git a/raiden/network/transport/matrix/transport.py b/raiden/network/transport/matrix/transport.py
index 660bbc9dd..97e2d2e54 100644
--- a/raiden/network/transport/matrix/transport.py
+++ b/raiden/network/transport/matrix/transport.py
@@ -142,7 +142,19 @@ class _RetryQueue(Runnable):
     def enqueue(self, queue_identifier: QueueIdentifier, message: Message):
         """ Enqueue a message to be sent, and notify main loop """
         assert queue_identifier.recipient == self.receiver
+        log.debug(
+            '--> About to enqueue message',
+            message=message,
+            node=pex(self.transport._raiden_service.address),
+            receiver=pex(self.receiver),
+        )
         with self._lock:
+            log.debug(
+                '--> Acquired lock to enqueue message',
+                message=message,
+                node=pex(self.transport._raiden_service.address),
+                receiver=pex(self.receiver),
+            )
             already_queued = any(
                 queue_identifier == data.queue_identifier and message == data.message
                 for data in self._message_queue
@@ -150,6 +162,7 @@ class _RetryQueue(Runnable):
             if already_queued:
                 self.log.warning(
                     'Message already in queue - ignoring',
+                    node=pex(self.transport._raiden_service.address),
                     receiver=pex(self.receiver),
                     queue=queue_identifier,
                     message=message,
@@ -167,6 +180,12 @@ class _RetryQueue(Runnable):
                 text=json.dumps(message.to_dict()),
                 expiration_generator=expiration_generator,
             ))
+        log.debug(
+            '--> Enqueue succesfull',
+            message=message,
+            node=pex(self.transport._raiden_service.address),
+            receiver=pex(self.receiver),
+        )
         self.notify()
 
     def enqueue_global(self, message: Message):
@@ -181,8 +200,18 @@ class _RetryQueue(Runnable):
 
     def notify(self):
         """ Notify main loop to check if anything needs to be sent """
+        log.debug(
+            '--> About to notify main loop',
+            node=pex(self.transport._raiden_service.address),
+            receiver=pex(self.receiver),
+        )
         with self._lock:
             self._notify_event.set()
+        log.debug(
+            '--> Notified main loop',
+            node=pex(self.transport._raiden_service.address),
+            receiver=pex(self.receiver),
+        )
 
     def _check_and_send(self):
         """Check and send all pending/queued messages that are not waiting on retry timeout
@@ -269,10 +298,26 @@ class _RetryQueue(Runnable):
         # run while transport parent is running
         while not self.transport._stop_event.ready():
             # once entered the critical section, block any other enqueue or notify attempt
+            log.debug(
+                '--> About to acquire lock at end of _run()',
+                node=pex(self.transport._raiden_service.address),
+                receiver=pex(self.receiver),
+            )
             with self._lock:
+                log.debug(
+                    '--> Acquired lock at end of _run()',
+                    node=pex(self.transport._raiden_service.address),
+                    receiver=pex(self.receiver),
+                )
                 self._notify_event.clear()
                 if self._message_queue:
                     self._check_and_send()
+
+            log.debug(
+                '--> Out of critical section at end of _run()',
+                node=pex(self.transport._raiden_service.address),
+                receiver=pex(self.receiver),
+            )
             # wait up to retry_interval (or to be notified) before checking again
             self._notify_event.wait(self.transport._config['retry_interval'])
 
diff --git a/raiden/tests/integration/test_echo_node.py b/raiden/tests/integration/test_echo_node.py
index bd206af67..587a6d580 100644
--- a/raiden/tests/integration/test_echo_node.py
+++ b/raiden/tests/integration/test_echo_node.py
@@ -17,7 +17,6 @@ from raiden.utils.echo_node import EchoNode
 @pytest.mark.parametrize('channels_per_node', [CHAIN])
 @pytest.mark.parametrize('reveal_timeout', [15])
 @pytest.mark.parametrize('settle_timeout', [120])
-@pytest.mark.skip('Issue: 3750')
 def test_event_transfer_received_success(
         token_addresses,
         raiden_chain,
@@ -53,7 +52,7 @@ def test_event_transfer_received_success(
         )
 
     for wait, sender, amount in wait_for:
-        wait.wait()
+        wait.wait(timeout=60.0)
         assert search_for_item(
             target_app.raiden.wal.storage.get_events(),
             EventPaymentReceivedSuccess,
```

So it seems that node `608de4ea` receives message from `76c32df2` with ID `10864362826422455865` and never manages to get to process it. It's stuck waiting for `self._lock` of the retry queue.
The log entry that shows the waiting on the lock is this:

```
2019-04-09 10:26:45.705871 [debug    ] --> About to enqueue message   [raiden.network.transport.matrix.transport] greenlet_name=GMatrixClient._sync user_id:@0x608de4ea2de09fd0caef8f9502a69e2453ccd1c6:localhost:8500 sync_token:s66_5_0_1_7_1_1_5_1 message=<Delivered [delivered_msgid:10864362826422455865]> node=608de4ea receiver=76c32df2
```
and the point in the code where the lock waiting happens is [here](https://github.com/raiden-network/raiden/blob/619a014f4c7e804ea401607881b6af7834290d2e/raiden/network/transport/matrix/transport.py#L145).

Looking back in the logs the last place where the lock is successfully acquired is:

```
2019-04-09 10:26:45.639516 [debug    ] --> Acquired lock at end of _run() [raiden.network.transport.matrix.transport] greenlet_name=RetryQueue node:608de4ea recipient:76c32df2 node=608de4ea receiver=76c32df2
```

So it's essentially getting in [this](https://github.com/raiden-network/raiden/blob/619a014f4c7e804ea401607881b6af7834290d2e/raiden/network/transport/matrix/transport.py#L272) area protected by `self._lock` and never gets outs which is what is causing the deadlock later down the line.

https://github.com/raiden-network/raiden/blob/619a014f4c7e804ea401607881b6af7834290d2e/raiden/network/transport/matrix/transport.py#L271-L277


More specifically as to why it does not get out of the protected area, still from the logs:

```
2019-04-09 10:26:45.639932 [debug    ] Retrying message               [raiden.network.transport.matrix.transport] current_user=@0x608de4ea2de09fd0caef8f9502a69e2453ccd1c6:localhost:8500 greenlet_name=RetryQueue node:608de4ea recipient:76c32df2 node=608de4ea receiver=0x76c32df2b4a27ebf2f7429c13578fa91ba4199dd
2019-04-09 10:26:45.640233 [debug    ] Send                           [raiden.network.transport.matrix.transport] current_user=@0x608de4ea2de09fd0caef8f9502a69e2453ccd1c6:localhost:8500 greenlet_name=RetryQueue node:608de4ea recipient:76c32df2 messages=['{"type": "Delivered", "delivered_message_identifier": 15509967386392572634, "signature": "0x97dc4baee467872a62c53bed3a1559048ecd6909c0d32b86c601ee3ecc13768b22f3f1f6a69f7cdd9bfec9c5d0f021253daee33149d2ee420302151fedec4a3f1c"}'] node=608de4ea receiver=76c32df2
2019-04-09 10:26:45.645220 [debug    ] matrix get account data        [raiden.network.transport.matrix.transport] current_user=@0x76c32df2b4a27ebf2f7429c13578fa91ba4199dd:localhost:8500 for_address=0x608DE4Ea2DE09fd0caEF8F9502a69E2453CCd1c6 greenlet_name=GMatrixClient._sync user_id:@0x76c32df2b4a27ebf2f7429c13578fa91ba4199dd:localhost:8500 sync_token:s74_5_0_1_7_1_1_5_1 node=76c32df2 room_ids=['!qUGHibmYjptgWfTgsA:localhost:8500']
2019-04-09 10:26:45.645919 [debug    ] Incoming messages              [raiden.network.transport.matrix.transport] current_user=@0x76c32df2b4a27ebf2f7429c13578fa91ba4199dd:localhost:8500 greenlet_name=GMatrixClient._sync user_id:@0x76c32df2b4a27ebf2f7429c13578fa91ba4199dd:localhost:8500 sync_token:s74_5_0_1_7_1_1_5_1 messages=[<Processed [msgid:3176360227660723458]>] node=76c32df2 room=<Room id='!qUGHibmYjptgWfTgsA:localhost:8500' alias='#raiden_337_0x608de4ea2de09fd0caef8f9502a69e2453ccd1c6_0x76c32df2b4a27ebf2f7429c13578fa91ba4199dd:localhost:8500'> sender=608de4ea sender_user=<User id='@0x608de4ea2de09fd0caef8f9502a69e2453ccd1c6:localhost:8500'>
2019-04-09 10:26:45.646272 [debug    ] Message received               [raiden.network.transport.matrix.transport] current_user=@0x76c32df2b4a27ebf2f7429c13578fa91ba4199dd:localhost:8500 greenlet_name=GMatrixClient._sync user_id:@0x76c32df2b4a27ebf2f7429c13578fa91ba4199dd:localhost:8500 sync_token:s74_5_0_1_7_1_1_5_1 message=<Processed [msgid:3176360227660723458]> node=76c32df2 sender=608de4ea
2019-04-09 10:26:45.646863 [debug    ] --> About to enqueue message   [raiden.network.transport.matrix.transport] greenlet_name=GMatrixClient._sync user_id:@0x76c32df2b4a27ebf2f7429c13578fa91ba4199dd:localhost:8500 sync_token:s74_5_0_1_7_1_1_5_1 message=<Delivered [delivered_msgid:3176360227660723458]> node=76c32df2 receiver=608de4ea
2019-04-09 10:26:45.647161 [debug    ] --> Acquired lock to enqueue message [raiden.network.transport.matrix.transport] greenlet_name=GMatrixClient._sync user_id:@0x76c32df2b4a27ebf2f7429c13578fa91ba4199dd:localhost:8500 sync_token:s74_5_0_1_7_1_1_5_1 message=<Delivered [delivered_msgid:3176360227660723458]> node=76c32df2 receiver=608de4ea
2019-04-09 10:26:45.647473 [debug    ] --> Enqueue succesfull         [raiden.network.transport.matrix.transport] greenlet_name=GMatrixClient._sync user_id:@0x76c32df2b4a27ebf2f7429c13578fa91ba4199dd:localhost:8500 sync_token:s74_5_0_1_7_1_1_5_1 message=<Delivered [delivered_msgid:3176360227660723458]> node=76c32df2 receiver=608de4ea
2019-04-09 10:26:45.647756 [debug    ] --> About to notify main loop  [raiden.network.transport.matrix.transport] greenlet_name=GMatrixClient._sync user_id:@0x76c32df2b4a27ebf2f7429c13578fa91ba4199dd:localhost:8500 sync_token:s74_5_0_1_7_1_1_5_1 node=76c32df2 receiver=608de4ea
2019-04-09 10:26:45.648014 [debug    ] --> Notified main loop         [raiden.network.transport.matrix.transport] greenlet_name=GMatrixClient._sync user_id:@0x76c32df2b4a27ebf2f7429c13578fa91ba4199dd:localhost:8500 sync_token:s74_5_0_1_7_1_1_5_1 node=76c32df2 receiver=608de4ea
```

We can see that while retrying it's doing a `Send` but not a `Send raw`. Which means that in the following code it never manages to get a room id probably:

https://github.com/raiden-network/raiden/blob/619a014f4c7e804ea401607881b6af7834290d2e/raiden/network/transport/matrix/transport.py#L973-L988

Now going even deeper there are other locks involved. The `self._getroom_lock` and `self._account_data_lock` any of which could be the cause. I will continue looking but I think that at this point it's probably a transport issue and the solution may be obvious to someone who knows the transport code well enough so I would like to ask for some feedback so that I don't waste more time on this than is necessary.

@ulope @andrevmatos @err508 ^

**Comment by hackaugusto** [comment] 2019-04-18 13:30
@LefterisJP have you tried printing the stack traces of all greenlets?

[it is enabled by default](https://github.com/raiden-network/raiden/blob/ad8ae3c976090b6437ea43a477ff3234b0fab90a/raiden/tests/conftest.py#L61-L74), you can use by running `kill -s USR1 $(pgrep pytest)`. This is the tool we used to find a deadlock with the token network proxies (fixed by d2b9bfdc4c82747ffae8f3cb5a929bc1d4adce3f)

**Comment by LefterisJP** [comment] 2019-04-23 21:39
@hackaugusto no I have not had the time to try this, no

@ulope @andrevmatos since I have heard nothing from you yet on this I am pinging you again.

I am also un-assigning myself from this as I will be on vacation and hopefully this will get solved before I am back.

**Comment by palango** [comment] 2019-07-19 11:21
@ulope Lefteris' comments above indicate that this might be caused by matrix problems. Do you think this might be fixed by the PR you're working on as well?

**Comment by palango** [comment] 2019-07-25 08:02
`test_echo_node_lottery` is still flaky:
https://circleci.com/gh/raiden-network/raiden/66176#tests/containers/16

**Comment by karlb** [comment] 2019-08-01 08:17
Still flaky: https://circleci.com/gh/raiden-network/raiden/68509#tests/containers/16

**Comment by palango** [comment] 2019-08-01 08:18
Nooooooo 😱

**Comment by palango** [comment] 2019-08-01 08:35
The latest failure is a simple timed out transfer:
```
RuntimeError: Transfer 600 from 0xB557Bc3812de7582EF3CDBc18f4De7357390a1f4 to 0x5AF8dD910BFD50648AA281EB080630d3924e679f timed out after 10
```

**Comment by palango** [comment] 2019-08-09 14:24
Still happens: #4567

**Comment by hackaugusto** [comment] 2019-08-12 09:28
`test_echo_node_lottery` is also flaky https://circleci.com/gh/raiden-network/raiden/70595#tests/containers/17

**Comment by jomuel** [comment] 2019-12-12 15:58
Closing this issue for now. We plan to take the echo node out of the client code and move it to an own repo, see issue #4588. Until that is done, it makes no sense to fix the test.

**Closed by jomuel** 2019-12-12 15:58 UTC
Labels: Flag / Testing
