### ISSUE TITLE
Add dataclasses (related to "Spring Cleaning")

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#3869] opened 2019-04-18 14:33 UTC
## Abstract

Convert state / state changes / events to dataclasses to be able to get rid of all the boilerplate code we have right now that deals with equality and json encoding / decoding

**Comment by LefterisJP** [comment] 2019-04-18 21:38
Blindly replacing NamedTuples with Dataclasses is not a good approach. We should use data classes for whenever mutability is not a problem and frozen data classes if we want immutable objects that need to utilize inheritance or objects that have a lot of logic attached to them.

For simple objects (i.e. for giving a name to a return value) a good old `typing.NamedTuple` is perfect. Also named tuples are probably a bit more performant .

Sources:
- https://stackoverflow.com/questions/47955263/what-are-data-classes-and-how-are-they-different-from-common-classes
- https://realpython.com/python-data-classes/

**Comment by rakanalh** [comment] 2019-04-23 21:17
Duplicate of #3253

**Comment by rakanalh** [comment] 2019-04-23 21:17
Actually, this is not a duplicate as the other one refers to messages.

**Closed** 2019-05-17 13:38 UTC
Labels: enhancement
