### ISSUE TITLE
Ethereum nonce mismatches with low ETH balance and Geth <= 1.9.1

### ISSUE THREAD

**Issue by jomuel** [raiden-network/raiden#5181] opened 2019-10-30 17:02 UTC
This is a follow-up issue to #5048.

After the main issue has been fixed in PR #5124, the question remains why the nonce mismatches (`"Invalid LockedTransfer message. Nonce did not change sequentially, expected: 7 got: 3."`) in the log of #5048 happened.

As @LefterisJP noticed, these nonce mismatches also happen in the new integration test (`long_running/test_settlement.py::test_handle_insufficient_eth`) when it is run with Geth 1.9.1, but no longer with Geth 1.9.2. So the key to reproducing it seems to be low eth balance and Geth 1.9.1 or older.

**Comment by LefterisJP** [comment] 2019-11-01 12:45
@jomuel You wrote the `test_handle_insufficient_eth` test.

I tried running the latest develop version of that test with geth 1.9.1, 1.9.2 and 1.9.6 and I don't get any:

> "Invalid LockedTransfer message. Nonce did not change sequentially, expected: 7 got: 3."

Do you remember when I told you that and in what situation the test was in? I would like to reproduce this to understand what happened.

Checking the previous PR: https://github.com/raiden-network/raiden/pull/5124/ it seems you changed the test during the PR review and since then it's not reproducible. Since it never got merged I can't find what the test was doing. Can you maybe help and give me the older version of the test?

**Comment by LefterisJP** [comment] 2019-11-04 15:38
I was told by Jochen that the previous version of the test had a withdraw by `app1`, right after the eth is burned and `app1.raiden` restarted

I tried this with geth v1.9.1 and I still saw no nonce mismatch.

I am closing this issue as not reproducible. If this pops up again we can reopen.

**Closed by LefterisJP** 2019-11-04 15:38 UTC
Labels: EthClient / Geth, Severity / Minor, Type / Bug
