### ISSUE TITLE
stun nat punching invalid  a few minitues later

### ISSUE THREAD

**Issue by nkbai** [raiden-network/raiden#1183] opened 2017-12-12 09:10 UTC
if a node start with stun nat punching, and it doesn't communicate with other node.
the nat punching will be invalid.

it needs a keep alive method to keep this nat punching work.

**Comment by ulope** [comment] 2018-01-05 02:14
This is likely related to / possibly one specific cause of #1133

**Comment by hackaugusto** [comment] 2018-01-05 03:46
Raiden does have a health check mechanism that is responsible to keep the router's mapping alive.

With the [current default settings](https://github.com/raiden-network/raiden/blob/ca2564bb7043c345ab44325dce5b3a3b0906f51f/raiden/settings.py#L26-L28) a ping message is sent every 5 seconds to online nodes, *or* every 15 seconds to offline nodes. These messages are responsible to keep the UDP mapping alive.

As @ulope pointed out, this issue is a duplicate of #1133 , so I'm closing this one. @nkbai if you have any input on why the current defaults are not working for you, please use that issue. If you want, the following tool can give some details on your router settings (requires java in the browser):

http://nattest.net.in.tum.de/

**Closed by hackaugusto** 2018-01-05 03:46 UTC
