### ISSUE TITLE
Parallelize the scenario execution

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#5796] opened 2020-01-31 09:16 UTC
Depends on what Nils has already done [SP 8]

**Comment by Dominik1999** [comment] 2020-02-03 13:05
So we will have parallel runs with our new Ansible setup. This setup is currently being implemented by @nlsdfnbch 

We won't have parallel runs with the current SP setup. 

We will keep that issue on the board to track progress. Maybe @nlsdfnbch can you add your status here?

**Comment by nlsdfnbch** [comment] 2020-02-03 13:51
Sorry for the delay, here's the requested status update:

- User stories regarding regression are all implemented
- A Debug container, including the environment and the logs for a scenario run, are uploaded to hub.docker.com
- Logs are also compressed and uploaded to a digitalocean space, here: https://scenario-player-nightlies.fra1.digitaloceanspaces.com/index.html
- The execution of scenarios happens using separate keystores and droplets, concurrently.

See https://github.com/raiden-network/team/issues/708 for further details on what is included in the setup.

What's left to do:
- Fix the container execution sequence - this currently always fails, despite the setup being nigh identical to the one on the static instances. It is likely a configuration error on my end. I will investigate with the help of @czepluch and/or @agatsoh , as I fear I might be a little snowblind to my own code by now.
- Reporting of the error of the scenario player to rocketchat is still vague. As of now it only indicated if there was a failure, but not why it actually failed. It was requested that this be more explicit.
- Adapt/update the log script written by Rakan, so it becomes compatible with the new setup.

If there's anything unclear or you need things added/changed/updated, please let me know!

@Dominik1999

**Comment by nlsdfnbch** [comment] 2020-02-03 14:25
Another update: turns out the docker image used to run the scenarios was outdated.
As it relies on commits to the sp repo to build new versions, we are not keeping up with the raiden repo.
I will add a call to a build trigger to the raiden repo to kick off the build of a new nightly sp environment whenever a commit is merged to raiden.

That should resolve the issue.

**Comment by Dominik1999** [comment] 2020-02-07 15:22
ok it looks like parallel execution works now with the new Ansible setup

**Closed by Dominik1999** 2020-02-07 15:22 UTC
Labels: Component / Scenario Player, State / Needs discussion, Type / Enhancement
