### ISSUE TITLE
Something went wrong in PUT requesting when sending messages to offline partner

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1917] opened 2018-07-23 06:56 UTC
When restarting the node after a long time, and the WAL is replayed the raiden node tries to send messages to an old partner that is offline. When that happens a matrix exception causes the client to crash. 

Raiden LOG 1: https://gist.github.com/LefterisJP/bcb2fb54bec759afefa94885e1f29a5b
Raiden LOG 2: https://gist.github.com/LefterisJP/f63d06bf840ef07e89bbcc276492146b

Came out of: #1897

**Comment by andrevmatos** [comment] 2018-07-25 19:35
Probably fixed by raiden-network/raiden-libs#111 and #1934

**Comment by ulope** [comment] 2018-07-25 21:33
Just to document what we found out in person: It looks like this specific issue (`Name or service not known`) is caused by an undefined networking glitch in @LefterisJP's machine, however we should be able to survive brief interruptions. Aa @andrevmatos said, probably fixed raiden-network/raiden-libs#111.
If the problem re-appears we can re-open this one.

**Closed by ulope** 2018-07-25 21:33 UTC
