### ISSUE TITLE
Change EVERY scenario to default fee 0 of token network address: "0x62083c80353Df771426D209eF578619EE68D5C7A"

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/raiden#4890] opened 2019-09-16 07:56 UTC
### Original Issue
Once mediation fee default is implemented #4731 then change EVERY scenario to default fee 0 of token network address: "0x62083c80353Df771426D209eF578619EE68D5C7A"

### Analysis from https://github.com/raiden-network/raiden/issues/4890#issuecomment-534161673
- It looks like at the moment all scenarios use the default mediation fees as set in [here](https://github.com/raiden-network/raiden/blob/c9169b1fb95bbc0782c201eb3e769117f1a10b05/raiden/settings.py#L57)
- The scenarios all pass, because of the transferred amounts being too small for fee deduction 
- However, in pfs1, pfs2, pfs3, pfs4, pfs5, pfs6, pfs8 and pfs9 we never check the final channel state / balance so we wouldn't see any deducted fees anyway

### Solution
- We should make sure that no fees are used in the current scenarios, this is reflected in that issue
- We should update every scenario such that the final channel state is asserted, see https://github.com/raiden-network/raiden/issues/4962
- We should use higher token amounts in our scenarios such that, we see if fees are deducted or not, i.e. instead of sending 1 token, send 1 * 10 ** 18 tokens, see https://github.com/raiden-network/raiden/issues/4963

**Comment by palango** [comment] 2019-09-18 10:22
@czepluch How do I do that in a scenario?

**Comment by czepluch** [comment] 2019-09-18 10:28
@palango the `nodes` option in the scenario files takes all the same arguments as the raiden node itself, so you should be able to set it there if I understand this issue correctly.

**Comment by palango** [comment] 2019-09-18 12:30
@czepluch @ulope Is it possible to give two arguments? In my example (for the flat fees) I need something like:
```
    flat-fee: 0x62083c80353Df771426D209eF578619EE68D5C7A 100
```

**Comment by czepluch** [comment] 2019-09-18 12:40
@palango I don't get any complaints from the SP when running like that just now, but can't verify if it actually works as intended yet.

**Comment by czepluch** [comment] 2019-09-18 12:42
Alright. I take that back. It doesn't seem to work with multiple arguments right now.

**Comment by palango** [comment] 2019-09-18 12:42
I got this while trying:
`Error: Invalid value for "--flat-fee": Address must be EIP55 checksummed`

**Comment by czepluch** [comment] 2019-09-18 12:43
Yeah, same here.

**Comment by czepluch** [comment] 2019-09-18 12:44
But according to `.stdout` it seems to have tried to start Raiden with the correct arguments.

**Comment by Dominik1999** [comment] 2019-09-23 15:50
ok, 
- It looks like at the moment all scenarios use the default mediation fees as set in [here](https://github.com/raiden-network/raiden/blob/c9169b1fb95bbc0782c201eb3e769117f1a10b05/raiden/settings.py#L57)
- The scenarios all pass, because of the transferred amounts being too small for fee deduction 
- However, in pfs1, pfs2, pfs3, pfs4, pfs5, pfs6, pfs8 and pfs9 we never check the final channel state / balance so we wouldn't see any deducted fees anyway

that leads to the following:
- We should make sure that no fees are used in the current scenarios, this is reflected in that issue
- We should update every scenario such that the final channel state is asserted, see <insert issue>
- We should use higher token amounts in our scenarios such that, we see if fees are deducted or not, i.e. instead of sending 1 token, send 1 * 10 ** 18 tokens <insert issue>

**Closed** 2019-09-24 06:32 UTC
Labels: scenario player
