### ISSUE TITLE
test_blockchainservice.py fails

### ISSUE THREAD

**Issue by schmir** [raiden-network/raiden#290] opened 2016-12-16 22:38 UTC
With raiden 0.0.4, geth 1.5.5 stable I get the following error with test_blockchainservice.py:

```
(local) ~/raiden (git)-[master] % tox -e py27 -- raiden/tests/integration/test_blockchainservice.py
GLOB sdist-make: /home/ralf/raiden/setup.py
py27 inst-nodeps: /home/ralf/raiden/.tox/dist/raiden-0.0.4.zip
py27 installed: alabaster==0.7.9,Babel==2.3.4,backports.shutil-get-terminal-size==1.0.0,bitcoin==1.1.42,bumpversion==0.5.3,cffi==1.9.1,click==6.6,CodernityDB==0.5.0,coverage==4.2,decorator==4.0.10,devp2p==0.8.0,docutils==0.13.1,enum34==1.1.6,ethereum==1.6.0,ethereum-serpent==2.0.2,gevent==1.1.0,gevent-websocket==0.9.4,gipc==0.4.0,greenlet==0.4.11,imagesize==0.7.1,ipaddress==1.0.17,ipython==4.2.1,ipython-genutils==0.1.0,Jinja2==2.8,leveldb==0.194,lmdb==0.92,MarkupSafe==0.23,miniupnpc==1.9,networkx==1.11,pathlib2==2.1.0,pbkdf2==1.3,pexpect==4.2.1,pickleshare==0.7.4,pluggy==0.4.0,ptyprocess==0.5.1,py==1.4.32,pycparser==2.17,pycryptodome==3.4.3,pyelliptic==1.5.7,pyethapp==1.5.0,pyethash==0.1.27,Pygments==2.1.3,pysha3==0.3,pytest==3.0.5,pytest-random==0.2,pytest-timeout==1.2.0,pytz==2016.10,PyYAML==3.12,raiden==0.0.4,repoze.lru==0.6,requests==2.12.4,rlp==0.4.7,scrypt==0.8.0,secp256k1==0.12.1,simplegeneric==0.8.1,six==1.10.0,snowballstemmer==1.2.1,Sphinx==1.5.1,statistics==1.0.3.5,tinyrpc==0.5,tox==2.5.0,traitlets==4.3.1,u-msgpack-python==2.3.0,virtualenv==15.1.0,Werkzeug==0.11.11
py27 runtests: PYTHONHASHSEED='2199530976'
py27 runtests: commands[0] | coverage erase
py27 runtests: commands[1] | coverage run --append -m py.test --exitfirst raiden/tests/integration/test_blockchainservice.py
============================================================ test session starts ============================================================
platform linux2 -- Python 2.7.11+, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: /home/ralf/raiden, inifile: 
plugins: timeout-1.2.0, random-0.2
collected 2 items 

raiden/tests/integration/test_blockchainservice.py E

================================================================== ERRORS ===================================================================
_____________________________________ ERROR at setup of test_new_netting_contract[0-0-3-blockchain:{}] ______________________________________

request = <SubRequest 'blockchain_services' for <Function 'test_new_netting_contract[0-0-3-blockchain:{}]'>>
deploy_key = '\xd8\x06\x8ez\xe4\xbc\x03\x07&\x01\x1e\x0b\xe7(\xf8`\xf3<}d\x1c$\xc0\xc1\\e\x002j;\x8b\x89'
private_keys = ['\xab@\\;{\xf5n_\\\x01*\xac\x19\xf0|\xb6\xa2\xdf\x81\xb80\xc6\xef(-\xffB\xc0\xf7\xa0\xe0 ', '\x88\xa6\x1b\xbb\xe5|g*\...\xf5W\xc7j\x1d\xda', "xN\x8a\xdc\xe34yX\xf3\x86k\x19\x13q\x86\x98<\xf2G\xa1\x92\x96\xa8\x80\xe5\xc4'\xa1\xedO\x88\x9c"]
poll_timeout = 60
blockchain_backend = [<subprocess.Popen object at 0x7fc09d7b0050>, <subprocess.Popen object at 0x7fc09d7b09d0>, <subprocess.Popen object at 0x7fc09d761510>]
blockchain_rpc_ports = [29873, 29874, 29875], blockchain_type = 'geth', tester_blockgas_limit = 10000000000, cached_genesis = None

    @pytest.fixture
    def blockchain_services(
            request,
            deploy_key,
            private_keys,
            poll_timeout,
            blockchain_backend,  # This fixture is required because it will start
                                 # the geth subprocesses
            blockchain_rpc_ports,
            blockchain_type,
            tester_blockgas_limit,
            cached_genesis):
    
        verbose = request.config.option.verbose
    
        if blockchain_type in ('geth',):
    
            registry_address = None
            if cached_genesis:
                registry_address = cached_genesis['config'].get('defaultRegistryAddress')
    
                if registry_address:
                    registry_address = address_decoder(registry_address)
    
            return _jsonrpc_services(
                deploy_key,
                private_keys,
                verbose,
                poll_timeout,
                blockchain_rpc_ports[0],
>               registry_address,
            )

raiden/tests/fixtures/blockchain.py:237: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
raiden/tests/fixtures/blockchain.py:365: in _jsonrpc_services
    timeout=poll_timeout,
.tox/py27/local/lib/python2.7/site-packages/pyethapp/rpc_client.py:243: in deploy_solidity_contract
    gasprice=gasprice,
raiden/network/rpc/client.py:71: in send_transaction
    'pending',
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <JSONRPCClient @29873>, method = 'eth_getTransactionCount', args = ('7d0eae79cf2685eff5933b45b981921ba8fe0be6', 'pending')
request = <tinyrpc.protocols.jsonrpc.JSONRPCRequest object at 0x7fc09cc7c790>
reply = '{"jsonrpc":"2.0","id":6,"error":{"code":-32602,"message":"missing 0x prefix for hex data"}}\n'
jsonrpc_reply = <tinyrpc.protocols.jsonrpc.JSONRPCErrorResponse object at 0x7fc09cc7cbd0>

    def call(self, method, *args):
        """ Do the request and returns the result.
    
            Args:
                method (str): The RPC method.
                args: The encoded arguments expected by the method.
                    - Object arguments must be supplied as an dictionary.
                    - Quantity arguments must be hex encoded starting with '0x' and
                    without left zeros.
                    - Data arguments must be hex encoded starting with '0x'
            """
        request = self.protocol.create_request(method, args)
        reply = self.transport.send_message(request.serialize())
        if self.print_communication:
            print json.dumps(json.loads(request.serialize()), indent=2)
            print reply
    
        jsonrpc_reply = self.protocol.parse_reply(reply)
        if isinstance(jsonrpc_reply, JSONRPCSuccessResponse):
            return jsonrpc_reply.result
        elif isinstance(jsonrpc_reply, JSONRPCErrorResponse):
>           raise JSONRPCClientReplyError(jsonrpc_reply.error)
E           JSONRPCClientReplyError: missing 0x prefix for hex data

.tox/py27/local/lib/python2.7/site-packages/pyethapp/rpc_client.py:370: JSONRPCClientReplyError
----------------------------------------------------------- Captured stdout setup -----------------------------------------------------------
Your new account is locked with a password. Please give a password. Do not forget this password.
!! Unsupported terminal, password will be echoed.
Passphrase: 
Repeat passphrase: 
Address: {a81cb4af5501f5407337cb5c13850cf882a1ae27}
Unlocking account 0 | Attempt 1/3
!! Unsupported terminal, password will be echoed.
Passphrase: 
{
  "id": 5, 
  "jsonrpc": "2.0", 
  "method": "eth_nonce", 
  "params": [
    "7d0eae79cf2685eff5933b45b981921ba8fe0be6", 
    "pending"
  ]
}
{"jsonrpc":"2.0","id":5,"error":{"code":-32601,"message":"The method eth_nonce does not exist/is not available"}}

{
  "id": 6, 
  "jsonrpc": "2.0", 
  "method": "eth_getTransactionCount", 
  "params": [
    "7d0eae79cf2685eff5933b45b981921ba8fe0be6", 
    "pending"
  ]
}
{"jsonrpc":"2.0","id":6,"error":{"code":-32602,"message":"missing 0x prefix for hex data"}}

----------------------------------------------------------- Captured stderr setup -----------------------------------------------------------
/home/ralf/raiden/.tox/py27/local/lib/python2.7/site-packages/secp256k1/__init__.py:228: UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  self.ctx, res_compressed, outlen, self.public_key, compflag)
I1216 23:35:33.114582 cmd/utils/flags.go:615] WARNING: No etherbase set and no accounts found as default
I1216 23:35:33.114751 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /tmp/pytest-of-ralf/pytest-2/test_new_netting_contract_0_0_0/f68952f08b60b79a5dbd3ec754ee33e6e52101fcf1d8055fc89979c253b14832/geth/chaindata
I1216 23:35:33.123475 ethdb/database.go:176] closed db:/tmp/pytest-of-ralf/pytest-2/test_new_netting_contract_0_0_0/f68952f08b60b79a5dbd3ec754ee33e6e52101fcf1d8055fc89979c253b14832/geth/chaindata
I1216 23:35:33.123557 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /tmp/pytest-of-ralf/pytest-2/test_new_netting_contract_0_0_0/f68952f08b60b79a5dbd3ec754ee33e6e52101fcf1d8055fc89979c253b14832/geth/chaindata
I1216 23:35:33.139719 cmd/geth/chaincmd.go:131] successfully wrote genesis block and/or chain rule set: c98f0e87d1b9027a15d08289f173e9eb98c151abdbd60a1176c9aa82997f9c22
I1216 23:35:34.092029 cmd/utils/flags.go:615] WARNING: No etherbase set and no accounts found as default
I1216 23:35:34.092163 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /tmp/pytest-of-ralf/pytest-2/test_new_netting_contract_0_0_0/7372d071baabaabeb968270cbe672094f872093713d6483ced88c3dfec537d9b/geth/chaindata
I1216 23:35:34.101640 ethdb/database.go:176] closed db:/tmp/pytest-of-ralf/pytest-2/test_new_netting_contract_0_0_0/7372d071baabaabeb968270cbe672094f872093713d6483ced88c3dfec537d9b/geth/chaindata
I1216 23:35:34.101721 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /tmp/pytest-of-ralf/pytest-2/test_new_netting_contract_0_0_0/7372d071baabaabeb968270cbe672094f872093713d6483ced88c3dfec537d9b/geth/chaindata
I1216 23:35:34.116255 cmd/geth/chaincmd.go:131] successfully wrote genesis block and/or chain rule set: c98f0e87d1b9027a15d08289f173e9eb98c151abdbd60a1176c9aa82997f9c22
I1216 23:35:34.173194 cmd/utils/flags.go:615] WARNING: No etherbase set and no accounts found as default
I1216 23:35:34.173325 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /tmp/pytest-of-ralf/pytest-2/test_new_netting_contract_0_0_0/69b23cde8d25f4c971f091b0cd90114d9a6e495f7d863a411376451c87b2100f/geth/chaindata
I1216 23:35:34.179756 ethdb/database.go:176] closed db:/tmp/pytest-of-ralf/pytest-2/test_new_netting_contract_0_0_0/69b23cde8d25f4c971f091b0cd90114d9a6e495f7d863a411376451c87b2100f/geth/chaindata
I1216 23:35:34.179856 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /tmp/pytest-of-ralf/pytest-2/test_new_netting_contract_0_0_0/69b23cde8d25f4c971f091b0cd90114d9a6e495f7d863a411376451c87b2100f/geth/chaindata
I1216 23:35:34.195209 cmd/geth/chaincmd.go:131] successfully wrote genesis block and/or chain rule set: c98f0e87d1b9027a15d08289f173e9eb98c151abdbd60a1176c9aa82997f9c22
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================== 1 error in 6.03 seconds ==========================================================
ERROR: InvocationError: '/home/ralf/raiden/.tox/py27/bin/coverage run --append -m py.test --exitfirst raiden/tests/integration/test_blockchainservice.py'
__________________________________________________________________ summary __________________________________________________________________
ERROR:   py27: commands failed
tox -e py27 -- raiden/tests/integration/test_blockchainservice.py  10.02s user 0.64s system 77% cpu 13.846 total
```

**Comment by hackaugusto** [comment] 2016-12-17 09:05
This is probably due to an out-dated dependency. Can you try upgrading solc to >=0.4.4 and recreating the tox envs?

**Comment by schmir** [comment] 2016-12-17 09:32
That didn't help. I suspect it may have something to do with the geth version I'm using.
```
...
{"jsonrpc":"2.0","id":5,"error":{"code":-32601,"message":"The method eth_nonce does not exist/is not available"}}
...
```

**Comment by LefterisJP** [comment] 2016-12-17 10:18
@schmir Which version of geth are you using?

**Comment by schmir** [comment] 2016-12-17 11:30
```
(local) ~ % geth version
Geth
Version: 1.5.5-stable
Git Commit: ff07d54843ea7ed9997c420d216b4c007f9c80c3
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
OS: linux
GOPATH=
GOROOT=/usr/lib/go-1.7
```

**Comment by LefterisJP** [comment] 2016-12-18 13:40
Hmmm all right so I have located at least one place in pyethapp where we need to make changes. The problem is multi-layered.

Geth got [this PR](https://github.com/ethereum/go-ethereum/pull/3355/files) inside the 1.5.4 release which change the way they encode/decode things. From a quick look it's mostly internal fixes but they also seem to have gotten more strict about wanting every address to be prefixed with `0x`. It seems we don't do that in every place inside pyethapp.

This is what leads to the actual error. For example [here](https://github.com/ethereum/pyethapp/blob/develop/pyethapp/rpc_client.py#L254) you would need to make sure that the contract address is prefixed with `0x`. There is probably more places this will happen. There is probably more places where this should be fixed.

The reason we don't see this in Travis is probably because we use an older version of geth.

@konradkonrad Can you handle this issue?

**Comment by konradkonrad** [comment] 2016-12-19 15:43
so one note here: `eth_nonce` is a non-spec method specific to pyethapp. the error you're seeing is (hopefully) from probing the server capabilities before the client behavior is adjusted for geth and should have nothing to do with the problem you're experiencing.

**Closed** 2016-12-20 13:51 UTC
Labels: showstopper
