### ISSUE TITLE
BF1 basic functionality fail  Payment couldn't be completed because: there is no route available

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5092] opened 2019-10-15 06:51 UTC
The `bf1_basic_functionality ` scenario fails with 
`Payment couldn't be completed because: there is no route available`

```
{"task": "<TransferTask: {'from': 3, 'to': 0, 'amount': 1000000000000000, 'lock_timeout': 30}>", "event": "Task errored", "logger": "scenario_player.tasks.base", "level": "error", "timestamp": "2019-10-14 03:57:13.734499", "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 74, in __call__\n    return self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 59, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.legacy.RESTAPIStatusMismatchError: HTTP status code \"409\" while fetching http://127.0.0.1:33845/api/v1/payments/0x62083c80353Df771426D209eF578619EE68D5C7A/0x3EC1468397Cb8f6CEa92f53d4DAa893f76c21926. Expected 2..: {\"errors\": \"Payment couldn't be completed because: there is no route available\"}"}
```
[Scenario_player_Logs-bf1_basic_functionality-1-latest-2019-10-14.tar.gz](https://github.com/raiden-network/raiden/files/3727697/Scenario_player_Logs-bf1_basic_functionality-1-latest-2019-10-14.tar.gz)

**Comment by rakanalh** [comment] 2019-10-15 11:26
Caused by #5059.

Closing.

**Closed by rakanalh** 2019-10-15 11:26 UTC
