### ISSUE TITLE
Flaky teardown in test_cli_manual_account_selection

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#4419] opened 2019-07-18 10:29 UTC
```
test teardown failure
>       lambda: ihook(item=item, **kwds),
        when=when,
    )

../venv-3.7-LINUX/lib/python3.7/site-packages/flaky/flaky_pytest_plugin.py:306: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../venv-3.7-LINUX/lib/python3.7/site-packages/six.py:693: in reraise
    raise value
../venv-3.7-LINUX/lib/python3.7/site-packages/six.py:693: in reraise
    raise value
../venv-3.7-LINUX/lib/python3.7/site-packages/six.py:693: in reraise
    raise value
raiden/tests/integration/cli/conftest.py:62: in raiden_testchain
    yield args
/usr/local/lib/python3.7/contextlib.py:119: in __exit__
    next(self.gen)
raiden/tests/utils/smoketest.py:209: in setup_testchain
    web3=web3,
/usr/local/lib/python3.7/contextlib.py:119: in __exit__
    next(self.gen)
raiden/tests/utils/eth_node.py:527: in run_private_blockchain
    yield executors
/usr/local/lib/python3.7/contextlib.py:119: in __exit__
    next(self.gen)
raiden/tests/utils/eth_node.py:429: in eth_run_nodes
    yield executors
/usr/local/lib/python3.7/contextlib.py:524: in __exit__
    raise exc_details[1]
/usr/local/lib/python3.7/contextlib.py:509: in __exit__
    if cb(*exc_details):
/usr/local/lib/python3.7/contextlib.py:377: in _exit_wrapper
    return cm_exit(cm, exc_type, exc, tb)
../venv-3.7-LINUX/lib/python3.7/site-packages/mirakuru/base.py:140: in __exit__
    self.stop()
raiden/utils/http.py:198: in stop
    super().stop()
../venv-3.7-LINUX/lib/python3.7/site-packages/mirakuru/base.py:284: in stop
    self.wait_for(process_stopped)
../venv-3.7-LINUX/lib/python3.7/site-packages/mirakuru/base.py:350: in wait_for
    time.sleep(self._sleep)
../venv-3.7-LINUX/lib/python3.7/site-packages/gevent/hub.py:159: in sleep
    hub.wait(t)
src/gevent/_hub_primitives.py:46: in gevent.__hub_primitives.WaitOperationsGreenlet.wait
    ???
src/gevent/_hub_primitives.py:55: in gevent.__hub_primitives.WaitOperationsGreenlet.wait
    ???
src/gevent/_waiter.py:151: in gevent.__waiter.Waiter.get
    ???
src/gevent/_greenlet_primitives.py:59: in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
    ???
src/gevent/_greenlet_primitives.py:59: in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
    ???
src/gevent/_greenlet_primitives.py:63: in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   Failed: Timeout >45.0s

src/gevent/__greenlet_primitives.pxd:35: Failed
```

Seen in https://circleci.com/gh/raiden-network/raiden/65011#tests/containers/18

[results.zip](https://github.com/raiden-network/raiden/files/3406072/results.zip)
[raiden-debug_2019-07-18T09:47:10.927476.log](https://github.com/raiden-network/raiden/files/3406073/raiden-debug_2019-07-18T09.47.10.927476.log)

**Comment by hackaugusto** [comment] 2019-07-26 10:56
This is a duplicate of https://github.com/raiden-network/raiden/issues/4450:

test setup starts at 2019-07-18 09:46:42 [first line](https://65011-50646767-gh.circle-artifacts.com/18/eth-logs/parity/add4d310.log) [45s left]
test call starts at 2019-07-18 09:47:12.747440 [first line](https://65011-50646767-gh.circle-artifacts.com/18/eth-logs/test_cli_manual_account_selection%5Bremoved_args0-0.19.0-development%5D/raiden_nodes/cli_test.log) [15s left]
teardown starts at 2019-07-18 09:47:17.693493 [ref](https://65011-50646767-gh.circle-artifacts.com/18/eth-logs/test_cli_manual_account_selection%5Bremoved_args0-0.19.0-development%5D/raiden-debug_2019-07-18T09%3A47%3A10.927476.log) [10s left]
process only exist at 2019-07-18 09:48:10 [last line at](https://65011-50646767-gh.circle-artifacts.com/18/eth-logs/parity/add4d310.log)

10s is the waiting time set in the executor, this leads to a race were the timeout can be raised before the kill signal is sent. which seems to be the case.

**Closed by hackaugusto** 2019-07-26 10:56 UTC
Labels: testing
