### ISSUE TITLE
can't open a channel

### ISSUE THREAD

**Issue by zhouzhou84** [raiden-network/raiden#2124] opened 2018-08-09 09:15 UTC
## Problem Definition
when I use this command to open a channel with other node, I wait it for over 20minutes but nothing happens, I can't wait it all the time , so I use`ctrl +C`to shut  it down.
```
curl -i -X PUT http://localhost:5001/api/1/channels -H 'Content-Type: application/json' --data-raw '{"balance": 1000, "partner_address": "0x13AE1c7fb262be079d7850d435D75a9bFC141b8e", "settle_timeout": 600, "token_address": "0x5d662156c457Ee5B0169dD9475E537E7e73546D5"}'
```

[raiden-debug.log](https://github.com/raiden-network/raiden/files/2273519/raiden-debug.log)

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
$ uname -a
Linux ip-172-31-15-69 4.4.0-1061-aws #70-Ubuntu SMP Fri May 25 21:47:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

command -v solc && solc --version
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Linux.g++

command -v geth && geth version
/usr/bin/geth
Geth
Version: 1.8.13-stable
Git Commit: 225171a4bfcc16bd12a1906b1e0d43d0b18c353b
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10
Operating System: linux
GOPATH=/home/ubuntu/gocode
GOROOT=/usr/lib/go-1.10


command -v parity && parity --version
command -v raiden && raiden version/usr/bin/raiden
{
  "raiden": "0.4.2",
  "python_implementation": "CPython",
  "python_version": "3.6.6",
  "system": "Linux 64bit_ELF 4.4.0-1061-aws x86_64",
  "distribution": "bundled"
}


[ -d .git ] && git rev-parse HEAD
```

**Comment by palango** [comment] 2018-08-09 09:30
Hi @zhouzhou84 From the logs I can see that you tried to connect to the token network, but then there were no partners to connect to.
```
2018-08-08 03:54:16 [info     ] 127.0.0.1 - - [2018-08-08 03:54:16] "PUT /api/1/connections/0x5d662156c457Ee5B0169dD9475E537E7e73546D5 HTTP/1.1" 204 143 91.553191 [raiden.api.rest.pywsgi] 
2018-08-08 03:54:16 [debug    ] found 0 partners               [raiden.connection_manager] 
2
```

Then when you try to send the payment it seems like the target is not available and the payment fails:
```
2018-08-08 05:13:53 [info     ] 127.0.0.1 - - [2018-08-08 05:13:53] "POST /api/1/transfers/0x5d662156c457Ee5B0169dD9475E537E7e73546D5/0x13AE1c7fb262be079d7850d435D75a9bFC141b8e HTTP/1.1" 409 246 0.188925 [raiden.api.rest.pywsgi] 
```

Here the `409` is the error code. Do you have control over the other node as well and can make sure that it is online. Can you also look if you have an open channel for that token network?

**Comment by zhouzhou84** [comment] 2018-08-09 10:00
0 partner, should I let the other node which I use the 5002 port to create connectto the `0x5d662156c457Ee5B0169dD9475E537E7e73546D5`, but when I use command `curl -i -X PUT http://localhost:5002/api/1/connections/0x5d662156c457Ee5B0169dD9475E537E7e73546D5 -H 'Content-Type: application/json' --data-raw '{"funds": 2000}'
`
it should wait a long time and nothing happen...
by the way , 5001 and 5002 is  in the same account  and different address, one is account[0],another is account[1]

**Comment by zhouzhou84** [comment] 2018-08-09 10:01
maybe I am wrong, they are two accounts:
```
Welcome to Raiden, version 0.4.2!
----------------------------------------------------------------------
| This is an Alpha version of experimental open source software      |
| released under the MIT license and may contain errors and/or bugs. |
| Use of the software is at your own risk and discretion. No         |
| guarantee whatsoever is made regarding its suitability for your    |
| intended purposes and its compliance with applicable law and       |
| regulations. It is up to the user to determine the software´s      |
| quality and suitability and whether its use is compliant with its  |
| respective regulatory regime, especially in the case that you are  |
| operating in a commercial context.                                 |
----------------------------------------------------------------------
The following accounts were found in your machine:

[  0] - 0x3C46570896F3eC1323280Df466716d1076a7162B
[  1] - 0x13AE1c7fb262be079d7850d435D75a9bFC141b8e

Select one of them by index to continue: 0

```

**Comment by palango** [comment] 2018-08-09 13:31
Do you have Raiden nodes for both account 0 and 1 running at the same time?

**Comment by LefterisJP** [comment] 2018-08-11 17:45
@rakanalh This is the same thing you experienced locally with two different nodes. But when trying with peers over the network it worked. Could this be an actual issue with running two local nodes?

**Comment by rakanalh** [comment] 2018-08-13 09:37
The issue that i experienced was an exception in transmitting a transfer to a different node running locally. I just tested the case being described here and i confirm this is reproducible.

Steps to reproduce:
1. Start Geth
```
geth --testnet --fast --rpc --rpcapi eth,net,web3 --rpccorsdomain "http://localhost:5001,http://localhost:5002" --ipcpath ./geth.ipc
```
2. Run Raiden in a terminal window.
```
raiden --keystore-path ~/.ethereum/testnet/keystore/ --log-config "raiden.raiden_service:DEBUG,raiden.blockchain_events_handler:DEBUG,raiden.network.proxies.token_network:DEBUG
```
2. Run Raiden with a different account on a different terminal window
```
raiden --keystore-path ~/.ethereum/testnet/keystore/ --log-config "raiden.raiden_service:DEBUG,raiden.blockchain_events_handler:DEBUG,raiden.network.proxies.token_network:DEBUG --api-address 127.0.0.1:5002
```
4. Try to open a channel / join a network from the second Raiden node. 
```
curl -i -X PUT http://localhost:5002/api/1/channels -H 'Content-Type: application/json' --data-raw '{"balance": 5, "partner_address": "0x6D1aE2fA14078B5Dbc46501Bcc0623C67aA7b5cF", "settle_timeout": 500, "token_address": "0x0f114A1E9Db192502E7856309cc899952b3db1ED"}'
```

One thing i noticed which is quite strange:
When fetching the list of channels:
```
curl -v http://localhost:5002/api/1/channels
[]
```
The logs for the Raiden node shows:
```
The Raiden API RPC server is now running at http://127.0.0.1:5002/.

See the Raiden documentation for all available endpoints at
http://raiden-network.readthedocs.io/en/stable/rest_api.html
You're running version 0.3.1.dev984+ga662e898. The latest version is 0.5.0
It's time to update! Releases: https://github.com/raiden-network/raiden/releases
2018-08-13 09:34:44 [info     ] 127.0.0.1 - - [2018-08-13 11:34:44] "GET /api/1/channels HTTP/1.1" 200 137 0.000847 [raiden.api.rest.pywsgi]
```
However, when making the request for opening a channel, the request isn't logged in the Raiden node.

**Comment by zhouzhou84** [comment] 2018-08-13 09:48
@rakanalh Now I run the raiden successfully,it's strange because I don't know what happened, I can do these operations:

```
ubuntu@ip-172-31-15-69:~$ http --timeout 300 GET :5001/api/1/channels
HTTP/1.1 200 OK
Content-Length: 308
Content-Type: application/json
Date: Mon, 13 Aug 2018 09:23:54 GMT
mimetype: application/json

[
    {
        "balance": 38, 
        "channel_identifier": 1, 
        "partner_address": "0x13AE1c7fb262be079d7850d435D75a9bFC141b8e", 
        "reveal_timeout": 10, 
        "settle_timeout": 600, 
        "state": "opened", 
        "token_address": "0x5d662156c457Ee5B0169dD9475E537E7e73546D5", 
        "token_network_identifier": "0x34673D980317921706c586178f60eF952cE52C49"
    }
]

ubuntu@ip-172-31-15-69:~$ http --timeout 300 GET :5001/api/1/address
HTTP/1.1 200 OK
Content-Length: 61
Content-Type: application/json
Date: Mon, 13 Aug 2018 09:24:57 GMT
mimetype: application/json

{
    "our_address": "0x3C46570896F3eC1323280Df466716d1076a7162B"
}

ubuntu@ip-172-31-15-69:~$ http --timeout 300 GET :5001/api/1/tokens
HTTP/1.1 200 OK
Content-Length: 138
Content-Type: application/json
Date: Mon, 13 Aug 2018 09:25:25 GMT
mimetype: application/json

[
    "0x0f114A1E9Db192502E7856309cc899952b3db1ED", 
    "0x68fB3bc1572b917096C9FcaF0A0A46a7b79544f6", 
    "0x5d662156c457Ee5B0169dD9475E537E7e73546D5"
]

ubuntu@ip-172-31-15-69:~$ http --timeout 300 GET :5001/api/1/channels
HTTP/1.1 200 OK
Content-Length: 308
Content-Type: application/json
Date: Mon, 13 Aug 2018 09:26:02 GMT
mimetype: application/json

[
    {
        "balance": 38, 
        "channel_identifier": 1, 
        "partner_address": "0x13AE1c7fb262be079d7850d435D75a9bFC141b8e", 
        "reveal_timeout": 10, 
        "settle_timeout": 600, 
        "state": "opened", 
        "token_address": "0x5d662156c457Ee5B0169dD9475E537E7e73546D5", 
        "token_network_identifier": "0x34673D980317921706c586178f60eF952cE52C49"
    }
]

ubuntu@ip-172-31-15-69:~$ http --timeout 300 GET :5001/api/1/connections
HTTP/1.1 200 OK
Content-Length: 96
Content-Type: application/json
Date: Mon, 13 Aug 2018 09:26:20 GMT

{
    "0x5d662156c457Ee5B0169dD9475E537E7e73546D5": {
        "channels": 1, 
        "funds": 0, 
        "sum_deposits": 50
    }
}


```

**Comment by rakanalh** [comment] 2018-08-13 09:55
Originally, your failed requests were directed at the second node:
> curl -i -X PUT http://localhost:5002/api/1/connections/0x5d662156c457Ee5B0169dD9475E537E7e73546D5 -H 'Content-Type: application/json' --data-raw '{"funds": 2000}'

I think we need to investigate this case a bit further on why requests aren't going through the second node's HTTP server.

**Comment by zhouzhou84** [comment] 2018-08-13 10:01
@rakanalh ok thank you 
by the way I think there is a small bug when you start raiden:
```
ubuntu@ip-172-31-15-69:~/xud/bin$ raiden --keystore-path  ~/data/eth_ropsten/keystore
Welcome to Raiden, version 0.5.0!
----------------------------------------------------------------------
| This is an Alpha version of experimental open source software      |
| released under the MIT license and may contain errors and/or bugs. |
| Use of the software is at your own risk and discretion. No         |
| guarantee whatsoever is made regarding its suitability for your    |
| intended purposes and its compliance with applicable law and       |
| regulations. It is up to the user to determine the software´s      |
| quality and suitability and whether its use is compliant with its  |
| respective regulatory regime, especially in the case that you are  |
| operating in a commercial context.                                 |
----------------------------------------------------------------------
The following accounts were found in your machine:

[  0] - 0x3C46570896F3eC1323280Df466716d1076a7162B
[  1] - 0x13AE1c7fb262be079d7850d435D75a9bFC141b8e

Select one of them by index to continue: 0
Enter the password to unlock 0x3C46570896F3eC1323280Df466716d1076a7162B: 
Traceback (most recent call last):
  File "raiden-script.py", line 2, in <module>
  File "site-packages/raiden/__main__.py", line 11, in main
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1043, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "site-packages/click/decorators.py", line 17, in new_func
  File "site-packages/raiden/ui/cli.py", line 1053, in run
  File "site-packages/raiden/ui/cli.py", line 907, in run
  File "site-packages/raiden/ui/cli.py", line 925, in _run_app
  File "site-packages/raiden/ui/cli.py", line 623, in run_app
  File "site-packages/raiden/network/rpc/client.py", line 209, in __init__
  File "site-packages/web3/eth.py", line 238, in getTransactionCount
  File "site-packages/web3/manager.py", line 110, in request_blocking
ValueError: {'code': -32000, 'message': 'missing trie node 1ff62ec1eef09982cff95032158aa8cd9ef318b8f1728cc1af42f8cef3819ebc (path 0a0f)'}
[2877] Failed to execute script raiden-script

```
But if you try again , it works well

**Comment by zhouzhou84** [comment] 2018-08-13 10:12
@rakanalh I ask the question about :how to do Atomic Swap using command line instead of webUI? 
at gitter raiden group, but nobody reply me , Do you know something about command for Atomic Swap?

**Comment by hackaugusto** [comment] 2018-08-13 10:28
> Do you know something about command for Atomic Swap?

We temporarily removed that feature, it will be added by #303

**Comment by zhouzhou84** [comment] 2018-08-13 10:32
so we can only do swap by webUI,but if someone use AWS , just a ssh connection, we can not do that

**Comment by palango** [comment] 2018-08-21 10:27
@zhouzhou84 We removed the Token Swap feature temporarily because of some architecture changes. You can follow #303 to get updates.

Did you manage to open the channel? Then we can close this issue. Also, do you still see the error from https://github.com/raiden-network/raiden/issues/2124#issuecomment-412468605 ?

**Comment by palango** [comment] 2018-08-27 09:38
@zhouzhou84 I didn't hear back so I assume the issue is fixed. If if still occurs please re-open this issue.

**Closed by palango** 2018-08-27 09:38 UTC
