### ISSUE TITLE
[Feature request] Raiden support for Windows

### ISSUE THREAD

**Issue by RostyslavAntonyshyn** [raiden-network/raiden#6441] opened 2020-08-04 10:34 UTC
## Abstract

Make Raiden compatible with Windows.

## Motivation

We are in the process of building a solution on top of raiden network, having lots of users currently running on Windows, which is stopping them from using it. Would be very useful to have raiden, windows compatible out of box for each release.

**Comment by ulope** [comment] 2020-08-04 11:17
Related: #2482

**Comment by karlb** [comment] 2020-08-17 09:42
Duplicate of #2482.

There are currently the options of using WSL, docker or the JS light client on Windows. I would be interested in hearing more about your use case to understand why these options are insufficient. The first two options should be fine for developers and service operators and the JS client can be a good choice for end users (although it still does have some limitations compared to the python client). If you have any input on this, please leave a comment in #2482. Thanks!

**Closed by karlb** 2020-08-17 09:42 UTC

**Comment by pepae** [comment] 2020-10-29 09:33
I think WSL won't work for Stakenet, as it would require their users to set up WSL. Normally their user experience is much more straightforward, just an installer. @RostyslavAntonyshyn that right?
